package com.qiwkreport.qiwk.etl.flex.domain;

import java.util.Date;

/**
 * @author abhilash
 *
 */
public class LCSColor {

	private int IDA2A2;
	private int IDA2TYPEDEFINITIONREFERENCE;
	private int IDA3CONTAINERREFERENCE;
	private int IDA3B8;
	private int IDA3A7;
	private int IDA3DOMAINREF;
	private int IDA3A2FOLDERINGINFO;
	private int IDA3B2FOLDERINGINFO;
	private int IDA3C8;
	private int IDA3A2OWNERSHIP;
	private int IDA3A2STATE;
	private int BRANCHIDA2TYPEDEFINITIONREFE;
	private int IDA3TEAMID;
	private int IDA3TEAMTEMPLATEID;
	private int MARKFORDELETEA2;
	private int UPDATECOUNTA2;
	private String PTC_STR_1TYPEINFOLCSCOLOR;
	private String COLORHEXIDECIMALVALUE;
	private String COLORNAME;
	private String FLEXTYPEIDPATH;
	private String SECURITYLABELS;
	private String THUMBNAIL;
	private Date CREATESTAMPA2;
	private Date UPDATESTAMPA2;
	
	public int getIDA2A2() {
		return IDA2A2;
	}
	public void setIDA2A2(int iDA2A2) {
		IDA2A2 = iDA2A2;
	}
	public int getIDA2TYPEDEFINITIONREFERENCE() {
		return IDA2TYPEDEFINITIONREFERENCE;
	}
	public void setIDA2TYPEDEFINITIONREFERENCE(int iDA2TYPEDEFINITIONREFERENCE) {
		IDA2TYPEDEFINITIONREFERENCE = iDA2TYPEDEFINITIONREFERENCE;
	}
	public int getIDA3CONTAINERREFERENCE() {
		return IDA3CONTAINERREFERENCE;
	}
	public void setIDA3CONTAINERREFERENCE(int iDA3CONTAINERREFERENCE) {
		IDA3CONTAINERREFERENCE = iDA3CONTAINERREFERENCE;
	}
	public int getIDA3B8() {
		return IDA3B8;
	}
	public void setIDA3B8(int iDA3B8) {
		IDA3B8 = iDA3B8;
	}
	public int getIDA3A7() {
		return IDA3A7;
	}
	public void setIDA3A7(int iDA3A7) {
		IDA3A7 = iDA3A7;
	}
	public int getIDA3DOMAINREF() {
		return IDA3DOMAINREF;
	}
	public void setIDA3DOMAINREF(int iDA3DOMAINREF) {
		IDA3DOMAINREF = iDA3DOMAINREF;
	}
	public int getIDA3A2FOLDERINGINFO() {
		return IDA3A2FOLDERINGINFO;
	}
	public void setIDA3A2FOLDERINGINFO(int iDA3A2FOLDERINGINFO) {
		IDA3A2FOLDERINGINFO = iDA3A2FOLDERINGINFO;
	}
	public int getIDA3B2FOLDERINGINFO() {
		return IDA3B2FOLDERINGINFO;
	}
	public void setIDA3B2FOLDERINGINFO(int iDA3B2FOLDERINGINFO) {
		IDA3B2FOLDERINGINFO = iDA3B2FOLDERINGINFO;
	}
	public int getIDA3C8() {
		return IDA3C8;
	}
	public void setIDA3C8(int iDA3C8) {
		IDA3C8 = iDA3C8;
	}
	public int getIDA3A2OWNERSHIP() {
		return IDA3A2OWNERSHIP;
	}
	public void setIDA3A2OWNERSHIP(int iDA3A2OWNERSHIP) {
		IDA3A2OWNERSHIP = iDA3A2OWNERSHIP;
	}
	public int getIDA3A2STATE() {
		return IDA3A2STATE;
	}
	public void setIDA3A2STATE(int iDA3A2STATE) {
		IDA3A2STATE = iDA3A2STATE;
	}
	public int getBRANCHIDA2TYPEDEFINITIONREFE() {
		return BRANCHIDA2TYPEDEFINITIONREFE;
	}
	public void setBRANCHIDA2TYPEDEFINITIONREFE(int bRANCHIDA2TYPEDEFINITIONREFE) {
		BRANCHIDA2TYPEDEFINITIONREFE = bRANCHIDA2TYPEDEFINITIONREFE;
	}
	public int getIDA3TEAMID() {
		return IDA3TEAMID;
	}
	public void setIDA3TEAMID(int iDA3TEAMID) {
		IDA3TEAMID = iDA3TEAMID;
	}
	public int getIDA3TEAMTEMPLATEID() {
		return IDA3TEAMTEMPLATEID;
	}
	public void setIDA3TEAMTEMPLATEID(int iDA3TEAMTEMPLATEID) {
		IDA3TEAMTEMPLATEID = iDA3TEAMTEMPLATEID;
	}
	public int getMARKFORDELETEA2() {
		return MARKFORDELETEA2;
	}
	public void setMARKFORDELETEA2(int mARKFORDELETEA2) {
		MARKFORDELETEA2 = mARKFORDELETEA2;
	}
	public int getUPDATECOUNTA2() {
		return UPDATECOUNTA2;
	}
	public void setUPDATECOUNTA2(int uPDATECOUNTA2) {
		UPDATECOUNTA2 = uPDATECOUNTA2;
	}
	public String getPTC_STR_1TYPEINFOLCSCOLOR() {
		return PTC_STR_1TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_1TYPEINFOLCSCOLOR(String pTC_STR_1TYPEINFOLCSCOLOR) {
		PTC_STR_1TYPEINFOLCSCOLOR = pTC_STR_1TYPEINFOLCSCOLOR;
	}
	public String getCOLORHEXIDECIMALVALUE() {
		return COLORHEXIDECIMALVALUE;
	}
	public void setCOLORHEXIDECIMALVALUE(String cOLORHEXIDECIMALVALUE) {
		COLORHEXIDECIMALVALUE = cOLORHEXIDECIMALVALUE;
	}
	public String getCOLORNAME() {
		return COLORNAME;
	}
	public void setCOLORNAME(String cOLORNAME) {
		COLORNAME = cOLORNAME;
	}
	public String getFLEXTYPEIDPATH() {
		return FLEXTYPEIDPATH;
	}
	public void setFLEXTYPEIDPATH(String fLEXTYPEIDPATH) {
		FLEXTYPEIDPATH = fLEXTYPEIDPATH;
	}
	public String getSECURITYLABELS() {
		return SECURITYLABELS;
	}
	public void setSECURITYLABELS(String sECURITYLABELS) {
		SECURITYLABELS = sECURITYLABELS;
	}
	public String getTHUMBNAIL() {
		return THUMBNAIL;
	}
	public void setTHUMBNAIL(String tHUMBNAIL) {
		THUMBNAIL = tHUMBNAIL;
	}
	public Date getCREATESTAMPA2() {
		return CREATESTAMPA2;
	}
	public void setCREATESTAMPA2(Date cREATESTAMPA2) {
		CREATESTAMPA2 = cREATESTAMPA2;
	}
	public Date getUPDATESTAMPA2() {
		return UPDATESTAMPA2;
	}
	public void setUPDATESTAMPA2(Date uPDATESTAMPA2) {
		UPDATESTAMPA2 = uPDATESTAMPA2;
	}
	
	@Override
	public String toString() {
		return "LCSColor [IDA2A2=" + IDA2A2 + ", IDA2TYPEDEFINITIONREFERENCE=" + IDA2TYPEDEFINITIONREFERENCE
				+ ", IDA3CONTAINERREFERENCE=" + IDA3CONTAINERREFERENCE + ", IDA3B8=" + IDA3B8 + ", IDA3A7=" + IDA3A7
				+ ", IDA3DOMAINREF=" + IDA3DOMAINREF + ", IDA3A2FOLDERINGINFO=" + IDA3A2FOLDERINGINFO
				+ ", IDA3B2FOLDERINGINFO=" + IDA3B2FOLDERINGINFO + ", IDA3C8=" + IDA3C8 + ", IDA3A2OWNERSHIP="
				+ IDA3A2OWNERSHIP + ", IDA3A2STATE=" + IDA3A2STATE + ", BRANCHIDA2TYPEDEFINITIONREFE="
				+ BRANCHIDA2TYPEDEFINITIONREFE + ", IDA3TEAMID=" + IDA3TEAMID + ", IDA3TEAMTEMPLATEID="
				+ IDA3TEAMTEMPLATEID + ", MARKFORDELETEA2=" + MARKFORDELETEA2 + ", UPDATECOUNTA2=" + UPDATECOUNTA2
				+ ", PTC_STR_1TYPEINFOLCSCOLOR=" + PTC_STR_1TYPEINFOLCSCOLOR + ", COLORHEXIDECIMALVALUE="
				+ COLORHEXIDECIMALVALUE + ", COLORNAME=" + COLORNAME + ", FLEXTYPEIDPATH=" + FLEXTYPEIDPATH
				+ ", SECURITYLABELS=" + SECURITYLABELS + ", THUMBNAIL=" + THUMBNAIL + ", CREATESTAMPA2=" + CREATESTAMPA2
				+ ", UPDATESTAMPA2=" + UPDATESTAMPA2 + "]";
	}
	
	
}
