package com.qiwkreport.qiwk.etl.flex.domain;

import java.util.Date;

/**
 * @author abhilash
 *
 */
public class LCSColor {

	private int IDA2A2;
	private int IDA2TYPEDEFINITIONREFERENCE;
	private int IDA3CONTAINERREFERENCE;
	private int IDA3B8;
	private int IDA3A7;
	private int IDA3DOMAINREF;
	private int IDA3A2FOLDERINGINFO;
	private int IDA3B2FOLDERINGINFO;
	private int IDA3C8;
	private int IDA3A2OWNERSHIP;
	private int IDA3A2STATE;
	private int BRANCHIDA2TYPEDEFINITIONREFE;
	private int IDA3TEAMID;
	private int IDA3TEAMTEMPLATEID;
	private int MARKFORDELETEA2;
	private int UPDATECOUNTA2;
	private String COLORHEXIDECIMALVALUE;
	private String COLORNAME;
	private String FLEXTYPEIDPATH;
	private String SECURITYLABELS;
	private String THUMBNAIL;
	private Date CREATESTAMPA2;
	private Date UPDATESTAMPA2;
	
	private String PTC_STR_1TYPEINFOLCSCOLOR;
	private String PTC_STR_3TYPEINFOLCSCOLOR;
	private String PTC_STR_4TYPEINFOLCSCOLOR;
	private String PTC_STR_5TYPEINFOLCSCOLOR;
	private String PTC_STR_6TYPEINFOLCSCOLOR;
	private boolean PTC_BLN_1TYPEINFOLCSCOLOR;
	private boolean PTC_BLN_2TYPEINFOLCSCOLOR;
	private boolean PTC_BLN_3TYPEINFOLCSCOLOR;
	private boolean PTC_BLN_4TYPEINFOLCSCOLOR;
	private boolean PTC_BLN_5TYPEINFOLCSCOLOR;
	private Double PTC_DBL_1TYPEINFOLCSCOLOR;
	private Double PTC_DBL_2TYPEINFOLCSCOLOR;
	private Double PTC_DBL_3TYPEINFOLCSCOLOR;
	private Double PTC_DBL_4TYPEINFOLCSCOLOR;
	private Double PTC_DBL_5TYPEINFOLCSCOLOR;
	private long PTC_LNG_1TYPEINFOLCSCOLOR;
	private long PTC_LNG_2TYPEINFOLCSCOLOR;
	private long PTC_LNG_3TYPEINFOLCSCOLOR;
	private long PTC_LNG_4TYPEINFOLCSCOLOR;
	private long PTC_LNG_5TYPEINFOLCSCOLOR;
	private Date PTC_TMS_1TYPEINFOLCSCOLOR;
	private Date PTC_TMS_2TYPEINFOLCSCOLOR;
	private Date PTC_TMS_3TYPEINFOLCSCOLOR;
	private Date PTC_TMS_4TYPEINFOLCSCOLOR;
	private Date PTC_TMS_5TYPEINFOLCSCOLOR;
	
	public String getPTC_STR_3TYPEINFOLCSCOLOR() {
		return PTC_STR_3TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_3TYPEINFOLCSCOLOR(String pTC_STR_3TYPEINFOLCSCOLOR) {
		PTC_STR_3TYPEINFOLCSCOLOR = pTC_STR_3TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_4TYPEINFOLCSCOLOR() {
		return PTC_STR_4TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_4TYPEINFOLCSCOLOR(String pTC_STR_4TYPEINFOLCSCOLOR) {
		PTC_STR_4TYPEINFOLCSCOLOR = pTC_STR_4TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_5TYPEINFOLCSCOLOR() {
		return PTC_STR_5TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_5TYPEINFOLCSCOLOR(String pTC_STR_5TYPEINFOLCSCOLOR) {
		PTC_STR_5TYPEINFOLCSCOLOR = pTC_STR_5TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_6TYPEINFOLCSCOLOR() {
		return PTC_STR_6TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_6TYPEINFOLCSCOLOR(String pTC_STR_6TYPEINFOLCSCOLOR) {
		PTC_STR_6TYPEINFOLCSCOLOR = pTC_STR_6TYPEINFOLCSCOLOR;
	}
	public boolean isPTC_BLN_1TYPEINFOLCSCOLOR() {
		return PTC_BLN_1TYPEINFOLCSCOLOR;
	}
	public void setPTC_BLN_1TYPEINFOLCSCOLOR(boolean pTC_BLN_1TYPEINFOLCSCOLOR) {
		PTC_BLN_1TYPEINFOLCSCOLOR = pTC_BLN_1TYPEINFOLCSCOLOR;
	}
	public boolean isPTC_BLN_2TYPEINFOLCSCOLOR() {
		return PTC_BLN_2TYPEINFOLCSCOLOR;
	}
	public void setPTC_BLN_2TYPEINFOLCSCOLOR(boolean pTC_BLN_2TYPEINFOLCSCOLOR) {
		PTC_BLN_2TYPEINFOLCSCOLOR = pTC_BLN_2TYPEINFOLCSCOLOR;
	}
	public boolean isPTC_BLN_3TYPEINFOLCSCOLOR() {
		return PTC_BLN_3TYPEINFOLCSCOLOR;
	}
	public void setPTC_BLN_3TYPEINFOLCSCOLOR(boolean pTC_BLN_3TYPEINFOLCSCOLOR) {
		PTC_BLN_3TYPEINFOLCSCOLOR = pTC_BLN_3TYPEINFOLCSCOLOR;
	}
	public boolean isPTC_BLN_4TYPEINFOLCSCOLOR() {
		return PTC_BLN_4TYPEINFOLCSCOLOR;
	}
	public void setPTC_BLN_4TYPEINFOLCSCOLOR(boolean pTC_BLN_4TYPEINFOLCSCOLOR) {
		PTC_BLN_4TYPEINFOLCSCOLOR = pTC_BLN_4TYPEINFOLCSCOLOR;
	}
	public boolean isPTC_BLN_5TYPEINFOLCSCOLOR() {
		return PTC_BLN_5TYPEINFOLCSCOLOR;
	}
	public void setPTC_BLN_5TYPEINFOLCSCOLOR(boolean pTC_BLN_5TYPEINFOLCSCOLOR) {
		PTC_BLN_5TYPEINFOLCSCOLOR = pTC_BLN_5TYPEINFOLCSCOLOR;
	}
	public Double getPTC_DBL_1TYPEINFOLCSCOLOR() {
		return PTC_DBL_1TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_1TYPEINFOLCSCOLOR(Double pTC_DBL_1TYPEINFOLCSCOLOR) {
		PTC_DBL_1TYPEINFOLCSCOLOR = pTC_DBL_1TYPEINFOLCSCOLOR;
	}
	public Double getPTC_DBL_2TYPEINFOLCSCOLOR() {
		return PTC_DBL_2TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_2TYPEINFOLCSCOLOR(Double pTC_DBL_2TYPEINFOLCSCOLOR) {
		PTC_DBL_2TYPEINFOLCSCOLOR = pTC_DBL_2TYPEINFOLCSCOLOR;
	}
	public Double getPTC_DBL_3TYPEINFOLCSCOLOR() {
		return PTC_DBL_3TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_3TYPEINFOLCSCOLOR(Double pTC_DBL_3TYPEINFOLCSCOLOR) {
		PTC_DBL_3TYPEINFOLCSCOLOR = pTC_DBL_3TYPEINFOLCSCOLOR;
	}
	public Double getPTC_DBL_4TYPEINFOLCSCOLOR() {
		return PTC_DBL_4TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_4TYPEINFOLCSCOLOR(Double pTC_DBL_4TYPEINFOLCSCOLOR) {
		PTC_DBL_4TYPEINFOLCSCOLOR = pTC_DBL_4TYPEINFOLCSCOLOR;
	}
	public Double getPTC_DBL_5TYPEINFOLCSCOLOR() {
		return PTC_DBL_5TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_5TYPEINFOLCSCOLOR(Double pTC_DBL_5TYPEINFOLCSCOLOR) {
		PTC_DBL_5TYPEINFOLCSCOLOR = pTC_DBL_5TYPEINFOLCSCOLOR;
	}
	public long getPTC_LNG_1TYPEINFOLCSCOLOR() {
		return PTC_LNG_1TYPEINFOLCSCOLOR;
	}
	public void setPTC_LNG_1TYPEINFOLCSCOLOR(long pTC_LNG_1TYPEINFOLCSCOLOR) {
		PTC_LNG_1TYPEINFOLCSCOLOR = pTC_LNG_1TYPEINFOLCSCOLOR;
	}
	public long getPTC_LNG_2TYPEINFOLCSCOLOR() {
		return PTC_LNG_2TYPEINFOLCSCOLOR;
	}
	public void setPTC_LNG_2TYPEINFOLCSCOLOR(long pTC_LNG_2TYPEINFOLCSCOLOR) {
		PTC_LNG_2TYPEINFOLCSCOLOR = pTC_LNG_2TYPEINFOLCSCOLOR;
	}
	public long getPTC_LNG_3TYPEINFOLCSCOLOR() {
		return PTC_LNG_3TYPEINFOLCSCOLOR;
	}
	public void setPTC_LNG_3TYPEINFOLCSCOLOR(long pTC_LNG_3TYPEINFOLCSCOLOR) {
		PTC_LNG_3TYPEINFOLCSCOLOR = pTC_LNG_3TYPEINFOLCSCOLOR;
	}
	public long getPTC_LNG_4TYPEINFOLCSCOLOR() {
		return PTC_LNG_4TYPEINFOLCSCOLOR;
	}
	public void setPTC_LNG_4TYPEINFOLCSCOLOR(long pTC_LNG_4TYPEINFOLCSCOLOR) {
		PTC_LNG_4TYPEINFOLCSCOLOR = pTC_LNG_4TYPEINFOLCSCOLOR;
	}
	public long getPTC_LNG_5TYPEINFOLCSCOLOR() {
		return PTC_LNG_5TYPEINFOLCSCOLOR;
	}
	public void setPTC_LNG_5TYPEINFOLCSCOLOR(long pTC_LNG_5TYPEINFOLCSCOLOR) {
		PTC_LNG_5TYPEINFOLCSCOLOR = pTC_LNG_5TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_1TYPEINFOLCSCOLOR() {
		return PTC_TMS_1TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_1TYPEINFOLCSCOLOR(Date pTC_TMS_1TYPEINFOLCSCOLOR) {
		PTC_TMS_1TYPEINFOLCSCOLOR = pTC_TMS_1TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_2TYPEINFOLCSCOLOR() {
		return PTC_TMS_2TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_2TYPEINFOLCSCOLOR(Date pTC_TMS_2TYPEINFOLCSCOLOR) {
		PTC_TMS_2TYPEINFOLCSCOLOR = pTC_TMS_2TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_3TYPEINFOLCSCOLOR() {
		return PTC_TMS_3TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_3TYPEINFOLCSCOLOR(Date pTC_TMS_3TYPEINFOLCSCOLOR) {
		PTC_TMS_3TYPEINFOLCSCOLOR = pTC_TMS_3TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_4TYPEINFOLCSCOLOR() {
		return PTC_TMS_4TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_4TYPEINFOLCSCOLOR(Date pTC_TMS_4TYPEINFOLCSCOLOR) {
		PTC_TMS_4TYPEINFOLCSCOLOR = pTC_TMS_4TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_5TYPEINFOLCSCOLOR() {
		return PTC_TMS_5TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_5TYPEINFOLCSCOLOR(Date pTC_TMS_5TYPEINFOLCSCOLOR) {
		PTC_TMS_5TYPEINFOLCSCOLOR = pTC_TMS_5TYPEINFOLCSCOLOR;
	}
	public int getIDA2A2() {
		return IDA2A2;
	}
	public void setIDA2A2(int iDA2A2) {
		IDA2A2 = iDA2A2;
	}
	public int getIDA2TYPEDEFINITIONREFERENCE() {
		return IDA2TYPEDEFINITIONREFERENCE;
	}
	public void setIDA2TYPEDEFINITIONREFERENCE(int iDA2TYPEDEFINITIONREFERENCE) {
		IDA2TYPEDEFINITIONREFERENCE = iDA2TYPEDEFINITIONREFERENCE;
	}
	public int getIDA3CONTAINERREFERENCE() {
		return IDA3CONTAINERREFERENCE;
	}
	public void setIDA3CONTAINERREFERENCE(int iDA3CONTAINERREFERENCE) {
		IDA3CONTAINERREFERENCE = iDA3CONTAINERREFERENCE;
	}
	public int getIDA3B8() {
		return IDA3B8;
	}
	public void setIDA3B8(int iDA3B8) {
		IDA3B8 = iDA3B8;
	}
	public int getIDA3A7() {
		return IDA3A7;
	}
	public void setIDA3A7(int iDA3A7) {
		IDA3A7 = iDA3A7;
	}
	public int getIDA3DOMAINREF() {
		return IDA3DOMAINREF;
	}
	public void setIDA3DOMAINREF(int iDA3DOMAINREF) {
		IDA3DOMAINREF = iDA3DOMAINREF;
	}
	public int getIDA3A2FOLDERINGINFO() {
		return IDA3A2FOLDERINGINFO;
	}
	public void setIDA3A2FOLDERINGINFO(int iDA3A2FOLDERINGINFO) {
		IDA3A2FOLDERINGINFO = iDA3A2FOLDERINGINFO;
	}
	public int getIDA3B2FOLDERINGINFO() {
		return IDA3B2FOLDERINGINFO;
	}
	public void setIDA3B2FOLDERINGINFO(int iDA3B2FOLDERINGINFO) {
		IDA3B2FOLDERINGINFO = iDA3B2FOLDERINGINFO;
	}
	public int getIDA3C8() {
		return IDA3C8;
	}
	public void setIDA3C8(int iDA3C8) {
		IDA3C8 = iDA3C8;
	}
	public int getIDA3A2OWNERSHIP() {
		return IDA3A2OWNERSHIP;
	}
	public void setIDA3A2OWNERSHIP(int iDA3A2OWNERSHIP) {
		IDA3A2OWNERSHIP = iDA3A2OWNERSHIP;
	}
	public int getIDA3A2STATE() {
		return IDA3A2STATE;
	}
	public void setIDA3A2STATE(int iDA3A2STATE) {
		IDA3A2STATE = iDA3A2STATE;
	}
	public int getBRANCHIDA2TYPEDEFINITIONREFE() {
		return BRANCHIDA2TYPEDEFINITIONREFE;
	}
	public void setBRANCHIDA2TYPEDEFINITIONREFE(int bRANCHIDA2TYPEDEFINITIONREFE) {
		BRANCHIDA2TYPEDEFINITIONREFE = bRANCHIDA2TYPEDEFINITIONREFE;
	}
	public int getIDA3TEAMID() {
		return IDA3TEAMID;
	}
	public void setIDA3TEAMID(int iDA3TEAMID) {
		IDA3TEAMID = iDA3TEAMID;
	}
	public int getIDA3TEAMTEMPLATEID() {
		return IDA3TEAMTEMPLATEID;
	}
	public void setIDA3TEAMTEMPLATEID(int iDA3TEAMTEMPLATEID) {
		IDA3TEAMTEMPLATEID = iDA3TEAMTEMPLATEID;
	}
	public int getMARKFORDELETEA2() {
		return MARKFORDELETEA2;
	}
	public void setMARKFORDELETEA2(int mARKFORDELETEA2) {
		MARKFORDELETEA2 = mARKFORDELETEA2;
	}
	public int getUPDATECOUNTA2() {
		return UPDATECOUNTA2;
	}
	public void setUPDATECOUNTA2(int uPDATECOUNTA2) {
		UPDATECOUNTA2 = uPDATECOUNTA2;
	}
	public String getPTC_STR_1TYPEINFOLCSCOLOR() {
		return PTC_STR_1TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_1TYPEINFOLCSCOLOR(String pTC_STR_1TYPEINFOLCSCOLOR) {
		PTC_STR_1TYPEINFOLCSCOLOR = pTC_STR_1TYPEINFOLCSCOLOR;
	}
	public String getCOLORHEXIDECIMALVALUE() {
		return COLORHEXIDECIMALVALUE;
	}
	public void setCOLORHEXIDECIMALVALUE(String cOLORHEXIDECIMALVALUE) {
		COLORHEXIDECIMALVALUE = cOLORHEXIDECIMALVALUE;
	}
	public String getCOLORNAME() {
		return COLORNAME;
	}
	public void setCOLORNAME(String cOLORNAME) {
		COLORNAME = cOLORNAME;
	}
	public String getFLEXTYPEIDPATH() {
		return FLEXTYPEIDPATH;
	}
	public void setFLEXTYPEIDPATH(String fLEXTYPEIDPATH) {
		FLEXTYPEIDPATH = fLEXTYPEIDPATH;
	}
	public String getSECURITYLABELS() {
		return SECURITYLABELS;
	}
	public void setSECURITYLABELS(String sECURITYLABELS) {
		SECURITYLABELS = sECURITYLABELS;
	}
	public String getTHUMBNAIL() {
		return THUMBNAIL;
	}
	public void setTHUMBNAIL(String tHUMBNAIL) {
		THUMBNAIL = tHUMBNAIL;
	}
	public Date getCREATESTAMPA2() {
		return CREATESTAMPA2;
	}
	public void setCREATESTAMPA2(Date cREATESTAMPA2) {
		CREATESTAMPA2 = cREATESTAMPA2;
	}
	public Date getUPDATESTAMPA2() {
		return UPDATESTAMPA2;
	}
	public void setUPDATESTAMPA2(Date uPDATESTAMPA2) {
		UPDATESTAMPA2 = uPDATESTAMPA2;
	}
	
	@Override
	public String toString() {
		return "LCSColor [IDA2A2=" + IDA2A2 + ", IDA2TYPEDEFINITIONREFERENCE=" + IDA2TYPEDEFINITIONREFERENCE
				+ ", IDA3CONTAINERREFERENCE=" + IDA3CONTAINERREFERENCE + ", IDA3B8=" + IDA3B8 + ", IDA3A7=" + IDA3A7
				+ ", IDA3DOMAINREF=" + IDA3DOMAINREF + ", IDA3A2FOLDERINGINFO=" + IDA3A2FOLDERINGINFO
				+ ", IDA3B2FOLDERINGINFO=" + IDA3B2FOLDERINGINFO + ", IDA3C8=" + IDA3C8 + ", IDA3A2OWNERSHIP="
				+ IDA3A2OWNERSHIP + ", IDA3A2STATE=" + IDA3A2STATE + ", BRANCHIDA2TYPEDEFINITIONREFE="
				+ BRANCHIDA2TYPEDEFINITIONREFE + ", IDA3TEAMID=" + IDA3TEAMID + ", IDA3TEAMTEMPLATEID="
				+ IDA3TEAMTEMPLATEID + ", MARKFORDELETEA2=" + MARKFORDELETEA2 + ", UPDATECOUNTA2=" + UPDATECOUNTA2
				+ ", COLORHEXIDECIMALVALUE=" + COLORHEXIDECIMALVALUE + ", COLORNAME=" + COLORNAME + ", FLEXTYPEIDPATH="
				+ FLEXTYPEIDPATH + ", SECURITYLABELS=" + SECURITYLABELS + ", THUMBNAIL=" + THUMBNAIL
				+ ", CREATESTAMPA2=" + CREATESTAMPA2 + ", UPDATESTAMPA2=" + UPDATESTAMPA2
				+ ", PTC_STR_1TYPEINFOLCSCOLOR=" + PTC_STR_1TYPEINFOLCSCOLOR + ", PTC_STR_3TYPEINFOLCSCOLOR="
				+ PTC_STR_3TYPEINFOLCSCOLOR + ", PTC_STR_4TYPEINFOLCSCOLOR=" + PTC_STR_4TYPEINFOLCSCOLOR
				+ ", PTC_STR_5TYPEINFOLCSCOLOR=" + PTC_STR_5TYPEINFOLCSCOLOR + ", PTC_STR_6TYPEINFOLCSCOLOR="
				+ PTC_STR_6TYPEINFOLCSCOLOR + ", PTC_BLN_1TYPEINFOLCSCOLOR=" + PTC_BLN_1TYPEINFOLCSCOLOR
				+ ", PTC_BLN_2TYPEINFOLCSCOLOR=" + PTC_BLN_2TYPEINFOLCSCOLOR + ", PTC_BLN_3TYPEINFOLCSCOLOR="
				+ PTC_BLN_3TYPEINFOLCSCOLOR + ", PTC_BLN_4TYPEINFOLCSCOLOR=" + PTC_BLN_4TYPEINFOLCSCOLOR
				+ ", PTC_BLN_5TYPEINFOLCSCOLOR=" + PTC_BLN_5TYPEINFOLCSCOLOR + ", PTC_DBL_1TYPEINFOLCSCOLOR="
				+ PTC_DBL_1TYPEINFOLCSCOLOR + ", PTC_DBL_2TYPEINFOLCSCOLOR=" + PTC_DBL_2TYPEINFOLCSCOLOR
				+ ", PTC_DBL_3TYPEINFOLCSCOLOR=" + PTC_DBL_3TYPEINFOLCSCOLOR + ", PTC_DBL_4TYPEINFOLCSCOLOR="
				+ PTC_DBL_4TYPEINFOLCSCOLOR + ", PTC_DBL_5TYPEINFOLCSCOLOR=" + PTC_DBL_5TYPEINFOLCSCOLOR
				+ ", PTC_LNG_1TYPEINFOLCSCOLOR=" + PTC_LNG_1TYPEINFOLCSCOLOR + ", PTC_LNG_2TYPEINFOLCSCOLOR="
				+ PTC_LNG_2TYPEINFOLCSCOLOR + ", PTC_LNG_3TYPEINFOLCSCOLOR=" + PTC_LNG_3TYPEINFOLCSCOLOR
				+ ", PTC_LNG_4TYPEINFOLCSCOLOR=" + PTC_LNG_4TYPEINFOLCSCOLOR + ", PTC_LNG_5TYPEINFOLCSCOLOR="
				+ PTC_LNG_5TYPEINFOLCSCOLOR + ", PTC_TMS_1TYPEINFOLCSCOLOR=" + PTC_TMS_1TYPEINFOLCSCOLOR
				+ ", PTC_TMS_2TYPEINFOLCSCOLOR=" + PTC_TMS_2TYPEINFOLCSCOLOR + ", PTC_TMS_3TYPEINFOLCSCOLOR="
				+ PTC_TMS_3TYPEINFOLCSCOLOR + ", PTC_TMS_4TYPEINFOLCSCOLOR=" + PTC_TMS_4TYPEINFOLCSCOLOR
				+ ", PTC_TMS_5TYPEINFOLCSCOLOR=" + PTC_TMS_5TYPEINFOLCSCOLOR + "]";
	}
	
	
}
