package com.qiwkreport.qiwk.etl.flex.domain;

import java.util.Arrays;
import java.util.Date;

/**
 * @author abhilash
 *
 */
public class LCSMaterial {

	private int IDA2A2;
	private boolean ADMINISTRATIVELOCKISNULL;
	private String TYPEADMINISTRATIVELOCK;
	private Byte[] BLOB$ENTRYSETADHOCACL;
	private boolean CHECKOUTINFOISNULL;
	private String STATECHECKOUTINFO;
	private String CLASSNAMEKEYCONTAINERREFEREN;
	private int IDA3CONTAINERREFERENCE;
	private String CLASSNAMEKEYB10;
	private int IDA3B10;
	private String CLASSNAMEKEYDOMAINREF;
	private int IDA3DOMAINREF;
	private String ENTRYSETADHOCACL;
	private String EVENTSET;
	private String FLEXTYPEIDPATH;
	private String CLASSNAMEKEYA2FOLDERINGINFO;
	private int IDA3A2FOLDERINGINFO;
	private String CLASSNAMEKEYB2FOLDERINGINFO;
	private int IDA3B2FOLDERINGINFO;
	private boolean HASHANGINGCHANGE;
	private boolean HASPENDINGCHANGE;
	private boolean HASRESULTINGCHANGE;
	private boolean HASVARIANCE;
	private String INDEXERSINDEXERSET;
	private boolean INHERITEDDOMAIN;
	private int BRANCHIDITERATIONINFO;
	private String CLASSNAMEKEYD2ITERATIONINFO;
	private int IDA3D2ITERATIONINFO;
	private String CLASSNAMEKEYE2ITERATIONINFO;
	private int IDA3E2ITERATIONINFO;
	private String ITERATIONIDA2ITERATIONINFO;
	private boolean LATESTITERATIONINFO;
	private String CLASSNAMEKEYB2ITERATIONINFO;
	private int IDA3B2ITERATIONINFO;
	private String NOTEITERATIONINFO;
	private String CLASSNAMEKEYC2ITERATIONINFO;
	private int IDA3C2ITERATIONINFO;
	private String STATEITERATIONINFO;
	private Date DATELOCK;
	private String CLASSNAMEKEYA2LOCK;
	private int IDA3A2LOCK;
	private String NOTELOCK;
	private String CLASSNAMEKEYMASTERREFERENCE;
	private int IDA3MASTERREFERENCE;
	private String CLASSNAMEKEYA2OWNERSHIP;
	private int IDA3A2OWNERSHIP;
	private String PRIMARYIMAGEURL;
	private String SECURITYLABELS;
	private boolean ATGATESTATE;
	private String CLASSNAMEKEYA2STATE;
	private int IDA3A2STATE;
	private String STATESTATE;
	private boolean TEAMIDISNULL;
	private String CLASSNAMEKEYTEAMID;
	private int IDA3TEAMID;
	private boolean TEAMTEMPLATEIDISNULL;
	private String CLASSNAMEKEYTEAMTEMPLATEID;
	private int IDA3TEAMTEMPLATEID;
	private Date CREATESTAMPA2;
	private int MARKFORDELETEA2;
	private Date MODIFYSTAMPA2;
	private String CLASSNAMEA2A2;
	private int UPDATECOUNTA2;         
	private Date UPDATESTAMPA2;           
	private int BRANCHIDA2TYPEDEFINITIONREFE;         
	private int IDA2TYPEDEFINITIONREFERENCE;         
	private String TYPEDISPLAY;  
	private String VERSIONIDA2VERSIONINFO;  
	private int VERSIONLEVELA2VERSIONINFO;         
	private String VERSIONSORTIDA2VERSIONINFO;  
	private String PTC_STR_1TYPEINFOLCSMATERIAL; 
	private String PTC_STR_2TYPEINFOLCSMATERIAL; 
	private String PTC_STR_3TYPEINFOLCSMATERIAL; 
	private String PTC_STR_4TYPEINFOLCSMATERIAL; 
	private boolean PTC_BLN_1TYPEINFOLCSMATERIAL;      
	private boolean PTC_BLN_2TYPEINFOLCSMATERIAL;      
	private Double PTC_DBL_1TYPEINFOLCSMATERIAL;         
	private Double PTC_DBL_2TYPEINFOLCSMATERIAL;         
	private long PTC_LNG_1TYPEINFOLCSMATERIAL;         
	private long PTC_LNG_2TYPEINFOLCSMATERIAL;         
	private String PTC_STR_5TYPEINFOLCSMATERIAL; 
	private String PTC_STR_6TYPEINFOLCSMATERIAL; 
	private Date PTC_TMS_1TYPEINFOLCSMATERIAL;           
	private Date PTC_TMS_2TYPEINFOLCSMATERIAL;
	
	public LCSMaterial() {
		super();
	}

	public LCSMaterial(int iDA2A2, boolean aDMINISTRATIVELOCKISNULL, String tYPEADMINISTRATIVELOCK,
			Byte[] bLOB$ENTRYSETADHOCACL, boolean cHECKOUTINFOISNULL, String sTATECHECKOUTINFO,
			String cLASSNAMEKEYCONTAINERREFEREN, int iDA3CONTAINERREFERENCE, String cLASSNAMEKEYB10, int iDA3B10,
			String cLASSNAMEKEYDOMAINREF, int iDA3DOMAINREF, String eNTRYSETADHOCACL, String eVENTSET,
			String fLEXTYPEIDPATH, String cLASSNAMEKEYA2FOLDERINGINFO, int iDA3A2FOLDERINGINFO,
			String cLASSNAMEKEYB2FOLDERINGINFO, int iDA3B2FOLDERINGINFO, boolean hASHANGINGCHANGE,
			boolean hASPENDINGCHANGE, boolean hASRESULTINGCHANGE, boolean hASVARIANCE, String iNDEXERSINDEXERSET,
			boolean iNHERITEDDOMAIN, int bRANCHIDITERATIONINFO, String cLASSNAMEKEYD2ITERATIONINFO,
			int iDA3D2ITERATIONINFO, String cLASSNAMEKEYE2ITERATIONINFO, int iDA3E2ITERATIONINFO,
			String iTERATIONIDA2ITERATIONINFO, boolean lATESTITERATIONINFO, String cLASSNAMEKEYB2ITERATIONINFO,
			int iDA3B2ITERATIONINFO, String nOTEITERATIONINFO, String cLASSNAMEKEYC2ITERATIONINFO,
			int iDA3C2ITERATIONINFO, String sTATEITERATIONINFO, Date dATELOCK, String cLASSNAMEKEYA2LOCK,
			int iDA3A2LOCK, String nOTELOCK, String cLASSNAMEKEYMASTERREFERENCE, int iDA3MASTERREFERENCE,
			String cLASSNAMEKEYA2OWNERSHIP, int iDA3A2OWNERSHIP, String pRIMARYIMAGEURL, String sECURITYLABELS,
			boolean aTGATESTATE, String cLASSNAMEKEYA2STATE, int iDA3A2STATE, String sTATESTATE, boolean tEAMIDISNULL,
			String cLASSNAMEKEYTEAMID, int iDA3TEAMID, boolean tEAMTEMPLATEIDISNULL, String cLASSNAMEKEYTEAMTEMPLATEID,
			int iDA3TEAMTEMPLATEID, Date cREATESTAMPA2, int mARKFORDELETEA2, Date mODIFYSTAMPA2, String cLASSNAMEA2A2,
			int uPDATECOUNTA2, Date uPDATESTAMPA2, int bRANCHIDA2TYPEDEFINITIONREFE, int iDA2TYPEDEFINITIONREFERENCE,
			String tYPEDISPLAY, String vERSIONIDA2VERSIONINFO, int vERSIONLEVELA2VERSIONINFO,
			String vERSIONSORTIDA2VERSIONINFO, String pTC_STR_1TYPEINFOLCSMATERIAL, String pTC_STR_2TYPEINFOLCSMATERIAL,
			String pTC_STR_3TYPEINFOLCSMATERIAL, String pTC_STR_4TYPEINFOLCSMATERIAL,
			boolean pTC_BLN_1TYPEINFOLCSMATERIAL, boolean pTC_BLN_2TYPEINFOLCSMATERIAL,
			Double pTC_DBL_1TYPEINFOLCSMATERIAL, Double pTC_DBL_2TYPEINFOLCSMATERIAL, long pTC_LNG_1TYPEINFOLCSMATERIAL,
			long pTC_LNG_2TYPEINFOLCSMATERIAL, String pTC_STR_5TYPEINFOLCSMATERIAL, String pTC_STR_6TYPEINFOLCSMATERIAL,
			Date pTC_TMS_1TYPEINFOLCSMATERIAL, Date pTC_TMS_2TYPEINFOLCSMATERIAL) {
		super();
		IDA2A2 = iDA2A2;
		ADMINISTRATIVELOCKISNULL = aDMINISTRATIVELOCKISNULL;
		TYPEADMINISTRATIVELOCK = tYPEADMINISTRATIVELOCK;
		BLOB$ENTRYSETADHOCACL = bLOB$ENTRYSETADHOCACL;
		CHECKOUTINFOISNULL = cHECKOUTINFOISNULL;
		STATECHECKOUTINFO = sTATECHECKOUTINFO;
		CLASSNAMEKEYCONTAINERREFEREN = cLASSNAMEKEYCONTAINERREFEREN;
		IDA3CONTAINERREFERENCE = iDA3CONTAINERREFERENCE;
		CLASSNAMEKEYB10 = cLASSNAMEKEYB10;
		IDA3B10 = iDA3B10;
		CLASSNAMEKEYDOMAINREF = cLASSNAMEKEYDOMAINREF;
		IDA3DOMAINREF = iDA3DOMAINREF;
		ENTRYSETADHOCACL = eNTRYSETADHOCACL;
		EVENTSET = eVENTSET;
		FLEXTYPEIDPATH = fLEXTYPEIDPATH;
		CLASSNAMEKEYA2FOLDERINGINFO = cLASSNAMEKEYA2FOLDERINGINFO;
		IDA3A2FOLDERINGINFO = iDA3A2FOLDERINGINFO;
		CLASSNAMEKEYB2FOLDERINGINFO = cLASSNAMEKEYB2FOLDERINGINFO;
		IDA3B2FOLDERINGINFO = iDA3B2FOLDERINGINFO;
		HASHANGINGCHANGE = hASHANGINGCHANGE;
		HASPENDINGCHANGE = hASPENDINGCHANGE;
		HASRESULTINGCHANGE = hASRESULTINGCHANGE;
		HASVARIANCE = hASVARIANCE;
		INDEXERSINDEXERSET = iNDEXERSINDEXERSET;
		INHERITEDDOMAIN = iNHERITEDDOMAIN;
		BRANCHIDITERATIONINFO = bRANCHIDITERATIONINFO;
		CLASSNAMEKEYD2ITERATIONINFO = cLASSNAMEKEYD2ITERATIONINFO;
		IDA3D2ITERATIONINFO = iDA3D2ITERATIONINFO;
		CLASSNAMEKEYE2ITERATIONINFO = cLASSNAMEKEYE2ITERATIONINFO;
		IDA3E2ITERATIONINFO = iDA3E2ITERATIONINFO;
		ITERATIONIDA2ITERATIONINFO = iTERATIONIDA2ITERATIONINFO;
		LATESTITERATIONINFO = lATESTITERATIONINFO;
		CLASSNAMEKEYB2ITERATIONINFO = cLASSNAMEKEYB2ITERATIONINFO;
		IDA3B2ITERATIONINFO = iDA3B2ITERATIONINFO;
		NOTEITERATIONINFO = nOTEITERATIONINFO;
		CLASSNAMEKEYC2ITERATIONINFO = cLASSNAMEKEYC2ITERATIONINFO;
		IDA3C2ITERATIONINFO = iDA3C2ITERATIONINFO;
		STATEITERATIONINFO = sTATEITERATIONINFO;
		DATELOCK = dATELOCK;
		CLASSNAMEKEYA2LOCK = cLASSNAMEKEYA2LOCK;
		IDA3A2LOCK = iDA3A2LOCK;
		NOTELOCK = nOTELOCK;
		CLASSNAMEKEYMASTERREFERENCE = cLASSNAMEKEYMASTERREFERENCE;
		IDA3MASTERREFERENCE = iDA3MASTERREFERENCE;
		CLASSNAMEKEYA2OWNERSHIP = cLASSNAMEKEYA2OWNERSHIP;
		IDA3A2OWNERSHIP = iDA3A2OWNERSHIP;
		PRIMARYIMAGEURL = pRIMARYIMAGEURL;
		SECURITYLABELS = sECURITYLABELS;
		ATGATESTATE = aTGATESTATE;
		CLASSNAMEKEYA2STATE = cLASSNAMEKEYA2STATE;
		IDA3A2STATE = iDA3A2STATE;
		STATESTATE = sTATESTATE;
		TEAMIDISNULL = tEAMIDISNULL;
		CLASSNAMEKEYTEAMID = cLASSNAMEKEYTEAMID;
		IDA3TEAMID = iDA3TEAMID;
		TEAMTEMPLATEIDISNULL = tEAMTEMPLATEIDISNULL;
		CLASSNAMEKEYTEAMTEMPLATEID = cLASSNAMEKEYTEAMTEMPLATEID;
		IDA3TEAMTEMPLATEID = iDA3TEAMTEMPLATEID;
		CREATESTAMPA2 = cREATESTAMPA2;
		MARKFORDELETEA2 = mARKFORDELETEA2;
		MODIFYSTAMPA2 = mODIFYSTAMPA2;
		CLASSNAMEA2A2 = cLASSNAMEA2A2;
		UPDATECOUNTA2 = uPDATECOUNTA2;
		UPDATESTAMPA2 = uPDATESTAMPA2;
		BRANCHIDA2TYPEDEFINITIONREFE = bRANCHIDA2TYPEDEFINITIONREFE;
		IDA2TYPEDEFINITIONREFERENCE = iDA2TYPEDEFINITIONREFERENCE;
		TYPEDISPLAY = tYPEDISPLAY;
		VERSIONIDA2VERSIONINFO = vERSIONIDA2VERSIONINFO;
		VERSIONLEVELA2VERSIONINFO = vERSIONLEVELA2VERSIONINFO;
		VERSIONSORTIDA2VERSIONINFO = vERSIONSORTIDA2VERSIONINFO;
		PTC_STR_1TYPEINFOLCSMATERIAL = pTC_STR_1TYPEINFOLCSMATERIAL;
		PTC_STR_2TYPEINFOLCSMATERIAL = pTC_STR_2TYPEINFOLCSMATERIAL;
		PTC_STR_3TYPEINFOLCSMATERIAL = pTC_STR_3TYPEINFOLCSMATERIAL;
		PTC_STR_4TYPEINFOLCSMATERIAL = pTC_STR_4TYPEINFOLCSMATERIAL;
		PTC_BLN_1TYPEINFOLCSMATERIAL = pTC_BLN_1TYPEINFOLCSMATERIAL;
		PTC_BLN_2TYPEINFOLCSMATERIAL = pTC_BLN_2TYPEINFOLCSMATERIAL;
		PTC_DBL_1TYPEINFOLCSMATERIAL = pTC_DBL_1TYPEINFOLCSMATERIAL;
		PTC_DBL_2TYPEINFOLCSMATERIAL = pTC_DBL_2TYPEINFOLCSMATERIAL;
		PTC_LNG_1TYPEINFOLCSMATERIAL = pTC_LNG_1TYPEINFOLCSMATERIAL;
		PTC_LNG_2TYPEINFOLCSMATERIAL = pTC_LNG_2TYPEINFOLCSMATERIAL;
		PTC_STR_5TYPEINFOLCSMATERIAL = pTC_STR_5TYPEINFOLCSMATERIAL;
		PTC_STR_6TYPEINFOLCSMATERIAL = pTC_STR_6TYPEINFOLCSMATERIAL;
		PTC_TMS_1TYPEINFOLCSMATERIAL = pTC_TMS_1TYPEINFOLCSMATERIAL;
		PTC_TMS_2TYPEINFOLCSMATERIAL = pTC_TMS_2TYPEINFOLCSMATERIAL;
	}
	public int getIDA2A2() {
		return IDA2A2;
	}
	public void setIDA2A2(int iDA2A2) {
		IDA2A2 = iDA2A2;
	}
	public boolean isADMINISTRATIVELOCKISNULL() {
		return ADMINISTRATIVELOCKISNULL;
	}
	public void setADMINISTRATIVELOCKISNULL(boolean aDMINISTRATIVELOCKISNULL) {
		ADMINISTRATIVELOCKISNULL = aDMINISTRATIVELOCKISNULL;
	}
	public String getTYPEADMINISTRATIVELOCK() {
		return TYPEADMINISTRATIVELOCK;
	}
	public void setTYPEADMINISTRATIVELOCK(String tYPEADMINISTRATIVELOCK) {
		TYPEADMINISTRATIVELOCK = tYPEADMINISTRATIVELOCK;
	}
	public Byte[] getBLOB$ENTRYSETADHOCACL() {
		return BLOB$ENTRYSETADHOCACL;
	}
	public void setBLOB$ENTRYSETADHOCACL(Byte[] bLOB$ENTRYSETADHOCACL) {
		BLOB$ENTRYSETADHOCACL = bLOB$ENTRYSETADHOCACL;
	}
	public boolean isCHECKOUTINFOISNULL() {
		return CHECKOUTINFOISNULL;
	}
	public void setCHECKOUTINFOISNULL(boolean cHECKOUTINFOISNULL) {
		CHECKOUTINFOISNULL = cHECKOUTINFOISNULL;
	}
	public String getSTATECHECKOUTINFO() {
		return STATECHECKOUTINFO;
	}
	public void setSTATECHECKOUTINFO(String sTATECHECKOUTINFO) {
		STATECHECKOUTINFO = sTATECHECKOUTINFO;
	}
	public String getCLASSNAMEKEYCONTAINERREFEREN() {
		return CLASSNAMEKEYCONTAINERREFEREN;
	}
	public void setCLASSNAMEKEYCONTAINERREFEREN(String cLASSNAMEKEYCONTAINERREFEREN) {
		CLASSNAMEKEYCONTAINERREFEREN = cLASSNAMEKEYCONTAINERREFEREN;
	}
	public int getIDA3CONTAINERREFERENCE() {
		return IDA3CONTAINERREFERENCE;
	}
	public void setIDA3CONTAINERREFERENCE(int iDA3CONTAINERREFERENCE) {
		IDA3CONTAINERREFERENCE = iDA3CONTAINERREFERENCE;
	}
	public String getCLASSNAMEKEYB10() {
		return CLASSNAMEKEYB10;
	}
	public void setCLASSNAMEKEYB10(String cLASSNAMEKEYB10) {
		CLASSNAMEKEYB10 = cLASSNAMEKEYB10;
	}
	public int getIDA3B10() {
		return IDA3B10;
	}
	public void setIDA3B10(int iDA3B10) {
		IDA3B10 = iDA3B10;
	}
	public String getCLASSNAMEKEYDOMAINREF() {
		return CLASSNAMEKEYDOMAINREF;
	}
	public void setCLASSNAMEKEYDOMAINREF(String cLASSNAMEKEYDOMAINREF) {
		CLASSNAMEKEYDOMAINREF = cLASSNAMEKEYDOMAINREF;
	}
	public int getIDA3DOMAINREF() {
		return IDA3DOMAINREF;
	}
	public void setIDA3DOMAINREF(int iDA3DOMAINREF) {
		IDA3DOMAINREF = iDA3DOMAINREF;
	}
	public String getENTRYSETADHOCACL() {
		return ENTRYSETADHOCACL;
	}
	public void setENTRYSETADHOCACL(String eNTRYSETADHOCACL) {
		ENTRYSETADHOCACL = eNTRYSETADHOCACL;
	}
	public String getEVENTSET() {
		return EVENTSET;
	}
	public void setEVENTSET(String eVENTSET) {
		EVENTSET = eVENTSET;
	}
	public String getFLEXTYPEIDPATH() {
		return FLEXTYPEIDPATH;
	}
	public void setFLEXTYPEIDPATH(String fLEXTYPEIDPATH) {
		FLEXTYPEIDPATH = fLEXTYPEIDPATH;
	}
	public String getCLASSNAMEKEYA2FOLDERINGINFO() {
		return CLASSNAMEKEYA2FOLDERINGINFO;
	}
	public void setCLASSNAMEKEYA2FOLDERINGINFO(String cLASSNAMEKEYA2FOLDERINGINFO) {
		CLASSNAMEKEYA2FOLDERINGINFO = cLASSNAMEKEYA2FOLDERINGINFO;
	}
	public int getIDA3A2FOLDERINGINFO() {
		return IDA3A2FOLDERINGINFO;
	}
	public void setIDA3A2FOLDERINGINFO(int iDA3A2FOLDERINGINFO) {
		IDA3A2FOLDERINGINFO = iDA3A2FOLDERINGINFO;
	}
	public String getCLASSNAMEKEYB2FOLDERINGINFO() {
		return CLASSNAMEKEYB2FOLDERINGINFO;
	}
	public void setCLASSNAMEKEYB2FOLDERINGINFO(String cLASSNAMEKEYB2FOLDERINGINFO) {
		CLASSNAMEKEYB2FOLDERINGINFO = cLASSNAMEKEYB2FOLDERINGINFO;
	}
	public int getIDA3B2FOLDERINGINFO() {
		return IDA3B2FOLDERINGINFO;
	}
	public void setIDA3B2FOLDERINGINFO(int iDA3B2FOLDERINGINFO) {
		IDA3B2FOLDERINGINFO = iDA3B2FOLDERINGINFO;
	}
	public boolean isHASHANGINGCHANGE() {
		return HASHANGINGCHANGE;
	}
	public void setHASHANGINGCHANGE(boolean hASHANGINGCHANGE) {
		HASHANGINGCHANGE = hASHANGINGCHANGE;
	}
	public boolean isHASPENDINGCHANGE() {
		return HASPENDINGCHANGE;
	}
	public void setHASPENDINGCHANGE(boolean hASPENDINGCHANGE) {
		HASPENDINGCHANGE = hASPENDINGCHANGE;
	}
	public boolean isHASRESULTINGCHANGE() {
		return HASRESULTINGCHANGE;
	}
	public void setHASRESULTINGCHANGE(boolean hASRESULTINGCHANGE) {
		HASRESULTINGCHANGE = hASRESULTINGCHANGE;
	}
	public boolean isHASVARIANCE() {
		return HASVARIANCE;
	}
	public void setHASVARIANCE(boolean hASVARIANCE) {
		HASVARIANCE = hASVARIANCE;
	}
	public String getINDEXERSINDEXERSET() {
		return INDEXERSINDEXERSET;
	}
	public void setINDEXERSINDEXERSET(String iNDEXERSINDEXERSET) {
		INDEXERSINDEXERSET = iNDEXERSINDEXERSET;
	}
	public boolean isINHERITEDDOMAIN() {
		return INHERITEDDOMAIN;
	}
	public void setINHERITEDDOMAIN(boolean iNHERITEDDOMAIN) {
		INHERITEDDOMAIN = iNHERITEDDOMAIN;
	}
	public int getBRANCHIDITERATIONINFO() {
		return BRANCHIDITERATIONINFO;
	}
	public void setBRANCHIDITERATIONINFO(int bRANCHIDITERATIONINFO) {
		BRANCHIDITERATIONINFO = bRANCHIDITERATIONINFO;
	}
	public String getCLASSNAMEKEYD2ITERATIONINFO() {
		return CLASSNAMEKEYD2ITERATIONINFO;
	}
	public void setCLASSNAMEKEYD2ITERATIONINFO(String cLASSNAMEKEYD2ITERATIONINFO) {
		CLASSNAMEKEYD2ITERATIONINFO = cLASSNAMEKEYD2ITERATIONINFO;
	}
	public int getIDA3D2ITERATIONINFO() {
		return IDA3D2ITERATIONINFO;
	}
	public void setIDA3D2ITERATIONINFO(int iDA3D2ITERATIONINFO) {
		IDA3D2ITERATIONINFO = iDA3D2ITERATIONINFO;
	}
	public String getCLASSNAMEKEYE2ITERATIONINFO() {
		return CLASSNAMEKEYE2ITERATIONINFO;
	}
	public void setCLASSNAMEKEYE2ITERATIONINFO(String cLASSNAMEKEYE2ITERATIONINFO) {
		CLASSNAMEKEYE2ITERATIONINFO = cLASSNAMEKEYE2ITERATIONINFO;
	}
	public int getIDA3E2ITERATIONINFO() {
		return IDA3E2ITERATIONINFO;
	}
	public void setIDA3E2ITERATIONINFO(int iDA3E2ITERATIONINFO) {
		IDA3E2ITERATIONINFO = iDA3E2ITERATIONINFO;
	}
	public String getITERATIONIDA2ITERATIONINFO() {
		return ITERATIONIDA2ITERATIONINFO;
	}
	public void setITERATIONIDA2ITERATIONINFO(String iTERATIONIDA2ITERATIONINFO) {
		ITERATIONIDA2ITERATIONINFO = iTERATIONIDA2ITERATIONINFO;
	}
	public boolean isLATESTITERATIONINFO() {
		return LATESTITERATIONINFO;
	}
	public void setLATESTITERATIONINFO(boolean lATESTITERATIONINFO) {
		LATESTITERATIONINFO = lATESTITERATIONINFO;
	}
	public String getCLASSNAMEKEYB2ITERATIONINFO() {
		return CLASSNAMEKEYB2ITERATIONINFO;
	}
	public void setCLASSNAMEKEYB2ITERATIONINFO(String cLASSNAMEKEYB2ITERATIONINFO) {
		CLASSNAMEKEYB2ITERATIONINFO = cLASSNAMEKEYB2ITERATIONINFO;
	}
	public int getIDA3B2ITERATIONINFO() {
		return IDA3B2ITERATIONINFO;
	}
	public void setIDA3B2ITERATIONINFO(int iDA3B2ITERATIONINFO) {
		IDA3B2ITERATIONINFO = iDA3B2ITERATIONINFO;
	}
	public String getNOTEITERATIONINFO() {
		return NOTEITERATIONINFO;
	}
	public void setNOTEITERATIONINFO(String nOTEITERATIONINFO) {
		NOTEITERATIONINFO = nOTEITERATIONINFO;
	}
	public String getCLASSNAMEKEYC2ITERATIONINFO() {
		return CLASSNAMEKEYC2ITERATIONINFO;
	}
	public void setCLASSNAMEKEYC2ITERATIONINFO(String cLASSNAMEKEYC2ITERATIONINFO) {
		CLASSNAMEKEYC2ITERATIONINFO = cLASSNAMEKEYC2ITERATIONINFO;
	}
	public int getIDA3C2ITERATIONINFO() {
		return IDA3C2ITERATIONINFO;
	}
	public void setIDA3C2ITERATIONINFO(int iDA3C2ITERATIONINFO) {
		IDA3C2ITERATIONINFO = iDA3C2ITERATIONINFO;
	}
	public String getSTATEITERATIONINFO() {
		return STATEITERATIONINFO;
	}
	public void setSTATEITERATIONINFO(String sTATEITERATIONINFO) {
		STATEITERATIONINFO = sTATEITERATIONINFO;
	}
	public Date getDATELOCK() {
		return DATELOCK;
	}
	public void setDATELOCK(Date dATELOCK) {
		DATELOCK = dATELOCK;
	}
	public String getCLASSNAMEKEYA2LOCK() {
		return CLASSNAMEKEYA2LOCK;
	}
	public void setCLASSNAMEKEYA2LOCK(String cLASSNAMEKEYA2LOCK) {
		CLASSNAMEKEYA2LOCK = cLASSNAMEKEYA2LOCK;
	}
	public int getIDA3A2LOCK() {
		return IDA3A2LOCK;
	}
	public void setIDA3A2LOCK(int iDA3A2LOCK) {
		IDA3A2LOCK = iDA3A2LOCK;
	}
	public String getNOTELOCK() {
		return NOTELOCK;
	}
	public void setNOTELOCK(String nOTELOCK) {
		NOTELOCK = nOTELOCK;
	}
	public String getCLASSNAMEKEYMASTERREFERENCE() {
		return CLASSNAMEKEYMASTERREFERENCE;
	}
	public void setCLASSNAMEKEYMASTERREFERENCE(String cLASSNAMEKEYMASTERREFERENCE) {
		CLASSNAMEKEYMASTERREFERENCE = cLASSNAMEKEYMASTERREFERENCE;
	}
	public int getIDA3MASTERREFERENCE() {
		return IDA3MASTERREFERENCE;
	}
	public void setIDA3MASTERREFERENCE(int iDA3MASTERREFERENCE) {
		IDA3MASTERREFERENCE = iDA3MASTERREFERENCE;
	}
	public String getCLASSNAMEKEYA2OWNERSHIP() {
		return CLASSNAMEKEYA2OWNERSHIP;
	}
	public void setCLASSNAMEKEYA2OWNERSHIP(String cLASSNAMEKEYA2OWNERSHIP) {
		CLASSNAMEKEYA2OWNERSHIP = cLASSNAMEKEYA2OWNERSHIP;
	}
	public int getIDA3A2OWNERSHIP() {
		return IDA3A2OWNERSHIP;
	}
	public void setIDA3A2OWNERSHIP(int iDA3A2OWNERSHIP) {
		IDA3A2OWNERSHIP = iDA3A2OWNERSHIP;
	}
	public String getPRIMARYIMAGEURL() {
		return PRIMARYIMAGEURL;
	}
	public void setPRIMARYIMAGEURL(String pRIMARYIMAGEURL) {
		PRIMARYIMAGEURL = pRIMARYIMAGEURL;
	}
	public String getSECURITYLABELS() {
		return SECURITYLABELS;
	}
	public void setSECURITYLABELS(String sECURITYLABELS) {
		SECURITYLABELS = sECURITYLABELS;
	}
	public boolean isATGATESTATE() {
		return ATGATESTATE;
	}
	public void setATGATESTATE(boolean aTGATESTATE) {
		ATGATESTATE = aTGATESTATE;
	}
	public String getCLASSNAMEKEYA2STATE() {
		return CLASSNAMEKEYA2STATE;
	}
	public void setCLASSNAMEKEYA2STATE(String cLASSNAMEKEYA2STATE) {
		CLASSNAMEKEYA2STATE = cLASSNAMEKEYA2STATE;
	}
	public int getIDA3A2STATE() {
		return IDA3A2STATE;
	}
	public void setIDA3A2STATE(int iDA3A2STATE) {
		IDA3A2STATE = iDA3A2STATE;
	}
	public String getSTATESTATE() {
		return STATESTATE;
	}
	public void setSTATESTATE(String sTATESTATE) {
		STATESTATE = sTATESTATE;
	}
	public boolean isTEAMIDISNULL() {
		return TEAMIDISNULL;
	}
	public void setTEAMIDISNULL(boolean tEAMIDISNULL) {
		TEAMIDISNULL = tEAMIDISNULL;
	}
	public String getCLASSNAMEKEYTEAMID() {
		return CLASSNAMEKEYTEAMID;
	}
	public void setCLASSNAMEKEYTEAMID(String cLASSNAMEKEYTEAMID) {
		CLASSNAMEKEYTEAMID = cLASSNAMEKEYTEAMID;
	}
	public int getIDA3TEAMID() {
		return IDA3TEAMID;
	}
	public void setIDA3TEAMID(int iDA3TEAMID) {
		IDA3TEAMID = iDA3TEAMID;
	}
	public boolean isTEAMTEMPLATEIDISNULL() {
		return TEAMTEMPLATEIDISNULL;
	}
	public void setTEAMTEMPLATEIDISNULL(boolean tEAMTEMPLATEIDISNULL) {
		TEAMTEMPLATEIDISNULL = tEAMTEMPLATEIDISNULL;
	}
	public String getCLASSNAMEKEYTEAMTEMPLATEID() {
		return CLASSNAMEKEYTEAMTEMPLATEID;
	}
	public void setCLASSNAMEKEYTEAMTEMPLATEID(String cLASSNAMEKEYTEAMTEMPLATEID) {
		CLASSNAMEKEYTEAMTEMPLATEID = cLASSNAMEKEYTEAMTEMPLATEID;
	}
	public int getIDA3TEAMTEMPLATEID() {
		return IDA3TEAMTEMPLATEID;
	}
	public void setIDA3TEAMTEMPLATEID(int iDA3TEAMTEMPLATEID) {
		IDA3TEAMTEMPLATEID = iDA3TEAMTEMPLATEID;
	}
	public Date getCREATESTAMPA2() {
		return CREATESTAMPA2;
	}
	public void setCREATESTAMPA2(Date cREATESTAMPA2) {
		CREATESTAMPA2 = cREATESTAMPA2;
	}
	public int getMARKFORDELETEA2() {
		return MARKFORDELETEA2;
	}
	public void setMARKFORDELETEA2(int mARKFORDELETEA2) {
		MARKFORDELETEA2 = mARKFORDELETEA2;
	}
	public Date getMODIFYSTAMPA2() {
		return MODIFYSTAMPA2;
	}
	public void setMODIFYSTAMPA2(Date mODIFYSTAMPA2) {
		MODIFYSTAMPA2 = mODIFYSTAMPA2;
	}
	public String getCLASSNAMEA2A2() {
		return CLASSNAMEA2A2;
	}
	public void setCLASSNAMEA2A2(String cLASSNAMEA2A2) {
		CLASSNAMEA2A2 = cLASSNAMEA2A2;
	}
	public int getUPDATECOUNTA2() {
		return UPDATECOUNTA2;
	}
	public void setUPDATECOUNTA2(int uPDATECOUNTA2) {
		UPDATECOUNTA2 = uPDATECOUNTA2;
	}
	public Date getUPDATESTAMPA2() {
		return UPDATESTAMPA2;
	}
	public void setUPDATESTAMPA2(Date uPDATESTAMPA2) {
		UPDATESTAMPA2 = uPDATESTAMPA2;
	}
	public int getBRANCHIDA2TYPEDEFINITIONREFE() {
		return BRANCHIDA2TYPEDEFINITIONREFE;
	}
	public void setBRANCHIDA2TYPEDEFINITIONREFE(int bRANCHIDA2TYPEDEFINITIONREFE) {
		BRANCHIDA2TYPEDEFINITIONREFE = bRANCHIDA2TYPEDEFINITIONREFE;
	}
	public int getIDA2TYPEDEFINITIONREFERENCE() {
		return IDA2TYPEDEFINITIONREFERENCE;
	}
	public void setIDA2TYPEDEFINITIONREFERENCE(int iDA2TYPEDEFINITIONREFERENCE) {
		IDA2TYPEDEFINITIONREFERENCE = iDA2TYPEDEFINITIONREFERENCE;
	}
	public String getTYPEDISPLAY() {
		return TYPEDISPLAY;
	}
	public void setTYPEDISPLAY(String tYPEDISPLAY) {
		TYPEDISPLAY = tYPEDISPLAY;
	}
	public String getVERSIONIDA2VERSIONINFO() {
		return VERSIONIDA2VERSIONINFO;
	}
	public void setVERSIONIDA2VERSIONINFO(String vERSIONIDA2VERSIONINFO) {
		VERSIONIDA2VERSIONINFO = vERSIONIDA2VERSIONINFO;
	}
	public int getVERSIONLEVELA2VERSIONINFO() {
		return VERSIONLEVELA2VERSIONINFO;
	}
	public void setVERSIONLEVELA2VERSIONINFO(int vERSIONLEVELA2VERSIONINFO) {
		VERSIONLEVELA2VERSIONINFO = vERSIONLEVELA2VERSIONINFO;
	}
	public String getVERSIONSORTIDA2VERSIONINFO() {
		return VERSIONSORTIDA2VERSIONINFO;
	}
	public void setVERSIONSORTIDA2VERSIONINFO(String vERSIONSORTIDA2VERSIONINFO) {
		VERSIONSORTIDA2VERSIONINFO = vERSIONSORTIDA2VERSIONINFO;
	}
	public String getPTC_STR_1TYPEINFOLCSMATERIAL() {
		return PTC_STR_1TYPEINFOLCSMATERIAL;
	}
	public void setPTC_STR_1TYPEINFOLCSMATERIAL(String pTC_STR_1TYPEINFOLCSMATERIAL) {
		PTC_STR_1TYPEINFOLCSMATERIAL = pTC_STR_1TYPEINFOLCSMATERIAL;
	}
	public String getPTC_STR_2TYPEINFOLCSMATERIAL() {
		return PTC_STR_2TYPEINFOLCSMATERIAL;
	}
	public void setPTC_STR_2TYPEINFOLCSMATERIAL(String pTC_STR_2TYPEINFOLCSMATERIAL) {
		PTC_STR_2TYPEINFOLCSMATERIAL = pTC_STR_2TYPEINFOLCSMATERIAL;
	}
	public String getPTC_STR_3TYPEINFOLCSMATERIAL() {
		return PTC_STR_3TYPEINFOLCSMATERIAL;
	}
	public void setPTC_STR_3TYPEINFOLCSMATERIAL(String pTC_STR_3TYPEINFOLCSMATERIAL) {
		PTC_STR_3TYPEINFOLCSMATERIAL = pTC_STR_3TYPEINFOLCSMATERIAL;
	}
	public String getPTC_STR_4TYPEINFOLCSMATERIAL() {
		return PTC_STR_4TYPEINFOLCSMATERIAL;
	}
	public void setPTC_STR_4TYPEINFOLCSMATERIAL(String pTC_STR_4TYPEINFOLCSMATERIAL) {
		PTC_STR_4TYPEINFOLCSMATERIAL = pTC_STR_4TYPEINFOLCSMATERIAL;
	}
	public boolean isPTC_BLN_1TYPEINFOLCSMATERIAL() {
		return PTC_BLN_1TYPEINFOLCSMATERIAL;
	}
	public void setPTC_BLN_1TYPEINFOLCSMATERIAL(boolean pTC_BLN_1TYPEINFOLCSMATERIAL) {
		PTC_BLN_1TYPEINFOLCSMATERIAL = pTC_BLN_1TYPEINFOLCSMATERIAL;
	}
	public boolean isPTC_BLN_2TYPEINFOLCSMATERIAL() {
		return PTC_BLN_2TYPEINFOLCSMATERIAL;
	}
	public void setPTC_BLN_2TYPEINFOLCSMATERIAL(boolean pTC_BLN_2TYPEINFOLCSMATERIAL) {
		PTC_BLN_2TYPEINFOLCSMATERIAL = pTC_BLN_2TYPEINFOLCSMATERIAL;
	}
	public Double getPTC_DBL_1TYPEINFOLCSMATERIAL() {
		return PTC_DBL_1TYPEINFOLCSMATERIAL;
	}
	public void setPTC_DBL_1TYPEINFOLCSMATERIAL(Double pTC_DBL_1TYPEINFOLCSMATERIAL) {
		PTC_DBL_1TYPEINFOLCSMATERIAL = pTC_DBL_1TYPEINFOLCSMATERIAL;
	}
	public Double getPTC_DBL_2TYPEINFOLCSMATERIAL() {
		return PTC_DBL_2TYPEINFOLCSMATERIAL;
	}
	public void setPTC_DBL_2TYPEINFOLCSMATERIAL(Double pTC_DBL_2TYPEINFOLCSMATERIAL) {
		PTC_DBL_2TYPEINFOLCSMATERIAL = pTC_DBL_2TYPEINFOLCSMATERIAL;
	}
	public long getPTC_LNG_1TYPEINFOLCSMATERIAL() {
		return PTC_LNG_1TYPEINFOLCSMATERIAL;
	}
	public void setPTC_LNG_1TYPEINFOLCSMATERIAL(long pTC_LNG_1TYPEINFOLCSMATERIAL) {
		PTC_LNG_1TYPEINFOLCSMATERIAL = pTC_LNG_1TYPEINFOLCSMATERIAL;
	}
	public long getPTC_LNG_2TYPEINFOLCSMATERIAL() {
		return PTC_LNG_2TYPEINFOLCSMATERIAL;
	}
	public void setPTC_LNG_2TYPEINFOLCSMATERIAL(long pTC_LNG_2TYPEINFOLCSMATERIAL) {
		PTC_LNG_2TYPEINFOLCSMATERIAL = pTC_LNG_2TYPEINFOLCSMATERIAL;
	}
	public String getPTC_STR_5TYPEINFOLCSMATERIAL() {
		return PTC_STR_5TYPEINFOLCSMATERIAL;
	}
	public void setPTC_STR_5TYPEINFOLCSMATERIAL(String pTC_STR_5TYPEINFOLCSMATERIAL) {
		PTC_STR_5TYPEINFOLCSMATERIAL = pTC_STR_5TYPEINFOLCSMATERIAL;
	}
	public String getPTC_STR_6TYPEINFOLCSMATERIAL() {
		return PTC_STR_6TYPEINFOLCSMATERIAL;
	}
	public void setPTC_STR_6TYPEINFOLCSMATERIAL(String pTC_STR_6TYPEINFOLCSMATERIAL) {
		PTC_STR_6TYPEINFOLCSMATERIAL = pTC_STR_6TYPEINFOLCSMATERIAL;
	}
	public Date getPTC_TMS_1TYPEINFOLCSMATERIAL() {
		return PTC_TMS_1TYPEINFOLCSMATERIAL;
	}
	public void setPTC_TMS_1TYPEINFOLCSMATERIAL(Date pTC_TMS_1TYPEINFOLCSMATERIAL) {
		PTC_TMS_1TYPEINFOLCSMATERIAL = pTC_TMS_1TYPEINFOLCSMATERIAL;
	}
	public Date getPTC_TMS_2TYPEINFOLCSMATERIAL() {
		return PTC_TMS_2TYPEINFOLCSMATERIAL;
	}
	public void setPTC_TMS_2TYPEINFOLCSMATERIAL(Date pTC_TMS_2TYPEINFOLCSMATERIAL) {
		PTC_TMS_2TYPEINFOLCSMATERIAL = pTC_TMS_2TYPEINFOLCSMATERIAL;
	}
	@Override
	public String toString() {
		return "LCSMaterial [IDA2A2=" + IDA2A2 + ", ADMINISTRATIVELOCKISNULL=" + ADMINISTRATIVELOCKISNULL
				+ ", TYPEADMINISTRATIVELOCK=" + TYPEADMINISTRATIVELOCK + ", BLOB$ENTRYSETADHOCACL="
				+ Arrays.toString(BLOB$ENTRYSETADHOCACL) + ", CHECKOUTINFOISNULL=" + CHECKOUTINFOISNULL
				+ ", STATECHECKOUTINFO=" + STATECHECKOUTINFO + ", CLASSNAMEKEYCONTAINERREFEREN="
				+ CLASSNAMEKEYCONTAINERREFEREN + ", IDA3CONTAINERREFERENCE=" + IDA3CONTAINERREFERENCE
				+ ", CLASSNAMEKEYB10=" + CLASSNAMEKEYB10 + ", IDA3B10=" + IDA3B10 + ", CLASSNAMEKEYDOMAINREF="
				+ CLASSNAMEKEYDOMAINREF + ", IDA3DOMAINREF=" + IDA3DOMAINREF + ", ENTRYSETADHOCACL=" + ENTRYSETADHOCACL
				+ ", EVENTSET=" + EVENTSET + ", FLEXTYPEIDPATH=" + FLEXTYPEIDPATH + ", CLASSNAMEKEYA2FOLDERINGINFO="
				+ CLASSNAMEKEYA2FOLDERINGINFO + ", IDA3A2FOLDERINGINFO=" + IDA3A2FOLDERINGINFO
				+ ", CLASSNAMEKEYB2FOLDERINGINFO=" + CLASSNAMEKEYB2FOLDERINGINFO + ", IDA3B2FOLDERINGINFO="
				+ IDA3B2FOLDERINGINFO + ", HASHANGINGCHANGE=" + HASHANGINGCHANGE + ", HASPENDINGCHANGE="
				+ HASPENDINGCHANGE + ", HASRESULTINGCHANGE=" + HASRESULTINGCHANGE + ", HASVARIANCE=" + HASVARIANCE
				+ ", INDEXERSINDEXERSET=" + INDEXERSINDEXERSET + ", INHERITEDDOMAIN=" + INHERITEDDOMAIN
				+ ", BRANCHIDITERATIONINFO=" + BRANCHIDITERATIONINFO + ", CLASSNAMEKEYD2ITERATIONINFO="
				+ CLASSNAMEKEYD2ITERATIONINFO + ", IDA3D2ITERATIONINFO=" + IDA3D2ITERATIONINFO
				+ ", CLASSNAMEKEYE2ITERATIONINFO=" + CLASSNAMEKEYE2ITERATIONINFO + ", IDA3E2ITERATIONINFO="
				+ IDA3E2ITERATIONINFO + ", ITERATIONIDA2ITERATIONINFO=" + ITERATIONIDA2ITERATIONINFO
				+ ", LATESTITERATIONINFO=" + LATESTITERATIONINFO + ", CLASSNAMEKEYB2ITERATIONINFO="
				+ CLASSNAMEKEYB2ITERATIONINFO + ", IDA3B2ITERATIONINFO=" + IDA3B2ITERATIONINFO + ", NOTEITERATIONINFO="
				+ NOTEITERATIONINFO + ", CLASSNAMEKEYC2ITERATIONINFO=" + CLASSNAMEKEYC2ITERATIONINFO
				+ ", IDA3C2ITERATIONINFO=" + IDA3C2ITERATIONINFO + ", STATEITERATIONINFO=" + STATEITERATIONINFO
				+ ", DATELOCK=" + DATELOCK + ", CLASSNAMEKEYA2LOCK=" + CLASSNAMEKEYA2LOCK + ", IDA3A2LOCK=" + IDA3A2LOCK
				+ ", NOTELOCK=" + NOTELOCK + ", CLASSNAMEKEYMASTERREFERENCE=" + CLASSNAMEKEYMASTERREFERENCE
				+ ", IDA3MASTERREFERENCE=" + IDA3MASTERREFERENCE + ", CLASSNAMEKEYA2OWNERSHIP="
				+ CLASSNAMEKEYA2OWNERSHIP + ", IDA3A2OWNERSHIP=" + IDA3A2OWNERSHIP + ", PRIMARYIMAGEURL="
				+ PRIMARYIMAGEURL + ", SECURITYLABELS=" + SECURITYLABELS + ", ATGATESTATE=" + ATGATESTATE
				+ ", CLASSNAMEKEYA2STATE=" + CLASSNAMEKEYA2STATE + ", IDA3A2STATE=" + IDA3A2STATE + ", STATESTATE="
				+ STATESTATE + ", TEAMIDISNULL=" + TEAMIDISNULL + ", CLASSNAMEKEYTEAMID=" + CLASSNAMEKEYTEAMID
				+ ", IDA3TEAMID=" + IDA3TEAMID + ", TEAMTEMPLATEIDISNULL=" + TEAMTEMPLATEIDISNULL
				+ ", CLASSNAMEKEYTEAMTEMPLATEID=" + CLASSNAMEKEYTEAMTEMPLATEID + ", IDA3TEAMTEMPLATEID="
				+ IDA3TEAMTEMPLATEID + ", CREATESTAMPA2=" + CREATESTAMPA2 + ", MARKFORDELETEA2=" + MARKFORDELETEA2
				+ ", MODIFYSTAMPA2=" + MODIFYSTAMPA2 + ", CLASSNAMEA2A2=" + CLASSNAMEA2A2 + ", UPDATECOUNTA2="
				+ UPDATECOUNTA2 + ", UPDATESTAMPA2=" + UPDATESTAMPA2 + ", BRANCHIDA2TYPEDEFINITIONREFE="
				+ BRANCHIDA2TYPEDEFINITIONREFE + ", IDA2TYPEDEFINITIONREFERENCE=" + IDA2TYPEDEFINITIONREFERENCE
				+ ", TYPEDISPLAY=" + TYPEDISPLAY + ", VERSIONIDA2VERSIONINFO=" + VERSIONIDA2VERSIONINFO
				+ ", VERSIONLEVELA2VERSIONINFO=" + VERSIONLEVELA2VERSIONINFO + ", VERSIONSORTIDA2VERSIONINFO="
				+ VERSIONSORTIDA2VERSIONINFO + ", PTC_STR_1TYPEINFOLCSMATERIAL=" + PTC_STR_1TYPEINFOLCSMATERIAL
				+ ", PTC_STR_2TYPEINFOLCSMATERIAL=" + PTC_STR_2TYPEINFOLCSMATERIAL + ", PTC_STR_3TYPEINFOLCSMATERIAL="
				+ PTC_STR_3TYPEINFOLCSMATERIAL + ", PTC_STR_4TYPEINFOLCSMATERIAL=" + PTC_STR_4TYPEINFOLCSMATERIAL
				+ ", PTC_BLN_1TYPEINFOLCSMATERIAL=" + PTC_BLN_1TYPEINFOLCSMATERIAL + ", PTC_BLN_2TYPEINFOLCSMATERIAL="
				+ PTC_BLN_2TYPEINFOLCSMATERIAL + ", PTC_DBL_1TYPEINFOLCSMATERIAL=" + PTC_DBL_1TYPEINFOLCSMATERIAL
				+ ", PTC_DBL_2TYPEINFOLCSMATERIAL=" + PTC_DBL_2TYPEINFOLCSMATERIAL + ", PTC_LNG_1TYPEINFOLCSMATERIAL="
				+ PTC_LNG_1TYPEINFOLCSMATERIAL + ", PTC_LNG_2TYPEINFOLCSMATERIAL=" + PTC_LNG_2TYPEINFOLCSMATERIAL
				+ ", PTC_STR_5TYPEINFOLCSMATERIAL=" + PTC_STR_5TYPEINFOLCSMATERIAL + ", PTC_STR_6TYPEINFOLCSMATERIAL="
				+ PTC_STR_6TYPEINFOLCSMATERIAL + ", PTC_TMS_1TYPEINFOLCSMATERIAL=" + PTC_TMS_1TYPEINFOLCSMATERIAL
				+ ", PTC_TMS_2TYPEINFOLCSMATERIAL=" + PTC_TMS_2TYPEINFOLCSMATERIAL + "]";
	}    
	
}
