
package com.qiwkreport.qiwk.etl.domain;
/*
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

*//**
 * @author abhilash This is Qiwk Color object
 *
 *//*

@Entity
@Table(name = "QIWKCOLOR")*/
public class QiwkColor_old {/*

	*//**
	 * Don't include any id genrator type here when developing actual FR/NC job
	 * use database sequence generator or any other genrator based on business
	 * decision.
	 *//*
	@Id
	@Column(name = "primaryKey")
	private int primaryKey;
	
	@Column(name = "BRANCHID")
	private int BRANCHID;
	@Column(name = "CREATESTAMPA2")
	private Date CREATESTAMPA2;
	@Column(name = "UPDATESTAMPA2")
	private Date UPDATESTAMPA2;
	@Column(name = "FLEXTYPEIDPATH")
	private String FLEXTYPEIDPATH;
	@Column(name = "FLEXTYPEID")
	private int FLEXTYPEID;
	@Column(name = "COLORHEXIDECIMALVALUE")
	private String COLORHEXIDECIMALVALUE;
	@Column(name = "THUMBNAIL")
	private String THUMBNAIL;
	@Column(name = "COLORNAME")
	private String COLORNAME;
	@Column(name = "UPDATECOUNTA2")
	private int UPDATECOUNTA2;
	@Column(name = "MARKEDFORDELETEA2")
	private int MARKEDFORDELETEA2;
	@Column(name = "IDA2TYPEDEFINITIONREFERENCE")
	private int IDA2TYPEDEFINITIONREFERENCE;
	@Column(name = "LOADERCREATESTAMP")
	private Timestamp LOADERCREATESTAMP;
	@Column(name = "LOADERUPDATESTAMP")
	private Timestamp LOADERUPDATESTAMP;
	@Column(name = "BRANCHIDA3E2TYPEINFOLCSCOLOR")
	private int BRANCHIDA3E2TYPEINFOLCSCOLOR;
	@Column(name = "BRANCHIDA3D2TYPEINFOLCSCOLOR")
	private int BRANCHIDA3D2TYPEINFOLCSCOLOR;
	@Column(name = "BRANCHIDA3C2TYPEINFOLCSCOLOR")
	private int BRANCHIDA3C2TYPEINFOLCSCOLOR;
	@Column(name = "BRANCHIDA3B2TYPEINFOLCSCOLOR")
	private int BRANCHIDA3B2TYPEINFOLCSCOLOR;
	@Column(name = "BRANCHIDA3A2TYPEINFOLCSCOLOR")
	private int BRANCHIDA3A2TYPEINFOLCSCOLOR;

	@Column(name = "PTC_DBL_1TYPEINFOLCSCOLOR")
	private double PTC_DBL_1TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_2TYPEINFOLCSCOLOR")
	private double PTC_DBL_2TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_3TYPEINFOLCSCOLOR")
	private double PTC_DBL_3TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_4TYPEINFOLCSCOLOR")
	private double PTC_DBL_4TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_5TYPEINFOLCSCOLOR")
	private double PTC_DBL_5TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_6TYPEINFOLCSCOLOR")
	private double PTC_DBL_6TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_7TYPEINFOLCSCOLOR")
	private double PTC_DBL_7TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_8TYPEINFOLCSCOLOR")
	private double PTC_DBL_8TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_9TYPEINFOLCSCOLOR")
	private double PTC_DBL_9TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_10TYPEINFOLCSCOLOR")
	private double PTC_DBL_10TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_11TYPEINFOLCSCOLOR")
	private double PTC_DBL_11TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_12TYPEINFOLCSCOLOR")
	private double PTC_DBL_12TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_13TYPEINFOLCSCOLOR")
	private double PTC_DBL_13TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_14TYPEINFOLCSCOLOR")
	private double PTC_DBL_14TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_15TYPEINFOLCSCOLOR")
	private double PTC_DBL_15TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_16TYPEINFOLCSCOLOR")
	private double PTC_DBL_16TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_17TYPEINFOLCSCOLOR")
	private double PTC_DBL_17TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_18TYPEINFOLCSCOLOR")
	private double PTC_DBL_18TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_19TYPEINFOLCSCOLOR")
	private double PTC_DBL_19TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_20TYPEINFOLCSCOLOR")
	private double PTC_DBL_20TYPEINFOLCSCOLOR;

	@Column(name = "PTC_STR_1TYPEINFOLCSCOLOR")
	private String PTC_STR_1TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_2TYPEINFOLCSCOLOR")
	private String PTC_STR_2TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_3TYPEINFOLCSCOLOR")
	private String PTC_STR_3TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_4TYPEINFOLCSCOLOR")
	private String PTC_STR_4TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_5TYPEINFOLCSCOLOR")
	private String PTC_STR_5TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_6TYPEINFOLCSCOLOR")
	private String PTC_STR_6TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_7TYPEINFOLCSCOLOR")
	private String PTC_STR_7TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_8TYPEINFOLCSCOLOR")
	private String PTC_STR_8TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_9TYPEINFOLCSCOLOR")
	private String PTC_STR_9TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_10TYPEINFOLCSCOLOR")
	private String PTC_STR_10TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_11TYPEINFOLCSCOLOR")
	private String PTC_STR_11TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_12TYPEINFOLCSCOLOR")
	private String PTC_STR_12TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_13TYPEINFOLCSCOLOR")
	private String PTC_STR_13TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_14TYPEINFOLCSCOLOR")
	private String PTC_STR_14TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_15TYPEINFOLCSCOLOR")
	private String PTC_STR_15TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_16TYPEINFOLCSCOLOR")
	private String PTC_STR_16TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_17TYPEINFOLCSCOLOR")
	private String PTC_STR_17TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_18TYPEINFOLCSCOLOR")
	private String PTC_STR_18TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_19TYPEINFOLCSCOLOR")
	private String PTC_STR_19TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_20TYPEINFOLCSCOLOR")
	private String PTC_STR_20TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_21TYPEINFOLCSCOLOR")
	private String PTC_STR_21TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_22TYPEINFOLCSCOLOR")
	private String PTC_STR_22TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_23TYPEINFOLCSCOLOR")
	private String PTC_STR_23TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_24TYPEINFOLCSCOLOR")
	private String PTC_STR_24TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_25TYPEINFOLCSCOLOR")
	private String PTC_STR_25TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_26TYPEINFOLCSCOLOR")
	private String PTC_STR_26TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_27TYPEINFOLCSCOLOR")
	private String PTC_STR_27TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_28TYPEINFOLCSCOLOR")
	private String PTC_STR_28TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_29TYPEINFOLCSCOLOR")
	private String PTC_STR_29TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_30TYPEINFOLCSCOLOR")
	private String PTC_STR_30TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_31TYPEINFOLCSCOLOR")
	private String PTC_STR_31TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_32TYPEINFOLCSCOLOR")
	private String PTC_STR_32TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_33TYPEINFOLCSCOLOR")
	private String PTC_STR_33TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_34TYPEINFOLCSCOLOR")
	private String PTC_STR_34TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_35TYPEINFOLCSCOLOR")
	private String PTC_STR_35TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_36TYPEINFOLCSCOLOR")
	private String PTC_STR_36TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_37TYPEINFOLCSCOLOR")
	private String PTC_STR_37TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_38TYPEINFOLCSCOLOR")
	private String PTC_STR_38TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_39TYPEINFOLCSCOLOR")
	private String PTC_STR_39TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_40TYPEINFOLCSCOLOR")
	private String PTC_STR_40TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_41TYPEINFOLCSCOLOR")
	private String PTC_STR_41TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_42TYPEINFOLCSCOLOR")
	private String PTC_STR_42TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_43TYPEINFOLCSCOLOR")
	private String PTC_STR_43TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_44TYPEINFOLCSCOLOR")
	private String PTC_STR_44TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_45TYPEINFOLCSCOLOR")
	private String PTC_STR_45TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_46TYPEINFOLCSCOLOR")
	private String PTC_STR_46TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_47TYPEINFOLCSCOLOR")
	private String PTC_STR_47TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_48TYPEINFOLCSCOLOR")
	private String PTC_STR_48TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_49TYPEINFOLCSCOLOR")
	private String PTC_STR_49TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_50TYPEINFOLCSCOLOR")
	private String PTC_STR_50TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_51TYPEINFOLCSCOLOR")
	private String PTC_STR_51TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_52TYPEINFOLCSCOLOR")
	private String PTC_STR_52TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_53TYPEINFOLCSCOLOR")
	private String PTC_STR_53TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_54TYPEINFOLCSCOLOR")
	private String PTC_STR_54TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_55TYPEINFOLCSCOLOR")
	private String PTC_STR_55TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_56TYPEINFOLCSCOLOR")
	private String PTC_STR_56TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_57TYPEINFOLCSCOLOR")
	private String PTC_STR_57TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_58TYPEINFOLCSCOLOR")
	private String PTC_STR_58TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_59TYPEINFOLCSCOLOR")
	private String PTC_STR_59TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_60TYPEINFOLCSCOLOR")
	private String PTC_STR_60TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_61TYPEINFOLCSCOLOR")
	private String PTC_STR_61TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_62TYPEINFOLCSCOLOR")
	private String PTC_STR_62TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_63TYPEINFOLCSCOLOR")
	private String PTC_STR_63TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_64TYPEINFOLCSCOLOR")
	private String PTC_STR_64TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_65TYPEINFOLCSCOLOR")
	private String PTC_STR_65TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_66TYPEINFOLCSCOLOR")
	private String PTC_STR_66TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_67TYPEINFOLCSCOLOR")
	private String PTC_STR_67TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_68TYPEINFOLCSCOLOR")
	private String PTC_STR_68TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_69TYPEINFOLCSCOLOR")
	private String PTC_STR_69TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_70TYPEINFOLCSCOLOR")
	private String PTC_STR_70TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_71TYPEINFOLCSCOLOR")
	private String PTC_STR_71TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_72TYPEINFOLCSCOLOR")
	private String PTC_STR_72TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_73TYPEINFOLCSCOLOR")
	private String PTC_STR_73TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_74TYPEINFOLCSCOLOR")
	private String PTC_STR_74TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_75TYPEINFOLCSCOLOR")
	private String PTC_STR_75TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_76TYPEINFOLCSCOLOR")
	private String PTC_STR_76TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_77TYPEINFOLCSCOLOR")
	private String PTC_STR_77TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_78TYPEINFOLCSCOLOR")
	private String PTC_STR_78TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_79TYPEINFOLCSCOLOR")
	private String PTC_STR_79TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_80TYPEINFOLCSCOLOR")
	private String PTC_STR_80TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_81TYPEINFOLCSCOLOR")
	private String PTC_STR_81TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_82TYPEINFOLCSCOLOR")
	private String PTC_STR_82TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_83TYPEINFOLCSCOLOR")
	private String PTC_STR_83TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_84TYPEINFOLCSCOLOR")
	private String PTC_STR_84TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_85TYPEINFOLCSCOLOR")
	private String PTC_STR_85TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_86TYPEINFOLCSCOLOR")
	private String PTC_STR_86TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_87TYPEINFOLCSCOLOR")
	private String PTC_STR_87TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_88TYPEINFOLCSCOLOR")
	private String PTC_STR_88TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_89TYPEINFOLCSCOLOR")
	private String PTC_STR_89TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_90TYPEINFOLCSCOLOR")
	private String PTC_STR_90TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_91TYPEINFOLCSCOLOR")
	private String PTC_STR_91TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_92TYPEINFOLCSCOLOR")
	private String PTC_STR_92TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_93TYPEINFOLCSCOLOR")
	private String PTC_STR_93TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_94TYPEINFOLCSCOLOR")
	private String PTC_STR_94TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_95TYPEINFOLCSCOLOR")
	private String PTC_STR_95TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_96TYPEINFOLCSCOLOR")
	private String PTC_STR_96TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_97TYPEINFOLCSCOLOR")
	private String PTC_STR_97TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_98TYPEINFOLCSCOLOR")
	private String PTC_STR_98TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_99TYPEINFOLCSCOLOR")
	private String PTC_STR_99TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_100TYPEINFOLCSCOLOR")
	private String PTC_STR_100TYPEINFOLCSCOLOR;

	@Column(name = "PTC_LNG_1TYPEINFOLCSCOLOR")
	private long PTC_LNG_1TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_2TYPEINFOLCSCOLOR")
	private long PTC_LNG_2TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_3TYPEINFOLCSCOLOR")
	private long PTC_LNG_3TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_4TYPEINFOLCSCOLOR")
	private long PTC_LNG_4TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_5TYPEINFOLCSCOLOR")
	private long PTC_LNG_5TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_6TYPEINFOLCSCOLOR")
	private long PTC_LNG_6TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_7TYPEINFOLCSCOLOR")
	private long PTC_LNG_7TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_8TYPEINFOLCSCOLOR")
	private long PTC_LNG_8TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_9TYPEINFOLCSCOLOR")
	private long PTC_LNG_9TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_10TYPEINFOLCSCOLOR")
	private long PTC_LNG_10TYPEINFOLCSCOLOR;

	@Column(name = "PTC_TMS_1TYPEINFOLCSCOLOR")
	private Date PTC_TMS_1TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_2TYPEINFOLCSCOLOR")
	private Date PTC_TMS_2TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_3TYPEINFOLCSCOLOR")
	private Date PTC_TMS_3TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_4TYPEINFOLCSCOLOR")
	private Date PTC_TMS_4TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_5TYPEINFOLCSCOLOR")
	private Date PTC_TMS_5TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_6TYPEINFOLCSCOLOR")
	private Date PTC_TMS_6TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_7TYPEINFOLCSCOLOR")
	private Date PTC_TMS_7TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_8TYPEINFOLCSCOLOR")
	private Date PTC_TMS_8TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_9TYPEINFOLCSCOLOR")
	private Date PTC_TMS_9TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_10TYPEINFOLCSCOLOR")
	private Date PTC_TMS_10TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_11TYPEINFOLCSCOLOR")
	private Date PTC_TMS_11TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_12TYPEINFOLCSCOLOR")
	private Date PTC_TMS_12TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_13TYPEINFOLCSCOLOR")
	private Date PTC_TMS_13TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_14TYPEINFOLCSCOLOR")
	private Date PTC_TMS_14TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_15TYPEINFOLCSCOLOR")
	private Date PTC_TMS_15TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_16TYPEINFOLCSCOLOR")
	private Date PTC_TMS_16TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_17TYPEINFOLCSCOLOR")
	private Date PTC_TMS_17TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_18TYPEINFOLCSCOLOR")
	private Date PTC_TMS_18TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_19TYPEINFOLCSCOLOR")
	private Date PTC_TMS_19TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_20TYPEINFOLCSCOLOR")
	private Date PTC_TMS_20TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_21TYPEINFOLCSCOLOR")
	private Date PTC_TMS_21TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_22TYPEINFOLCSCOLOR")
	private Date PTC_TMS_22TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_23TYPEINFOLCSCOLOR")
	private Date PTC_TMS_23TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_24TYPEINFOLCSCOLOR")
	private Date PTC_TMS_24TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_25TYPEINFOLCSCOLOR")
	private Date PTC_TMS_25TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_26TYPEINFOLCSCOLOR")
	private Date PTC_TMS_26TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_27TYPEINFOLCSCOLOR")
	private Date PTC_TMS_27TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_28TYPEINFOLCSCOLOR")
	private Date PTC_TMS_28TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_29TYPEINFOLCSCOLOR")
	private Date PTC_TMS_29TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_30TYPEINFOLCSCOLOR")
	private Date PTC_TMS_30TYPEINFOLCSCOLOR;

	@Column(name = "PTC_BLN_1TYPEINFOLCSCOLOR")
	private String PTC_BLN_1TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_2TYPEINFOLCSCOLOR")
	private String PTC_BLN_2TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_3TYPEINFOLCSCOLOR")
	private String PTC_BLN_3TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_4TYPEINFOLCSCOLOR")
	private String PTC_BLN_4TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_5TYPEINFOLCSCOLOR")
	private String PTC_BLN_5TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_6TYPEINFOLCSCOLOR")
	private String PTC_BLN_6TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_7TYPEINFOLCSCOLOR")
	private String PTC_BLN_7TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_8TYPEINFOLCSCOLOR")
	private String PTC_BLN_8TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_9TYPEINFOLCSCOLOR")
	private String PTC_BLN_9TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_10TYPEINFOLCSCOLOR")
	private String PTC_BLN_10TYPEINFOLCSCOLOR;
	
	public QiwkColor_old() {
		super();
	}

	
	
	public QiwkColor_old(int primaryKey, int bRANCHID, Date cREATESTAMPA2, Date uPDATESTAMPA2, String fLEXTYPEIDPATH,
			int fLEXTYPEID, String cOLORHEXIDECIMALVALUE, String tHUMBNAIL, String cOLORNAME, int uPDATECOUNTA2,
			int mARKEDFORDELETEA2, int iDA2TYPEDEFINITIONREFERENCE, Timestamp lOADERCREATESTAMP,
			Timestamp lOADERUPDATESTAMP, int bRANCHIDA3E2TYPEINFOLCSCOLOR, int bRANCHIDA3D2TYPEINFOLCSCOLOR,
			int bRANCHIDA3C2TYPEINFOLCSCOLOR, int bRANCHIDA3B2TYPEINFOLCSCOLOR, int bRANCHIDA3A2TYPEINFOLCSCOLOR,
			double pTC_DBL_1TYPEINFOLCSCOLOR, double pTC_DBL_2TYPEINFOLCSCOLOR, double pTC_DBL_3TYPEINFOLCSCOLOR,
			double pTC_DBL_4TYPEINFOLCSCOLOR, double pTC_DBL_5TYPEINFOLCSCOLOR, double pTC_DBL_6TYPEINFOLCSCOLOR,
			double pTC_DBL_7TYPEINFOLCSCOLOR, double pTC_DBL_8TYPEINFOLCSCOLOR, double pTC_DBL_9TYPEINFOLCSCOLOR,
			double pTC_DBL_10TYPEINFOLCSCOLOR, double pTC_DBL_11TYPEINFOLCSCOLOR, double pTC_DBL_12TYPEINFOLCSCOLOR,
			double pTC_DBL_13TYPEINFOLCSCOLOR, double pTC_DBL_14TYPEINFOLCSCOLOR, double pTC_DBL_15TYPEINFOLCSCOLOR,
			double pTC_DBL_16TYPEINFOLCSCOLOR, double pTC_DBL_17TYPEINFOLCSCOLOR, double pTC_DBL_18TYPEINFOLCSCOLOR,
			double pTC_DBL_19TYPEINFOLCSCOLOR, double pTC_DBL_20TYPEINFOLCSCOLOR, String pTC_STR_1TYPEINFOLCSCOLOR,
			String pTC_STR_2TYPEINFOLCSCOLOR, String pTC_STR_3TYPEINFOLCSCOLOR, String pTC_STR_4TYPEINFOLCSCOLOR,
			String pTC_STR_5TYPEINFOLCSCOLOR, String pTC_STR_6TYPEINFOLCSCOLOR, String pTC_STR_7TYPEINFOLCSCOLOR,
			String pTC_STR_8TYPEINFOLCSCOLOR, String pTC_STR_9TYPEINFOLCSCOLOR, String pTC_STR_10TYPEINFOLCSCOLOR,
			String pTC_STR_11TYPEINFOLCSCOLOR, String pTC_STR_12TYPEINFOLCSCOLOR, String pTC_STR_13TYPEINFOLCSCOLOR,
			String pTC_STR_14TYPEINFOLCSCOLOR, String pTC_STR_15TYPEINFOLCSCOLOR, String pTC_STR_16TYPEINFOLCSCOLOR,
			String pTC_STR_17TYPEINFOLCSCOLOR, String pTC_STR_18TYPEINFOLCSCOLOR, String pTC_STR_19TYPEINFOLCSCOLOR,
			String pTC_STR_20TYPEINFOLCSCOLOR, String pTC_STR_21TYPEINFOLCSCOLOR, String pTC_STR_22TYPEINFOLCSCOLOR,
			String pTC_STR_23TYPEINFOLCSCOLOR, String pTC_STR_24TYPEINFOLCSCOLOR, String pTC_STR_25TYPEINFOLCSCOLOR,
			String pTC_STR_26TYPEINFOLCSCOLOR, String pTC_STR_27TYPEINFOLCSCOLOR, String pTC_STR_28TYPEINFOLCSCOLOR,
			String pTC_STR_29TYPEINFOLCSCOLOR, String pTC_STR_30TYPEINFOLCSCOLOR, String pTC_STR_31TYPEINFOLCSCOLOR,
			String pTC_STR_32TYPEINFOLCSCOLOR, String pTC_STR_33TYPEINFOLCSCOLOR, String pTC_STR_34TYPEINFOLCSCOLOR,
			String pTC_STR_35TYPEINFOLCSCOLOR, String pTC_STR_36TYPEINFOLCSCOLOR, String pTC_STR_37TYPEINFOLCSCOLOR,
			String pTC_STR_38TYPEINFOLCSCOLOR, String pTC_STR_39TYPEINFOLCSCOLOR, String pTC_STR_40TYPEINFOLCSCOLOR,
			String pTC_STR_41TYPEINFOLCSCOLOR, String pTC_STR_42TYPEINFOLCSCOLOR, String pTC_STR_43TYPEINFOLCSCOLOR,
			String pTC_STR_44TYPEINFOLCSCOLOR, String pTC_STR_45TYPEINFOLCSCOLOR, String pTC_STR_46TYPEINFOLCSCOLOR,
			String pTC_STR_47TYPEINFOLCSCOLOR, String pTC_STR_48TYPEINFOLCSCOLOR, String pTC_STR_49TYPEINFOLCSCOLOR,
			String pTC_STR_50TYPEINFOLCSCOLOR, String pTC_STR_51TYPEINFOLCSCOLOR, String pTC_STR_52TYPEINFOLCSCOLOR,
			String pTC_STR_53TYPEINFOLCSCOLOR, String pTC_STR_54TYPEINFOLCSCOLOR, String pTC_STR_55TYPEINFOLCSCOLOR,
			String pTC_STR_56TYPEINFOLCSCOLOR, String pTC_STR_57TYPEINFOLCSCOLOR, String pTC_STR_58TYPEINFOLCSCOLOR,
			String pTC_STR_59TYPEINFOLCSCOLOR, String pTC_STR_60TYPEINFOLCSCOLOR, String pTC_STR_61TYPEINFOLCSCOLOR,
			String pTC_STR_62TYPEINFOLCSCOLOR, String pTC_STR_63TYPEINFOLCSCOLOR, String pTC_STR_64TYPEINFOLCSCOLOR,
			String pTC_STR_65TYPEINFOLCSCOLOR, String pTC_STR_66TYPEINFOLCSCOLOR, String pTC_STR_67TYPEINFOLCSCOLOR,
			String pTC_STR_68TYPEINFOLCSCOLOR, String pTC_STR_69TYPEINFOLCSCOLOR, String pTC_STR_70TYPEINFOLCSCOLOR,
			String pTC_STR_71TYPEINFOLCSCOLOR, String pTC_STR_72TYPEINFOLCSCOLOR, String pTC_STR_73TYPEINFOLCSCOLOR,
			String pTC_STR_74TYPEINFOLCSCOLOR, String pTC_STR_75TYPEINFOLCSCOLOR, String pTC_STR_76TYPEINFOLCSCOLOR,
			String pTC_STR_77TYPEINFOLCSCOLOR, String pTC_STR_78TYPEINFOLCSCOLOR, String pTC_STR_79TYPEINFOLCSCOLOR,
			String pTC_STR_80TYPEINFOLCSCOLOR, String pTC_STR_81TYPEINFOLCSCOLOR, String pTC_STR_82TYPEINFOLCSCOLOR,
			String pTC_STR_83TYPEINFOLCSCOLOR, String pTC_STR_84TYPEINFOLCSCOLOR, String pTC_STR_85TYPEINFOLCSCOLOR,
			String pTC_STR_86TYPEINFOLCSCOLOR, String pTC_STR_87TYPEINFOLCSCOLOR, String pTC_STR_88TYPEINFOLCSCOLOR,
			String pTC_STR_89TYPEINFOLCSCOLOR, String pTC_STR_90TYPEINFOLCSCOLOR, String pTC_STR_91TYPEINFOLCSCOLOR,
			String pTC_STR_92TYPEINFOLCSCOLOR, String pTC_STR_93TYPEINFOLCSCOLOR, String pTC_STR_94TYPEINFOLCSCOLOR,
			String pTC_STR_95TYPEINFOLCSCOLOR, String pTC_STR_96TYPEINFOLCSCOLOR, String pTC_STR_97TYPEINFOLCSCOLOR,
			String pTC_STR_98TYPEINFOLCSCOLOR, String pTC_STR_99TYPEINFOLCSCOLOR, String pTC_STR_100TYPEINFOLCSCOLOR,
			long pTC_LNG_1TYPEINFOLCSCOLOR, long pTC_LNG_2TYPEINFOLCSCOLOR, long pTC_LNG_3TYPEINFOLCSCOLOR,
			long pTC_LNG_4TYPEINFOLCSCOLOR, long pTC_LNG_5TYPEINFOLCSCOLOR, long pTC_LNG_6TYPEINFOLCSCOLOR,
			long pTC_LNG_7TYPEINFOLCSCOLOR, long pTC_LNG_8TYPEINFOLCSCOLOR, long pTC_LNG_9TYPEINFOLCSCOLOR,
			long pTC_LNG_10TYPEINFOLCSCOLOR, Date pTC_TMS_1TYPEINFOLCSCOLOR, Date pTC_TMS_2TYPEINFOLCSCOLOR,
			Date pTC_TMS_3TYPEINFOLCSCOLOR, Date pTC_TMS_4TYPEINFOLCSCOLOR, Date pTC_TMS_5TYPEINFOLCSCOLOR,
			Date pTC_TMS_6TYPEINFOLCSCOLOR, Date pTC_TMS_7TYPEINFOLCSCOLOR, Date pTC_TMS_8TYPEINFOLCSCOLOR,
			Date pTC_TMS_9TYPEINFOLCSCOLOR, Date pTC_TMS_10TYPEINFOLCSCOLOR, Date pTC_TMS_11TYPEINFOLCSCOLOR,
			Date pTC_TMS_12TYPEINFOLCSCOLOR, Date pTC_TMS_13TYPEINFOLCSCOLOR, Date pTC_TMS_14TYPEINFOLCSCOLOR,
			Date pTC_TMS_15TYPEINFOLCSCOLOR, Date pTC_TMS_16TYPEINFOLCSCOLOR, Date pTC_TMS_17TYPEINFOLCSCOLOR,
			Date pTC_TMS_18TYPEINFOLCSCOLOR, Date pTC_TMS_19TYPEINFOLCSCOLOR, Date pTC_TMS_20TYPEINFOLCSCOLOR,
			Date pTC_TMS_21TYPEINFOLCSCOLOR, Date pTC_TMS_22TYPEINFOLCSCOLOR, Date pTC_TMS_23TYPEINFOLCSCOLOR,
			Date pTC_TMS_24TYPEINFOLCSCOLOR, Date pTC_TMS_25TYPEINFOLCSCOLOR, Date pTC_TMS_26TYPEINFOLCSCOLOR,
			Date pTC_TMS_27TYPEINFOLCSCOLOR, Date pTC_TMS_28TYPEINFOLCSCOLOR, Date pTC_TMS_29TYPEINFOLCSCOLOR,
			Date pTC_TMS_30TYPEINFOLCSCOLOR, String pTC_BLN_1TYPEINFOLCSCOLOR, String pTC_BLN_2TYPEINFOLCSCOLOR,
			String pTC_BLN_3TYPEINFOLCSCOLOR, String pTC_BLN_4TYPEINFOLCSCOLOR, String pTC_BLN_5TYPEINFOLCSCOLOR,
			String pTC_BLN_6TYPEINFOLCSCOLOR, String pTC_BLN_7TYPEINFOLCSCOLOR, String pTC_BLN_8TYPEINFOLCSCOLOR,
			String pTC_BLN_9TYPEINFOLCSCOLOR, String pTC_BLN_10TYPEINFOLCSCOLOR) {
		super();
		this.primaryKey = primaryKey;
		BRANCHID = bRANCHID;
		CREATESTAMPA2 = cREATESTAMPA2;
		UPDATESTAMPA2 = uPDATESTAMPA2;
		FLEXTYPEIDPATH = fLEXTYPEIDPATH;
		FLEXTYPEID = fLEXTYPEID;
		COLORHEXIDECIMALVALUE = cOLORHEXIDECIMALVALUE;
		THUMBNAIL = tHUMBNAIL;
		COLORNAME = cOLORNAME;
		UPDATECOUNTA2 = uPDATECOUNTA2;
		MARKEDFORDELETEA2 = mARKEDFORDELETEA2;
		IDA2TYPEDEFINITIONREFERENCE = iDA2TYPEDEFINITIONREFERENCE;
		LOADERCREATESTAMP = lOADERCREATESTAMP;
		LOADERUPDATESTAMP = lOADERUPDATESTAMP;
		BRANCHIDA3E2TYPEINFOLCSCOLOR = bRANCHIDA3E2TYPEINFOLCSCOLOR;
		BRANCHIDA3D2TYPEINFOLCSCOLOR = bRANCHIDA3D2TYPEINFOLCSCOLOR;
		BRANCHIDA3C2TYPEINFOLCSCOLOR = bRANCHIDA3C2TYPEINFOLCSCOLOR;
		BRANCHIDA3B2TYPEINFOLCSCOLOR = bRANCHIDA3B2TYPEINFOLCSCOLOR;
		BRANCHIDA3A2TYPEINFOLCSCOLOR = bRANCHIDA3A2TYPEINFOLCSCOLOR;
		PTC_DBL_1TYPEINFOLCSCOLOR = pTC_DBL_1TYPEINFOLCSCOLOR;
		PTC_DBL_2TYPEINFOLCSCOLOR = pTC_DBL_2TYPEINFOLCSCOLOR;
		PTC_DBL_3TYPEINFOLCSCOLOR = pTC_DBL_3TYPEINFOLCSCOLOR;
		PTC_DBL_4TYPEINFOLCSCOLOR = pTC_DBL_4TYPEINFOLCSCOLOR;
		PTC_DBL_5TYPEINFOLCSCOLOR = pTC_DBL_5TYPEINFOLCSCOLOR;
		PTC_DBL_6TYPEINFOLCSCOLOR = pTC_DBL_6TYPEINFOLCSCOLOR;
		PTC_DBL_7TYPEINFOLCSCOLOR = pTC_DBL_7TYPEINFOLCSCOLOR;
		PTC_DBL_8TYPEINFOLCSCOLOR = pTC_DBL_8TYPEINFOLCSCOLOR;
		PTC_DBL_9TYPEINFOLCSCOLOR = pTC_DBL_9TYPEINFOLCSCOLOR;
		PTC_DBL_10TYPEINFOLCSCOLOR = pTC_DBL_10TYPEINFOLCSCOLOR;
		PTC_DBL_11TYPEINFOLCSCOLOR = pTC_DBL_11TYPEINFOLCSCOLOR;
		PTC_DBL_12TYPEINFOLCSCOLOR = pTC_DBL_12TYPEINFOLCSCOLOR;
		PTC_DBL_13TYPEINFOLCSCOLOR = pTC_DBL_13TYPEINFOLCSCOLOR;
		PTC_DBL_14TYPEINFOLCSCOLOR = pTC_DBL_14TYPEINFOLCSCOLOR;
		PTC_DBL_15TYPEINFOLCSCOLOR = pTC_DBL_15TYPEINFOLCSCOLOR;
		PTC_DBL_16TYPEINFOLCSCOLOR = pTC_DBL_16TYPEINFOLCSCOLOR;
		PTC_DBL_17TYPEINFOLCSCOLOR = pTC_DBL_17TYPEINFOLCSCOLOR;
		PTC_DBL_18TYPEINFOLCSCOLOR = pTC_DBL_18TYPEINFOLCSCOLOR;
		PTC_DBL_19TYPEINFOLCSCOLOR = pTC_DBL_19TYPEINFOLCSCOLOR;
		PTC_DBL_20TYPEINFOLCSCOLOR = pTC_DBL_20TYPEINFOLCSCOLOR;
		PTC_STR_1TYPEINFOLCSCOLOR = pTC_STR_1TYPEINFOLCSCOLOR;
		PTC_STR_2TYPEINFOLCSCOLOR = pTC_STR_2TYPEINFOLCSCOLOR;
		PTC_STR_3TYPEINFOLCSCOLOR = pTC_STR_3TYPEINFOLCSCOLOR;
		PTC_STR_4TYPEINFOLCSCOLOR = pTC_STR_4TYPEINFOLCSCOLOR;
		PTC_STR_5TYPEINFOLCSCOLOR = pTC_STR_5TYPEINFOLCSCOLOR;
		PTC_STR_6TYPEINFOLCSCOLOR = pTC_STR_6TYPEINFOLCSCOLOR;
		PTC_STR_7TYPEINFOLCSCOLOR = pTC_STR_7TYPEINFOLCSCOLOR;
		PTC_STR_8TYPEINFOLCSCOLOR = pTC_STR_8TYPEINFOLCSCOLOR;
		PTC_STR_9TYPEINFOLCSCOLOR = pTC_STR_9TYPEINFOLCSCOLOR;
		PTC_STR_10TYPEINFOLCSCOLOR = pTC_STR_10TYPEINFOLCSCOLOR;
		PTC_STR_11TYPEINFOLCSCOLOR = pTC_STR_11TYPEINFOLCSCOLOR;
		PTC_STR_12TYPEINFOLCSCOLOR = pTC_STR_12TYPEINFOLCSCOLOR;
		PTC_STR_13TYPEINFOLCSCOLOR = pTC_STR_13TYPEINFOLCSCOLOR;
		PTC_STR_14TYPEINFOLCSCOLOR = pTC_STR_14TYPEINFOLCSCOLOR;
		PTC_STR_15TYPEINFOLCSCOLOR = pTC_STR_15TYPEINFOLCSCOLOR;
		PTC_STR_16TYPEINFOLCSCOLOR = pTC_STR_16TYPEINFOLCSCOLOR;
		PTC_STR_17TYPEINFOLCSCOLOR = pTC_STR_17TYPEINFOLCSCOLOR;
		PTC_STR_18TYPEINFOLCSCOLOR = pTC_STR_18TYPEINFOLCSCOLOR;
		PTC_STR_19TYPEINFOLCSCOLOR = pTC_STR_19TYPEINFOLCSCOLOR;
		PTC_STR_20TYPEINFOLCSCOLOR = pTC_STR_20TYPEINFOLCSCOLOR;
		PTC_STR_21TYPEINFOLCSCOLOR = pTC_STR_21TYPEINFOLCSCOLOR;
		PTC_STR_22TYPEINFOLCSCOLOR = pTC_STR_22TYPEINFOLCSCOLOR;
		PTC_STR_23TYPEINFOLCSCOLOR = pTC_STR_23TYPEINFOLCSCOLOR;
		PTC_STR_24TYPEINFOLCSCOLOR = pTC_STR_24TYPEINFOLCSCOLOR;
		PTC_STR_25TYPEINFOLCSCOLOR = pTC_STR_25TYPEINFOLCSCOLOR;
		PTC_STR_26TYPEINFOLCSCOLOR = pTC_STR_26TYPEINFOLCSCOLOR;
		PTC_STR_27TYPEINFOLCSCOLOR = pTC_STR_27TYPEINFOLCSCOLOR;
		PTC_STR_28TYPEINFOLCSCOLOR = pTC_STR_28TYPEINFOLCSCOLOR;
		PTC_STR_29TYPEINFOLCSCOLOR = pTC_STR_29TYPEINFOLCSCOLOR;
		PTC_STR_30TYPEINFOLCSCOLOR = pTC_STR_30TYPEINFOLCSCOLOR;
		PTC_STR_31TYPEINFOLCSCOLOR = pTC_STR_31TYPEINFOLCSCOLOR;
		PTC_STR_32TYPEINFOLCSCOLOR = pTC_STR_32TYPEINFOLCSCOLOR;
		PTC_STR_33TYPEINFOLCSCOLOR = pTC_STR_33TYPEINFOLCSCOLOR;
		PTC_STR_34TYPEINFOLCSCOLOR = pTC_STR_34TYPEINFOLCSCOLOR;
		PTC_STR_35TYPEINFOLCSCOLOR = pTC_STR_35TYPEINFOLCSCOLOR;
		PTC_STR_36TYPEINFOLCSCOLOR = pTC_STR_36TYPEINFOLCSCOLOR;
		PTC_STR_37TYPEINFOLCSCOLOR = pTC_STR_37TYPEINFOLCSCOLOR;
		PTC_STR_38TYPEINFOLCSCOLOR = pTC_STR_38TYPEINFOLCSCOLOR;
		PTC_STR_39TYPEINFOLCSCOLOR = pTC_STR_39TYPEINFOLCSCOLOR;
		PTC_STR_40TYPEINFOLCSCOLOR = pTC_STR_40TYPEINFOLCSCOLOR;
		PTC_STR_41TYPEINFOLCSCOLOR = pTC_STR_41TYPEINFOLCSCOLOR;
		PTC_STR_42TYPEINFOLCSCOLOR = pTC_STR_42TYPEINFOLCSCOLOR;
		PTC_STR_43TYPEINFOLCSCOLOR = pTC_STR_43TYPEINFOLCSCOLOR;
		PTC_STR_44TYPEINFOLCSCOLOR = pTC_STR_44TYPEINFOLCSCOLOR;
		PTC_STR_45TYPEINFOLCSCOLOR = pTC_STR_45TYPEINFOLCSCOLOR;
		PTC_STR_46TYPEINFOLCSCOLOR = pTC_STR_46TYPEINFOLCSCOLOR;
		PTC_STR_47TYPEINFOLCSCOLOR = pTC_STR_47TYPEINFOLCSCOLOR;
		PTC_STR_48TYPEINFOLCSCOLOR = pTC_STR_48TYPEINFOLCSCOLOR;
		PTC_STR_49TYPEINFOLCSCOLOR = pTC_STR_49TYPEINFOLCSCOLOR;
		PTC_STR_50TYPEINFOLCSCOLOR = pTC_STR_50TYPEINFOLCSCOLOR;
		PTC_STR_51TYPEINFOLCSCOLOR = pTC_STR_51TYPEINFOLCSCOLOR;
		PTC_STR_52TYPEINFOLCSCOLOR = pTC_STR_52TYPEINFOLCSCOLOR;
		PTC_STR_53TYPEINFOLCSCOLOR = pTC_STR_53TYPEINFOLCSCOLOR;
		PTC_STR_54TYPEINFOLCSCOLOR = pTC_STR_54TYPEINFOLCSCOLOR;
		PTC_STR_55TYPEINFOLCSCOLOR = pTC_STR_55TYPEINFOLCSCOLOR;
		PTC_STR_56TYPEINFOLCSCOLOR = pTC_STR_56TYPEINFOLCSCOLOR;
		PTC_STR_57TYPEINFOLCSCOLOR = pTC_STR_57TYPEINFOLCSCOLOR;
		PTC_STR_58TYPEINFOLCSCOLOR = pTC_STR_58TYPEINFOLCSCOLOR;
		PTC_STR_59TYPEINFOLCSCOLOR = pTC_STR_59TYPEINFOLCSCOLOR;
		PTC_STR_60TYPEINFOLCSCOLOR = pTC_STR_60TYPEINFOLCSCOLOR;
		PTC_STR_61TYPEINFOLCSCOLOR = pTC_STR_61TYPEINFOLCSCOLOR;
		PTC_STR_62TYPEINFOLCSCOLOR = pTC_STR_62TYPEINFOLCSCOLOR;
		PTC_STR_63TYPEINFOLCSCOLOR = pTC_STR_63TYPEINFOLCSCOLOR;
		PTC_STR_64TYPEINFOLCSCOLOR = pTC_STR_64TYPEINFOLCSCOLOR;
		PTC_STR_65TYPEINFOLCSCOLOR = pTC_STR_65TYPEINFOLCSCOLOR;
		PTC_STR_66TYPEINFOLCSCOLOR = pTC_STR_66TYPEINFOLCSCOLOR;
		PTC_STR_67TYPEINFOLCSCOLOR = pTC_STR_67TYPEINFOLCSCOLOR;
		PTC_STR_68TYPEINFOLCSCOLOR = pTC_STR_68TYPEINFOLCSCOLOR;
		PTC_STR_69TYPEINFOLCSCOLOR = pTC_STR_69TYPEINFOLCSCOLOR;
		PTC_STR_70TYPEINFOLCSCOLOR = pTC_STR_70TYPEINFOLCSCOLOR;
		PTC_STR_71TYPEINFOLCSCOLOR = pTC_STR_71TYPEINFOLCSCOLOR;
		PTC_STR_72TYPEINFOLCSCOLOR = pTC_STR_72TYPEINFOLCSCOLOR;
		PTC_STR_73TYPEINFOLCSCOLOR = pTC_STR_73TYPEINFOLCSCOLOR;
		PTC_STR_74TYPEINFOLCSCOLOR = pTC_STR_74TYPEINFOLCSCOLOR;
		PTC_STR_75TYPEINFOLCSCOLOR = pTC_STR_75TYPEINFOLCSCOLOR;
		PTC_STR_76TYPEINFOLCSCOLOR = pTC_STR_76TYPEINFOLCSCOLOR;
		PTC_STR_77TYPEINFOLCSCOLOR = pTC_STR_77TYPEINFOLCSCOLOR;
		PTC_STR_78TYPEINFOLCSCOLOR = pTC_STR_78TYPEINFOLCSCOLOR;
		PTC_STR_79TYPEINFOLCSCOLOR = pTC_STR_79TYPEINFOLCSCOLOR;
		PTC_STR_80TYPEINFOLCSCOLOR = pTC_STR_80TYPEINFOLCSCOLOR;
		PTC_STR_81TYPEINFOLCSCOLOR = pTC_STR_81TYPEINFOLCSCOLOR;
		PTC_STR_82TYPEINFOLCSCOLOR = pTC_STR_82TYPEINFOLCSCOLOR;
		PTC_STR_83TYPEINFOLCSCOLOR = pTC_STR_83TYPEINFOLCSCOLOR;
		PTC_STR_84TYPEINFOLCSCOLOR = pTC_STR_84TYPEINFOLCSCOLOR;
		PTC_STR_85TYPEINFOLCSCOLOR = pTC_STR_85TYPEINFOLCSCOLOR;
		PTC_STR_86TYPEINFOLCSCOLOR = pTC_STR_86TYPEINFOLCSCOLOR;
		PTC_STR_87TYPEINFOLCSCOLOR = pTC_STR_87TYPEINFOLCSCOLOR;
		PTC_STR_88TYPEINFOLCSCOLOR = pTC_STR_88TYPEINFOLCSCOLOR;
		PTC_STR_89TYPEINFOLCSCOLOR = pTC_STR_89TYPEINFOLCSCOLOR;
		PTC_STR_90TYPEINFOLCSCOLOR = pTC_STR_90TYPEINFOLCSCOLOR;
		PTC_STR_91TYPEINFOLCSCOLOR = pTC_STR_91TYPEINFOLCSCOLOR;
		PTC_STR_92TYPEINFOLCSCOLOR = pTC_STR_92TYPEINFOLCSCOLOR;
		PTC_STR_93TYPEINFOLCSCOLOR = pTC_STR_93TYPEINFOLCSCOLOR;
		PTC_STR_94TYPEINFOLCSCOLOR = pTC_STR_94TYPEINFOLCSCOLOR;
		PTC_STR_95TYPEINFOLCSCOLOR = pTC_STR_95TYPEINFOLCSCOLOR;
		PTC_STR_96TYPEINFOLCSCOLOR = pTC_STR_96TYPEINFOLCSCOLOR;
		PTC_STR_97TYPEINFOLCSCOLOR = pTC_STR_97TYPEINFOLCSCOLOR;
		PTC_STR_98TYPEINFOLCSCOLOR = pTC_STR_98TYPEINFOLCSCOLOR;
		PTC_STR_99TYPEINFOLCSCOLOR = pTC_STR_99TYPEINFOLCSCOLOR;
		PTC_STR_100TYPEINFOLCSCOLOR = pTC_STR_100TYPEINFOLCSCOLOR;
		PTC_LNG_1TYPEINFOLCSCOLOR = pTC_LNG_1TYPEINFOLCSCOLOR;
		PTC_LNG_2TYPEINFOLCSCOLOR = pTC_LNG_2TYPEINFOLCSCOLOR;
		PTC_LNG_3TYPEINFOLCSCOLOR = pTC_LNG_3TYPEINFOLCSCOLOR;
		PTC_LNG_4TYPEINFOLCSCOLOR = pTC_LNG_4TYPEINFOLCSCOLOR;
		PTC_LNG_5TYPEINFOLCSCOLOR = pTC_LNG_5TYPEINFOLCSCOLOR;
		PTC_LNG_6TYPEINFOLCSCOLOR = pTC_LNG_6TYPEINFOLCSCOLOR;
		PTC_LNG_7TYPEINFOLCSCOLOR = pTC_LNG_7TYPEINFOLCSCOLOR;
		PTC_LNG_8TYPEINFOLCSCOLOR = pTC_LNG_8TYPEINFOLCSCOLOR;
		PTC_LNG_9TYPEINFOLCSCOLOR = pTC_LNG_9TYPEINFOLCSCOLOR;
		PTC_LNG_10TYPEINFOLCSCOLOR = pTC_LNG_10TYPEINFOLCSCOLOR;
		PTC_TMS_1TYPEINFOLCSCOLOR = pTC_TMS_1TYPEINFOLCSCOLOR;
		PTC_TMS_2TYPEINFOLCSCOLOR = pTC_TMS_2TYPEINFOLCSCOLOR;
		PTC_TMS_3TYPEINFOLCSCOLOR = pTC_TMS_3TYPEINFOLCSCOLOR;
		PTC_TMS_4TYPEINFOLCSCOLOR = pTC_TMS_4TYPEINFOLCSCOLOR;
		PTC_TMS_5TYPEINFOLCSCOLOR = pTC_TMS_5TYPEINFOLCSCOLOR;
		PTC_TMS_6TYPEINFOLCSCOLOR = pTC_TMS_6TYPEINFOLCSCOLOR;
		PTC_TMS_7TYPEINFOLCSCOLOR = pTC_TMS_7TYPEINFOLCSCOLOR;
		PTC_TMS_8TYPEINFOLCSCOLOR = pTC_TMS_8TYPEINFOLCSCOLOR;
		PTC_TMS_9TYPEINFOLCSCOLOR = pTC_TMS_9TYPEINFOLCSCOLOR;
		PTC_TMS_10TYPEINFOLCSCOLOR = pTC_TMS_10TYPEINFOLCSCOLOR;
		PTC_TMS_11TYPEINFOLCSCOLOR = pTC_TMS_11TYPEINFOLCSCOLOR;
		PTC_TMS_12TYPEINFOLCSCOLOR = pTC_TMS_12TYPEINFOLCSCOLOR;
		PTC_TMS_13TYPEINFOLCSCOLOR = pTC_TMS_13TYPEINFOLCSCOLOR;
		PTC_TMS_14TYPEINFOLCSCOLOR = pTC_TMS_14TYPEINFOLCSCOLOR;
		PTC_TMS_15TYPEINFOLCSCOLOR = pTC_TMS_15TYPEINFOLCSCOLOR;
		PTC_TMS_16TYPEINFOLCSCOLOR = pTC_TMS_16TYPEINFOLCSCOLOR;
		PTC_TMS_17TYPEINFOLCSCOLOR = pTC_TMS_17TYPEINFOLCSCOLOR;
		PTC_TMS_18TYPEINFOLCSCOLOR = pTC_TMS_18TYPEINFOLCSCOLOR;
		PTC_TMS_19TYPEINFOLCSCOLOR = pTC_TMS_19TYPEINFOLCSCOLOR;
		PTC_TMS_20TYPEINFOLCSCOLOR = pTC_TMS_20TYPEINFOLCSCOLOR;
		PTC_TMS_21TYPEINFOLCSCOLOR = pTC_TMS_21TYPEINFOLCSCOLOR;
		PTC_TMS_22TYPEINFOLCSCOLOR = pTC_TMS_22TYPEINFOLCSCOLOR;
		PTC_TMS_23TYPEINFOLCSCOLOR = pTC_TMS_23TYPEINFOLCSCOLOR;
		PTC_TMS_24TYPEINFOLCSCOLOR = pTC_TMS_24TYPEINFOLCSCOLOR;
		PTC_TMS_25TYPEINFOLCSCOLOR = pTC_TMS_25TYPEINFOLCSCOLOR;
		PTC_TMS_26TYPEINFOLCSCOLOR = pTC_TMS_26TYPEINFOLCSCOLOR;
		PTC_TMS_27TYPEINFOLCSCOLOR = pTC_TMS_27TYPEINFOLCSCOLOR;
		PTC_TMS_28TYPEINFOLCSCOLOR = pTC_TMS_28TYPEINFOLCSCOLOR;
		PTC_TMS_29TYPEINFOLCSCOLOR = pTC_TMS_29TYPEINFOLCSCOLOR;
		PTC_TMS_30TYPEINFOLCSCOLOR = pTC_TMS_30TYPEINFOLCSCOLOR;
		PTC_BLN_1TYPEINFOLCSCOLOR = pTC_BLN_1TYPEINFOLCSCOLOR;
		PTC_BLN_2TYPEINFOLCSCOLOR = pTC_BLN_2TYPEINFOLCSCOLOR;
		PTC_BLN_3TYPEINFOLCSCOLOR = pTC_BLN_3TYPEINFOLCSCOLOR;
		PTC_BLN_4TYPEINFOLCSCOLOR = pTC_BLN_4TYPEINFOLCSCOLOR;
		PTC_BLN_5TYPEINFOLCSCOLOR = pTC_BLN_5TYPEINFOLCSCOLOR;
		PTC_BLN_6TYPEINFOLCSCOLOR = pTC_BLN_6TYPEINFOLCSCOLOR;
		PTC_BLN_7TYPEINFOLCSCOLOR = pTC_BLN_7TYPEINFOLCSCOLOR;
		PTC_BLN_8TYPEINFOLCSCOLOR = pTC_BLN_8TYPEINFOLCSCOLOR;
		PTC_BLN_9TYPEINFOLCSCOLOR = pTC_BLN_9TYPEINFOLCSCOLOR;
		PTC_BLN_10TYPEINFOLCSCOLOR = pTC_BLN_10TYPEINFOLCSCOLOR;
	}



	public int getPrimaryKey() {
		return primaryKey;
	}
	public void setPrimaryKey(int primaryKey) {
		this.primaryKey = primaryKey;
	}
	public int getBRANCHID() {
		return BRANCHID;
	}
	public void setBRANCHID(int bRANCHID) {
		BRANCHID = bRANCHID;
	}
	public Date getCREATESTAMPA2() {
		return CREATESTAMPA2;
	}
	public void setCREATESTAMPA2(Date cREATESTAMPA2) {
		CREATESTAMPA2 = cREATESTAMPA2;
	}
	public Date getUPDATESTAMPA2() {
		return UPDATESTAMPA2;
	}
	public void setUPDATESTAMPA2(Date uPDATESTAMPA2) {
		UPDATESTAMPA2 = uPDATESTAMPA2;
	}
	public String getFLEXTYPEIDPATH() {
		return FLEXTYPEIDPATH;
	}
	public void setFLEXTYPEIDPATH(String fLEXTYPEIDPATH) {
		FLEXTYPEIDPATH = fLEXTYPEIDPATH;
	}
	public int getFLEXTYPEID() {
		return FLEXTYPEID;
	}
	public void setFLEXTYPEID(int fLEXTYPEID) {
		FLEXTYPEID = fLEXTYPEID;
	}
	public String getCOLORHEXIDECIMALVALUE() {
		return COLORHEXIDECIMALVALUE;
	}
	public void setCOLORHEXIDECIMALVALUE(String cOLORHEXIDECIMALVALUE) {
		COLORHEXIDECIMALVALUE = cOLORHEXIDECIMALVALUE;
	}
	public String getTHUMBNAIL() {
		return THUMBNAIL;
	}
	public void setTHUMBNAIL(String tHUMBNAIL) {
		THUMBNAIL = tHUMBNAIL;
	}
	public String getCOLORNAME() {
		return COLORNAME;
	}
	public void setCOLORNAME(String cOLORNAME) {
		COLORNAME = cOLORNAME;
	}
	public int getUPDATECOUNTA2() {
		return UPDATECOUNTA2;
	}
	public void setUPDATECOUNTA2(int uPDATECOUNTA2) {
		UPDATECOUNTA2 = uPDATECOUNTA2;
	}
	public int getMARKEDFORDELETEA2() {
		return MARKEDFORDELETEA2;
	}
	public void setMARKEDFORDELETEA2(int mARKEDFORDELETEA2) {
		MARKEDFORDELETEA2 = mARKEDFORDELETEA2;
	}
	public int getIDA2TYPEDEFINITIONREFERENCE() {
		return IDA2TYPEDEFINITIONREFERENCE;
	}
	public void setIDA2TYPEDEFINITIONREFERENCE(int iDA2TYPEDEFINITIONREFERENCE) {
		IDA2TYPEDEFINITIONREFERENCE = iDA2TYPEDEFINITIONREFERENCE;
	}
	public Timestamp getLOADERCREATESTAMP() {
		return LOADERCREATESTAMP;
	}
	public void setLOADERCREATESTAMP(Timestamp lOADERCREATESTAMP) {
		LOADERCREATESTAMP = lOADERCREATESTAMP;
	}
	public Timestamp getLOADERUPDATESTAMP() {
		return LOADERUPDATESTAMP;
	}
	public void setLOADERUPDATESTAMP(Timestamp lOADERUPDATESTAMP) {
		LOADERUPDATESTAMP = lOADERUPDATESTAMP;
	}
	public int getBRANCHIDA3E2TYPEINFOLCSCOLOR() {
		return BRANCHIDA3E2TYPEINFOLCSCOLOR;
	}
	public void setBRANCHIDA3E2TYPEINFOLCSCOLOR(int bRANCHIDA3E2TYPEINFOLCSCOLOR) {
		BRANCHIDA3E2TYPEINFOLCSCOLOR = bRANCHIDA3E2TYPEINFOLCSCOLOR;
	}
	public int getBRANCHIDA3D2TYPEINFOLCSCOLOR() {
		return BRANCHIDA3D2TYPEINFOLCSCOLOR;
	}
	public void setBRANCHIDA3D2TYPEINFOLCSCOLOR(int bRANCHIDA3D2TYPEINFOLCSCOLOR) {
		BRANCHIDA3D2TYPEINFOLCSCOLOR = bRANCHIDA3D2TYPEINFOLCSCOLOR;
	}
	public int getBRANCHIDA3C2TYPEINFOLCSCOLOR() {
		return BRANCHIDA3C2TYPEINFOLCSCOLOR;
	}
	public void setBRANCHIDA3C2TYPEINFOLCSCOLOR(int bRANCHIDA3C2TYPEINFOLCSCOLOR) {
		BRANCHIDA3C2TYPEINFOLCSCOLOR = bRANCHIDA3C2TYPEINFOLCSCOLOR;
	}
	public int getBRANCHIDA3B2TYPEINFOLCSCOLOR() {
		return BRANCHIDA3B2TYPEINFOLCSCOLOR;
	}
	public void setBRANCHIDA3B2TYPEINFOLCSCOLOR(int bRANCHIDA3B2TYPEINFOLCSCOLOR) {
		BRANCHIDA3B2TYPEINFOLCSCOLOR = bRANCHIDA3B2TYPEINFOLCSCOLOR;
	}
	public int getBRANCHIDA3A2TYPEINFOLCSCOLOR() {
		return BRANCHIDA3A2TYPEINFOLCSCOLOR;
	}
	public void setBRANCHIDA3A2TYPEINFOLCSCOLOR(int bRANCHIDA3A2TYPEINFOLCSCOLOR) {
		BRANCHIDA3A2TYPEINFOLCSCOLOR = bRANCHIDA3A2TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_1TYPEINFOLCSCOLOR() {
		return PTC_DBL_1TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_1TYPEINFOLCSCOLOR(double pTC_DBL_1TYPEINFOLCSCOLOR) {
		PTC_DBL_1TYPEINFOLCSCOLOR = pTC_DBL_1TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_2TYPEINFOLCSCOLOR() {
		return PTC_DBL_2TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_2TYPEINFOLCSCOLOR(double pTC_DBL_2TYPEINFOLCSCOLOR) {
		PTC_DBL_2TYPEINFOLCSCOLOR = pTC_DBL_2TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_3TYPEINFOLCSCOLOR() {
		return PTC_DBL_3TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_3TYPEINFOLCSCOLOR(double pTC_DBL_3TYPEINFOLCSCOLOR) {
		PTC_DBL_3TYPEINFOLCSCOLOR = pTC_DBL_3TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_4TYPEINFOLCSCOLOR() {
		return PTC_DBL_4TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_4TYPEINFOLCSCOLOR(double pTC_DBL_4TYPEINFOLCSCOLOR) {
		PTC_DBL_4TYPEINFOLCSCOLOR = pTC_DBL_4TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_5TYPEINFOLCSCOLOR() {
		return PTC_DBL_5TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_5TYPEINFOLCSCOLOR(double pTC_DBL_5TYPEINFOLCSCOLOR) {
		PTC_DBL_5TYPEINFOLCSCOLOR = pTC_DBL_5TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_6TYPEINFOLCSCOLOR() {
		return PTC_DBL_6TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_6TYPEINFOLCSCOLOR(double pTC_DBL_6TYPEINFOLCSCOLOR) {
		PTC_DBL_6TYPEINFOLCSCOLOR = pTC_DBL_6TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_7TYPEINFOLCSCOLOR() {
		return PTC_DBL_7TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_7TYPEINFOLCSCOLOR(double pTC_DBL_7TYPEINFOLCSCOLOR) {
		PTC_DBL_7TYPEINFOLCSCOLOR = pTC_DBL_7TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_8TYPEINFOLCSCOLOR() {
		return PTC_DBL_8TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_8TYPEINFOLCSCOLOR(double pTC_DBL_8TYPEINFOLCSCOLOR) {
		PTC_DBL_8TYPEINFOLCSCOLOR = pTC_DBL_8TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_9TYPEINFOLCSCOLOR() {
		return PTC_DBL_9TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_9TYPEINFOLCSCOLOR(double pTC_DBL_9TYPEINFOLCSCOLOR) {
		PTC_DBL_9TYPEINFOLCSCOLOR = pTC_DBL_9TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_10TYPEINFOLCSCOLOR() {
		return PTC_DBL_10TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_10TYPEINFOLCSCOLOR(double pTC_DBL_10TYPEINFOLCSCOLOR) {
		PTC_DBL_10TYPEINFOLCSCOLOR = pTC_DBL_10TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_11TYPEINFOLCSCOLOR() {
		return PTC_DBL_11TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_11TYPEINFOLCSCOLOR(double pTC_DBL_11TYPEINFOLCSCOLOR) {
		PTC_DBL_11TYPEINFOLCSCOLOR = pTC_DBL_11TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_12TYPEINFOLCSCOLOR() {
		return PTC_DBL_12TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_12TYPEINFOLCSCOLOR(double pTC_DBL_12TYPEINFOLCSCOLOR) {
		PTC_DBL_12TYPEINFOLCSCOLOR = pTC_DBL_12TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_13TYPEINFOLCSCOLOR() {
		return PTC_DBL_13TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_13TYPEINFOLCSCOLOR(double pTC_DBL_13TYPEINFOLCSCOLOR) {
		PTC_DBL_13TYPEINFOLCSCOLOR = pTC_DBL_13TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_14TYPEINFOLCSCOLOR() {
		return PTC_DBL_14TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_14TYPEINFOLCSCOLOR(double pTC_DBL_14TYPEINFOLCSCOLOR) {
		PTC_DBL_14TYPEINFOLCSCOLOR = pTC_DBL_14TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_15TYPEINFOLCSCOLOR() {
		return PTC_DBL_15TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_15TYPEINFOLCSCOLOR(double pTC_DBL_15TYPEINFOLCSCOLOR) {
		PTC_DBL_15TYPEINFOLCSCOLOR = pTC_DBL_15TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_16TYPEINFOLCSCOLOR() {
		return PTC_DBL_16TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_16TYPEINFOLCSCOLOR(double pTC_DBL_16TYPEINFOLCSCOLOR) {
		PTC_DBL_16TYPEINFOLCSCOLOR = pTC_DBL_16TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_17TYPEINFOLCSCOLOR() {
		return PTC_DBL_17TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_17TYPEINFOLCSCOLOR(double pTC_DBL_17TYPEINFOLCSCOLOR) {
		PTC_DBL_17TYPEINFOLCSCOLOR = pTC_DBL_17TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_18TYPEINFOLCSCOLOR() {
		return PTC_DBL_18TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_18TYPEINFOLCSCOLOR(double pTC_DBL_18TYPEINFOLCSCOLOR) {
		PTC_DBL_18TYPEINFOLCSCOLOR = pTC_DBL_18TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_19TYPEINFOLCSCOLOR() {
		return PTC_DBL_19TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_19TYPEINFOLCSCOLOR(double pTC_DBL_19TYPEINFOLCSCOLOR) {
		PTC_DBL_19TYPEINFOLCSCOLOR = pTC_DBL_19TYPEINFOLCSCOLOR;
	}
	public double getPTC_DBL_20TYPEINFOLCSCOLOR() {
		return PTC_DBL_20TYPEINFOLCSCOLOR;
	}
	public void setPTC_DBL_20TYPEINFOLCSCOLOR(double pTC_DBL_20TYPEINFOLCSCOLOR) {
		PTC_DBL_20TYPEINFOLCSCOLOR = pTC_DBL_20TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_1TYPEINFOLCSCOLOR() {
		return PTC_STR_1TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_1TYPEINFOLCSCOLOR(String pTC_STR_1TYPEINFOLCSCOLOR) {
		PTC_STR_1TYPEINFOLCSCOLOR = pTC_STR_1TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_2TYPEINFOLCSCOLOR() {
		return PTC_STR_2TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_2TYPEINFOLCSCOLOR(String pTC_STR_2TYPEINFOLCSCOLOR) {
		PTC_STR_2TYPEINFOLCSCOLOR = pTC_STR_2TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_3TYPEINFOLCSCOLOR() {
		return PTC_STR_3TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_3TYPEINFOLCSCOLOR(String pTC_STR_3TYPEINFOLCSCOLOR) {
		PTC_STR_3TYPEINFOLCSCOLOR = pTC_STR_3TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_4TYPEINFOLCSCOLOR() {
		return PTC_STR_4TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_4TYPEINFOLCSCOLOR(String pTC_STR_4TYPEINFOLCSCOLOR) {
		PTC_STR_4TYPEINFOLCSCOLOR = pTC_STR_4TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_5TYPEINFOLCSCOLOR() {
		return PTC_STR_5TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_5TYPEINFOLCSCOLOR(String pTC_STR_5TYPEINFOLCSCOLOR) {
		PTC_STR_5TYPEINFOLCSCOLOR = pTC_STR_5TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_6TYPEINFOLCSCOLOR() {
		return PTC_STR_6TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_6TYPEINFOLCSCOLOR(String pTC_STR_6TYPEINFOLCSCOLOR) {
		PTC_STR_6TYPEINFOLCSCOLOR = pTC_STR_6TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_7TYPEINFOLCSCOLOR() {
		return PTC_STR_7TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_7TYPEINFOLCSCOLOR(String pTC_STR_7TYPEINFOLCSCOLOR) {
		PTC_STR_7TYPEINFOLCSCOLOR = pTC_STR_7TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_8TYPEINFOLCSCOLOR() {
		return PTC_STR_8TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_8TYPEINFOLCSCOLOR(String pTC_STR_8TYPEINFOLCSCOLOR) {
		PTC_STR_8TYPEINFOLCSCOLOR = pTC_STR_8TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_9TYPEINFOLCSCOLOR() {
		return PTC_STR_9TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_9TYPEINFOLCSCOLOR(String pTC_STR_9TYPEINFOLCSCOLOR) {
		PTC_STR_9TYPEINFOLCSCOLOR = pTC_STR_9TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_10TYPEINFOLCSCOLOR() {
		return PTC_STR_10TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_10TYPEINFOLCSCOLOR(String pTC_STR_10TYPEINFOLCSCOLOR) {
		PTC_STR_10TYPEINFOLCSCOLOR = pTC_STR_10TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_11TYPEINFOLCSCOLOR() {
		return PTC_STR_11TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_11TYPEINFOLCSCOLOR(String pTC_STR_11TYPEINFOLCSCOLOR) {
		PTC_STR_11TYPEINFOLCSCOLOR = pTC_STR_11TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_12TYPEINFOLCSCOLOR() {
		return PTC_STR_12TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_12TYPEINFOLCSCOLOR(String pTC_STR_12TYPEINFOLCSCOLOR) {
		PTC_STR_12TYPEINFOLCSCOLOR = pTC_STR_12TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_13TYPEINFOLCSCOLOR() {
		return PTC_STR_13TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_13TYPEINFOLCSCOLOR(String pTC_STR_13TYPEINFOLCSCOLOR) {
		PTC_STR_13TYPEINFOLCSCOLOR = pTC_STR_13TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_14TYPEINFOLCSCOLOR() {
		return PTC_STR_14TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_14TYPEINFOLCSCOLOR(String pTC_STR_14TYPEINFOLCSCOLOR) {
		PTC_STR_14TYPEINFOLCSCOLOR = pTC_STR_14TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_15TYPEINFOLCSCOLOR() {
		return PTC_STR_15TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_15TYPEINFOLCSCOLOR(String pTC_STR_15TYPEINFOLCSCOLOR) {
		PTC_STR_15TYPEINFOLCSCOLOR = pTC_STR_15TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_16TYPEINFOLCSCOLOR() {
		return PTC_STR_16TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_16TYPEINFOLCSCOLOR(String pTC_STR_16TYPEINFOLCSCOLOR) {
		PTC_STR_16TYPEINFOLCSCOLOR = pTC_STR_16TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_17TYPEINFOLCSCOLOR() {
		return PTC_STR_17TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_17TYPEINFOLCSCOLOR(String pTC_STR_17TYPEINFOLCSCOLOR) {
		PTC_STR_17TYPEINFOLCSCOLOR = pTC_STR_17TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_18TYPEINFOLCSCOLOR() {
		return PTC_STR_18TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_18TYPEINFOLCSCOLOR(String pTC_STR_18TYPEINFOLCSCOLOR) {
		PTC_STR_18TYPEINFOLCSCOLOR = pTC_STR_18TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_19TYPEINFOLCSCOLOR() {
		return PTC_STR_19TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_19TYPEINFOLCSCOLOR(String pTC_STR_19TYPEINFOLCSCOLOR) {
		PTC_STR_19TYPEINFOLCSCOLOR = pTC_STR_19TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_20TYPEINFOLCSCOLOR() {
		return PTC_STR_20TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_20TYPEINFOLCSCOLOR(String pTC_STR_20TYPEINFOLCSCOLOR) {
		PTC_STR_20TYPEINFOLCSCOLOR = pTC_STR_20TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_21TYPEINFOLCSCOLOR() {
		return PTC_STR_21TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_21TYPEINFOLCSCOLOR(String pTC_STR_21TYPEINFOLCSCOLOR) {
		PTC_STR_21TYPEINFOLCSCOLOR = pTC_STR_21TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_22TYPEINFOLCSCOLOR() {
		return PTC_STR_22TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_22TYPEINFOLCSCOLOR(String pTC_STR_22TYPEINFOLCSCOLOR) {
		PTC_STR_22TYPEINFOLCSCOLOR = pTC_STR_22TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_23TYPEINFOLCSCOLOR() {
		return PTC_STR_23TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_23TYPEINFOLCSCOLOR(String pTC_STR_23TYPEINFOLCSCOLOR) {
		PTC_STR_23TYPEINFOLCSCOLOR = pTC_STR_23TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_24TYPEINFOLCSCOLOR() {
		return PTC_STR_24TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_24TYPEINFOLCSCOLOR(String pTC_STR_24TYPEINFOLCSCOLOR) {
		PTC_STR_24TYPEINFOLCSCOLOR = pTC_STR_24TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_25TYPEINFOLCSCOLOR() {
		return PTC_STR_25TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_25TYPEINFOLCSCOLOR(String pTC_STR_25TYPEINFOLCSCOLOR) {
		PTC_STR_25TYPEINFOLCSCOLOR = pTC_STR_25TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_26TYPEINFOLCSCOLOR() {
		return PTC_STR_26TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_26TYPEINFOLCSCOLOR(String pTC_STR_26TYPEINFOLCSCOLOR) {
		PTC_STR_26TYPEINFOLCSCOLOR = pTC_STR_26TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_27TYPEINFOLCSCOLOR() {
		return PTC_STR_27TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_27TYPEINFOLCSCOLOR(String pTC_STR_27TYPEINFOLCSCOLOR) {
		PTC_STR_27TYPEINFOLCSCOLOR = pTC_STR_27TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_28TYPEINFOLCSCOLOR() {
		return PTC_STR_28TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_28TYPEINFOLCSCOLOR(String pTC_STR_28TYPEINFOLCSCOLOR) {
		PTC_STR_28TYPEINFOLCSCOLOR = pTC_STR_28TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_29TYPEINFOLCSCOLOR() {
		return PTC_STR_29TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_29TYPEINFOLCSCOLOR(String pTC_STR_29TYPEINFOLCSCOLOR) {
		PTC_STR_29TYPEINFOLCSCOLOR = pTC_STR_29TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_30TYPEINFOLCSCOLOR() {
		return PTC_STR_30TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_30TYPEINFOLCSCOLOR(String pTC_STR_30TYPEINFOLCSCOLOR) {
		PTC_STR_30TYPEINFOLCSCOLOR = pTC_STR_30TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_31TYPEINFOLCSCOLOR() {
		return PTC_STR_31TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_31TYPEINFOLCSCOLOR(String pTC_STR_31TYPEINFOLCSCOLOR) {
		PTC_STR_31TYPEINFOLCSCOLOR = pTC_STR_31TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_32TYPEINFOLCSCOLOR() {
		return PTC_STR_32TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_32TYPEINFOLCSCOLOR(String pTC_STR_32TYPEINFOLCSCOLOR) {
		PTC_STR_32TYPEINFOLCSCOLOR = pTC_STR_32TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_33TYPEINFOLCSCOLOR() {
		return PTC_STR_33TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_33TYPEINFOLCSCOLOR(String pTC_STR_33TYPEINFOLCSCOLOR) {
		PTC_STR_33TYPEINFOLCSCOLOR = pTC_STR_33TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_34TYPEINFOLCSCOLOR() {
		return PTC_STR_34TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_34TYPEINFOLCSCOLOR(String pTC_STR_34TYPEINFOLCSCOLOR) {
		PTC_STR_34TYPEINFOLCSCOLOR = pTC_STR_34TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_35TYPEINFOLCSCOLOR() {
		return PTC_STR_35TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_35TYPEINFOLCSCOLOR(String pTC_STR_35TYPEINFOLCSCOLOR) {
		PTC_STR_35TYPEINFOLCSCOLOR = pTC_STR_35TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_36TYPEINFOLCSCOLOR() {
		return PTC_STR_36TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_36TYPEINFOLCSCOLOR(String pTC_STR_36TYPEINFOLCSCOLOR) {
		PTC_STR_36TYPEINFOLCSCOLOR = pTC_STR_36TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_37TYPEINFOLCSCOLOR() {
		return PTC_STR_37TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_37TYPEINFOLCSCOLOR(String pTC_STR_37TYPEINFOLCSCOLOR) {
		PTC_STR_37TYPEINFOLCSCOLOR = pTC_STR_37TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_38TYPEINFOLCSCOLOR() {
		return PTC_STR_38TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_38TYPEINFOLCSCOLOR(String pTC_STR_38TYPEINFOLCSCOLOR) {
		PTC_STR_38TYPEINFOLCSCOLOR = pTC_STR_38TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_39TYPEINFOLCSCOLOR() {
		return PTC_STR_39TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_39TYPEINFOLCSCOLOR(String pTC_STR_39TYPEINFOLCSCOLOR) {
		PTC_STR_39TYPEINFOLCSCOLOR = pTC_STR_39TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_40TYPEINFOLCSCOLOR() {
		return PTC_STR_40TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_40TYPEINFOLCSCOLOR(String pTC_STR_40TYPEINFOLCSCOLOR) {
		PTC_STR_40TYPEINFOLCSCOLOR = pTC_STR_40TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_41TYPEINFOLCSCOLOR() {
		return PTC_STR_41TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_41TYPEINFOLCSCOLOR(String pTC_STR_41TYPEINFOLCSCOLOR) {
		PTC_STR_41TYPEINFOLCSCOLOR = pTC_STR_41TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_42TYPEINFOLCSCOLOR() {
		return PTC_STR_42TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_42TYPEINFOLCSCOLOR(String pTC_STR_42TYPEINFOLCSCOLOR) {
		PTC_STR_42TYPEINFOLCSCOLOR = pTC_STR_42TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_43TYPEINFOLCSCOLOR() {
		return PTC_STR_43TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_43TYPEINFOLCSCOLOR(String pTC_STR_43TYPEINFOLCSCOLOR) {
		PTC_STR_43TYPEINFOLCSCOLOR = pTC_STR_43TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_44TYPEINFOLCSCOLOR() {
		return PTC_STR_44TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_44TYPEINFOLCSCOLOR(String pTC_STR_44TYPEINFOLCSCOLOR) {
		PTC_STR_44TYPEINFOLCSCOLOR = pTC_STR_44TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_45TYPEINFOLCSCOLOR() {
		return PTC_STR_45TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_45TYPEINFOLCSCOLOR(String pTC_STR_45TYPEINFOLCSCOLOR) {
		PTC_STR_45TYPEINFOLCSCOLOR = pTC_STR_45TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_46TYPEINFOLCSCOLOR() {
		return PTC_STR_46TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_46TYPEINFOLCSCOLOR(String pTC_STR_46TYPEINFOLCSCOLOR) {
		PTC_STR_46TYPEINFOLCSCOLOR = pTC_STR_46TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_47TYPEINFOLCSCOLOR() {
		return PTC_STR_47TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_47TYPEINFOLCSCOLOR(String pTC_STR_47TYPEINFOLCSCOLOR) {
		PTC_STR_47TYPEINFOLCSCOLOR = pTC_STR_47TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_48TYPEINFOLCSCOLOR() {
		return PTC_STR_48TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_48TYPEINFOLCSCOLOR(String pTC_STR_48TYPEINFOLCSCOLOR) {
		PTC_STR_48TYPEINFOLCSCOLOR = pTC_STR_48TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_49TYPEINFOLCSCOLOR() {
		return PTC_STR_49TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_49TYPEINFOLCSCOLOR(String pTC_STR_49TYPEINFOLCSCOLOR) {
		PTC_STR_49TYPEINFOLCSCOLOR = pTC_STR_49TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_50TYPEINFOLCSCOLOR() {
		return PTC_STR_50TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_50TYPEINFOLCSCOLOR(String pTC_STR_50TYPEINFOLCSCOLOR) {
		PTC_STR_50TYPEINFOLCSCOLOR = pTC_STR_50TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_51TYPEINFOLCSCOLOR() {
		return PTC_STR_51TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_51TYPEINFOLCSCOLOR(String pTC_STR_51TYPEINFOLCSCOLOR) {
		PTC_STR_51TYPEINFOLCSCOLOR = pTC_STR_51TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_52TYPEINFOLCSCOLOR() {
		return PTC_STR_52TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_52TYPEINFOLCSCOLOR(String pTC_STR_52TYPEINFOLCSCOLOR) {
		PTC_STR_52TYPEINFOLCSCOLOR = pTC_STR_52TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_53TYPEINFOLCSCOLOR() {
		return PTC_STR_53TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_53TYPEINFOLCSCOLOR(String pTC_STR_53TYPEINFOLCSCOLOR) {
		PTC_STR_53TYPEINFOLCSCOLOR = pTC_STR_53TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_54TYPEINFOLCSCOLOR() {
		return PTC_STR_54TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_54TYPEINFOLCSCOLOR(String pTC_STR_54TYPEINFOLCSCOLOR) {
		PTC_STR_54TYPEINFOLCSCOLOR = pTC_STR_54TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_55TYPEINFOLCSCOLOR() {
		return PTC_STR_55TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_55TYPEINFOLCSCOLOR(String pTC_STR_55TYPEINFOLCSCOLOR) {
		PTC_STR_55TYPEINFOLCSCOLOR = pTC_STR_55TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_56TYPEINFOLCSCOLOR() {
		return PTC_STR_56TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_56TYPEINFOLCSCOLOR(String pTC_STR_56TYPEINFOLCSCOLOR) {
		PTC_STR_56TYPEINFOLCSCOLOR = pTC_STR_56TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_57TYPEINFOLCSCOLOR() {
		return PTC_STR_57TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_57TYPEINFOLCSCOLOR(String pTC_STR_57TYPEINFOLCSCOLOR) {
		PTC_STR_57TYPEINFOLCSCOLOR = pTC_STR_57TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_58TYPEINFOLCSCOLOR() {
		return PTC_STR_58TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_58TYPEINFOLCSCOLOR(String pTC_STR_58TYPEINFOLCSCOLOR) {
		PTC_STR_58TYPEINFOLCSCOLOR = pTC_STR_58TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_59TYPEINFOLCSCOLOR() {
		return PTC_STR_59TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_59TYPEINFOLCSCOLOR(String pTC_STR_59TYPEINFOLCSCOLOR) {
		PTC_STR_59TYPEINFOLCSCOLOR = pTC_STR_59TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_60TYPEINFOLCSCOLOR() {
		return PTC_STR_60TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_60TYPEINFOLCSCOLOR(String pTC_STR_60TYPEINFOLCSCOLOR) {
		PTC_STR_60TYPEINFOLCSCOLOR = pTC_STR_60TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_61TYPEINFOLCSCOLOR() {
		return PTC_STR_61TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_61TYPEINFOLCSCOLOR(String pTC_STR_61TYPEINFOLCSCOLOR) {
		PTC_STR_61TYPEINFOLCSCOLOR = pTC_STR_61TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_62TYPEINFOLCSCOLOR() {
		return PTC_STR_62TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_62TYPEINFOLCSCOLOR(String pTC_STR_62TYPEINFOLCSCOLOR) {
		PTC_STR_62TYPEINFOLCSCOLOR = pTC_STR_62TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_63TYPEINFOLCSCOLOR() {
		return PTC_STR_63TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_63TYPEINFOLCSCOLOR(String pTC_STR_63TYPEINFOLCSCOLOR) {
		PTC_STR_63TYPEINFOLCSCOLOR = pTC_STR_63TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_64TYPEINFOLCSCOLOR() {
		return PTC_STR_64TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_64TYPEINFOLCSCOLOR(String pTC_STR_64TYPEINFOLCSCOLOR) {
		PTC_STR_64TYPEINFOLCSCOLOR = pTC_STR_64TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_65TYPEINFOLCSCOLOR() {
		return PTC_STR_65TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_65TYPEINFOLCSCOLOR(String pTC_STR_65TYPEINFOLCSCOLOR) {
		PTC_STR_65TYPEINFOLCSCOLOR = pTC_STR_65TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_66TYPEINFOLCSCOLOR() {
		return PTC_STR_66TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_66TYPEINFOLCSCOLOR(String pTC_STR_66TYPEINFOLCSCOLOR) {
		PTC_STR_66TYPEINFOLCSCOLOR = pTC_STR_66TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_67TYPEINFOLCSCOLOR() {
		return PTC_STR_67TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_67TYPEINFOLCSCOLOR(String pTC_STR_67TYPEINFOLCSCOLOR) {
		PTC_STR_67TYPEINFOLCSCOLOR = pTC_STR_67TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_68TYPEINFOLCSCOLOR() {
		return PTC_STR_68TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_68TYPEINFOLCSCOLOR(String pTC_STR_68TYPEINFOLCSCOLOR) {
		PTC_STR_68TYPEINFOLCSCOLOR = pTC_STR_68TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_69TYPEINFOLCSCOLOR() {
		return PTC_STR_69TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_69TYPEINFOLCSCOLOR(String pTC_STR_69TYPEINFOLCSCOLOR) {
		PTC_STR_69TYPEINFOLCSCOLOR = pTC_STR_69TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_70TYPEINFOLCSCOLOR() {
		return PTC_STR_70TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_70TYPEINFOLCSCOLOR(String pTC_STR_70TYPEINFOLCSCOLOR) {
		PTC_STR_70TYPEINFOLCSCOLOR = pTC_STR_70TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_71TYPEINFOLCSCOLOR() {
		return PTC_STR_71TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_71TYPEINFOLCSCOLOR(String pTC_STR_71TYPEINFOLCSCOLOR) {
		PTC_STR_71TYPEINFOLCSCOLOR = pTC_STR_71TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_72TYPEINFOLCSCOLOR() {
		return PTC_STR_72TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_72TYPEINFOLCSCOLOR(String pTC_STR_72TYPEINFOLCSCOLOR) {
		PTC_STR_72TYPEINFOLCSCOLOR = pTC_STR_72TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_73TYPEINFOLCSCOLOR() {
		return PTC_STR_73TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_73TYPEINFOLCSCOLOR(String pTC_STR_73TYPEINFOLCSCOLOR) {
		PTC_STR_73TYPEINFOLCSCOLOR = pTC_STR_73TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_74TYPEINFOLCSCOLOR() {
		return PTC_STR_74TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_74TYPEINFOLCSCOLOR(String pTC_STR_74TYPEINFOLCSCOLOR) {
		PTC_STR_74TYPEINFOLCSCOLOR = pTC_STR_74TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_75TYPEINFOLCSCOLOR() {
		return PTC_STR_75TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_75TYPEINFOLCSCOLOR(String pTC_STR_75TYPEINFOLCSCOLOR) {
		PTC_STR_75TYPEINFOLCSCOLOR = pTC_STR_75TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_76TYPEINFOLCSCOLOR() {
		return PTC_STR_76TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_76TYPEINFOLCSCOLOR(String pTC_STR_76TYPEINFOLCSCOLOR) {
		PTC_STR_76TYPEINFOLCSCOLOR = pTC_STR_76TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_77TYPEINFOLCSCOLOR() {
		return PTC_STR_77TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_77TYPEINFOLCSCOLOR(String pTC_STR_77TYPEINFOLCSCOLOR) {
		PTC_STR_77TYPEINFOLCSCOLOR = pTC_STR_77TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_78TYPEINFOLCSCOLOR() {
		return PTC_STR_78TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_78TYPEINFOLCSCOLOR(String pTC_STR_78TYPEINFOLCSCOLOR) {
		PTC_STR_78TYPEINFOLCSCOLOR = pTC_STR_78TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_79TYPEINFOLCSCOLOR() {
		return PTC_STR_79TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_79TYPEINFOLCSCOLOR(String pTC_STR_79TYPEINFOLCSCOLOR) {
		PTC_STR_79TYPEINFOLCSCOLOR = pTC_STR_79TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_80TYPEINFOLCSCOLOR() {
		return PTC_STR_80TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_80TYPEINFOLCSCOLOR(String pTC_STR_80TYPEINFOLCSCOLOR) {
		PTC_STR_80TYPEINFOLCSCOLOR = pTC_STR_80TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_81TYPEINFOLCSCOLOR() {
		return PTC_STR_81TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_81TYPEINFOLCSCOLOR(String pTC_STR_81TYPEINFOLCSCOLOR) {
		PTC_STR_81TYPEINFOLCSCOLOR = pTC_STR_81TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_82TYPEINFOLCSCOLOR() {
		return PTC_STR_82TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_82TYPEINFOLCSCOLOR(String pTC_STR_82TYPEINFOLCSCOLOR) {
		PTC_STR_82TYPEINFOLCSCOLOR = pTC_STR_82TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_83TYPEINFOLCSCOLOR() {
		return PTC_STR_83TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_83TYPEINFOLCSCOLOR(String pTC_STR_83TYPEINFOLCSCOLOR) {
		PTC_STR_83TYPEINFOLCSCOLOR = pTC_STR_83TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_84TYPEINFOLCSCOLOR() {
		return PTC_STR_84TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_84TYPEINFOLCSCOLOR(String pTC_STR_84TYPEINFOLCSCOLOR) {
		PTC_STR_84TYPEINFOLCSCOLOR = pTC_STR_84TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_85TYPEINFOLCSCOLOR() {
		return PTC_STR_85TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_85TYPEINFOLCSCOLOR(String pTC_STR_85TYPEINFOLCSCOLOR) {
		PTC_STR_85TYPEINFOLCSCOLOR = pTC_STR_85TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_86TYPEINFOLCSCOLOR() {
		return PTC_STR_86TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_86TYPEINFOLCSCOLOR(String pTC_STR_86TYPEINFOLCSCOLOR) {
		PTC_STR_86TYPEINFOLCSCOLOR = pTC_STR_86TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_87TYPEINFOLCSCOLOR() {
		return PTC_STR_87TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_87TYPEINFOLCSCOLOR(String pTC_STR_87TYPEINFOLCSCOLOR) {
		PTC_STR_87TYPEINFOLCSCOLOR = pTC_STR_87TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_88TYPEINFOLCSCOLOR() {
		return PTC_STR_88TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_88TYPEINFOLCSCOLOR(String pTC_STR_88TYPEINFOLCSCOLOR) {
		PTC_STR_88TYPEINFOLCSCOLOR = pTC_STR_88TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_89TYPEINFOLCSCOLOR() {
		return PTC_STR_89TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_89TYPEINFOLCSCOLOR(String pTC_STR_89TYPEINFOLCSCOLOR) {
		PTC_STR_89TYPEINFOLCSCOLOR = pTC_STR_89TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_90TYPEINFOLCSCOLOR() {
		return PTC_STR_90TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_90TYPEINFOLCSCOLOR(String pTC_STR_90TYPEINFOLCSCOLOR) {
		PTC_STR_90TYPEINFOLCSCOLOR = pTC_STR_90TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_91TYPEINFOLCSCOLOR() {
		return PTC_STR_91TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_91TYPEINFOLCSCOLOR(String pTC_STR_91TYPEINFOLCSCOLOR) {
		PTC_STR_91TYPEINFOLCSCOLOR = pTC_STR_91TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_92TYPEINFOLCSCOLOR() {
		return PTC_STR_92TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_92TYPEINFOLCSCOLOR(String pTC_STR_92TYPEINFOLCSCOLOR) {
		PTC_STR_92TYPEINFOLCSCOLOR = pTC_STR_92TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_93TYPEINFOLCSCOLOR() {
		return PTC_STR_93TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_93TYPEINFOLCSCOLOR(String pTC_STR_93TYPEINFOLCSCOLOR) {
		PTC_STR_93TYPEINFOLCSCOLOR = pTC_STR_93TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_94TYPEINFOLCSCOLOR() {
		return PTC_STR_94TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_94TYPEINFOLCSCOLOR(String pTC_STR_94TYPEINFOLCSCOLOR) {
		PTC_STR_94TYPEINFOLCSCOLOR = pTC_STR_94TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_95TYPEINFOLCSCOLOR() {
		return PTC_STR_95TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_95TYPEINFOLCSCOLOR(String pTC_STR_95TYPEINFOLCSCOLOR) {
		PTC_STR_95TYPEINFOLCSCOLOR = pTC_STR_95TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_96TYPEINFOLCSCOLOR() {
		return PTC_STR_96TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_96TYPEINFOLCSCOLOR(String pTC_STR_96TYPEINFOLCSCOLOR) {
		PTC_STR_96TYPEINFOLCSCOLOR = pTC_STR_96TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_97TYPEINFOLCSCOLOR() {
		return PTC_STR_97TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_97TYPEINFOLCSCOLOR(String pTC_STR_97TYPEINFOLCSCOLOR) {
		PTC_STR_97TYPEINFOLCSCOLOR = pTC_STR_97TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_98TYPEINFOLCSCOLOR() {
		return PTC_STR_98TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_98TYPEINFOLCSCOLOR(String pTC_STR_98TYPEINFOLCSCOLOR) {
		PTC_STR_98TYPEINFOLCSCOLOR = pTC_STR_98TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_99TYPEINFOLCSCOLOR() {
		return PTC_STR_99TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_99TYPEINFOLCSCOLOR(String pTC_STR_99TYPEINFOLCSCOLOR) {
		PTC_STR_99TYPEINFOLCSCOLOR = pTC_STR_99TYPEINFOLCSCOLOR;
	}
	public String getPTC_STR_100TYPEINFOLCSCOLOR() {
		return PTC_STR_100TYPEINFOLCSCOLOR;
	}
	public void setPTC_STR_100TYPEINFOLCSCOLOR(String pTC_STR_100TYPEINFOLCSCOLOR) {
		PTC_STR_100TYPEINFOLCSCOLOR = pTC_STR_100TYPEINFOLCSCOLOR;
	}
	public long getPTC_LNG_1TYPEINFOLCSCOLOR() {
		return PTC_LNG_1TYPEINFOLCSCOLOR;
	}
	public void setPTC_LNG_1TYPEINFOLCSCOLOR(long pTC_LNG_1TYPEINFOLCSCOLOR) {
		PTC_LNG_1TYPEINFOLCSCOLOR = pTC_LNG_1TYPEINFOLCSCOLOR;
	}
	public long getPTC_LNG_2TYPEINFOLCSCOLOR() {
		return PTC_LNG_2TYPEINFOLCSCOLOR;
	}
	public void setPTC_LNG_2TYPEINFOLCSCOLOR(long pTC_LNG_2TYPEINFOLCSCOLOR) {
		PTC_LNG_2TYPEINFOLCSCOLOR = pTC_LNG_2TYPEINFOLCSCOLOR;
	}
	public long getPTC_LNG_3TYPEINFOLCSCOLOR() {
		return PTC_LNG_3TYPEINFOLCSCOLOR;
	}
	public void setPTC_LNG_3TYPEINFOLCSCOLOR(long pTC_LNG_3TYPEINFOLCSCOLOR) {
		PTC_LNG_3TYPEINFOLCSCOLOR = pTC_LNG_3TYPEINFOLCSCOLOR;
	}
	public long getPTC_LNG_4TYPEINFOLCSCOLOR() {
		return PTC_LNG_4TYPEINFOLCSCOLOR;
	}
	public void setPTC_LNG_4TYPEINFOLCSCOLOR(long pTC_LNG_4TYPEINFOLCSCOLOR) {
		PTC_LNG_4TYPEINFOLCSCOLOR = pTC_LNG_4TYPEINFOLCSCOLOR;
	}
	public long getPTC_LNG_5TYPEINFOLCSCOLOR() {
		return PTC_LNG_5TYPEINFOLCSCOLOR;
	}
	public void setPTC_LNG_5TYPEINFOLCSCOLOR(long pTC_LNG_5TYPEINFOLCSCOLOR) {
		PTC_LNG_5TYPEINFOLCSCOLOR = pTC_LNG_5TYPEINFOLCSCOLOR;
	}
	public long getPTC_LNG_6TYPEINFOLCSCOLOR() {
		return PTC_LNG_6TYPEINFOLCSCOLOR;
	}
	public void setPTC_LNG_6TYPEINFOLCSCOLOR(long pTC_LNG_6TYPEINFOLCSCOLOR) {
		PTC_LNG_6TYPEINFOLCSCOLOR = pTC_LNG_6TYPEINFOLCSCOLOR;
	}
	public long getPTC_LNG_7TYPEINFOLCSCOLOR() {
		return PTC_LNG_7TYPEINFOLCSCOLOR;
	}
	public void setPTC_LNG_7TYPEINFOLCSCOLOR(long pTC_LNG_7TYPEINFOLCSCOLOR) {
		PTC_LNG_7TYPEINFOLCSCOLOR = pTC_LNG_7TYPEINFOLCSCOLOR;
	}
	public long getPTC_LNG_8TYPEINFOLCSCOLOR() {
		return PTC_LNG_8TYPEINFOLCSCOLOR;
	}
	public void setPTC_LNG_8TYPEINFOLCSCOLOR(long pTC_LNG_8TYPEINFOLCSCOLOR) {
		PTC_LNG_8TYPEINFOLCSCOLOR = pTC_LNG_8TYPEINFOLCSCOLOR;
	}
	public long getPTC_LNG_9TYPEINFOLCSCOLOR() {
		return PTC_LNG_9TYPEINFOLCSCOLOR;
	}
	public void setPTC_LNG_9TYPEINFOLCSCOLOR(long pTC_LNG_9TYPEINFOLCSCOLOR) {
		PTC_LNG_9TYPEINFOLCSCOLOR = pTC_LNG_9TYPEINFOLCSCOLOR;
	}
	public long getPTC_LNG_10TYPEINFOLCSCOLOR() {
		return PTC_LNG_10TYPEINFOLCSCOLOR;
	}
	public void setPTC_LNG_10TYPEINFOLCSCOLOR(long pTC_LNG_10TYPEINFOLCSCOLOR) {
		PTC_LNG_10TYPEINFOLCSCOLOR = pTC_LNG_10TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_1TYPEINFOLCSCOLOR() {
		return PTC_TMS_1TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_1TYPEINFOLCSCOLOR(Date pTC_TMS_1TYPEINFOLCSCOLOR) {
		PTC_TMS_1TYPEINFOLCSCOLOR = pTC_TMS_1TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_2TYPEINFOLCSCOLOR() {
		return PTC_TMS_2TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_2TYPEINFOLCSCOLOR(Date pTC_TMS_2TYPEINFOLCSCOLOR) {
		PTC_TMS_2TYPEINFOLCSCOLOR = pTC_TMS_2TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_3TYPEINFOLCSCOLOR() {
		return PTC_TMS_3TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_3TYPEINFOLCSCOLOR(Date pTC_TMS_3TYPEINFOLCSCOLOR) {
		PTC_TMS_3TYPEINFOLCSCOLOR = pTC_TMS_3TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_4TYPEINFOLCSCOLOR() {
		return PTC_TMS_4TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_4TYPEINFOLCSCOLOR(Date pTC_TMS_4TYPEINFOLCSCOLOR) {
		PTC_TMS_4TYPEINFOLCSCOLOR = pTC_TMS_4TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_5TYPEINFOLCSCOLOR() {
		return PTC_TMS_5TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_5TYPEINFOLCSCOLOR(Date pTC_TMS_5TYPEINFOLCSCOLOR) {
		PTC_TMS_5TYPEINFOLCSCOLOR = pTC_TMS_5TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_6TYPEINFOLCSCOLOR() {
		return PTC_TMS_6TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_6TYPEINFOLCSCOLOR(Date pTC_TMS_6TYPEINFOLCSCOLOR) {
		PTC_TMS_6TYPEINFOLCSCOLOR = pTC_TMS_6TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_7TYPEINFOLCSCOLOR() {
		return PTC_TMS_7TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_7TYPEINFOLCSCOLOR(Date pTC_TMS_7TYPEINFOLCSCOLOR) {
		PTC_TMS_7TYPEINFOLCSCOLOR = pTC_TMS_7TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_8TYPEINFOLCSCOLOR() {
		return PTC_TMS_8TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_8TYPEINFOLCSCOLOR(Date pTC_TMS_8TYPEINFOLCSCOLOR) {
		PTC_TMS_8TYPEINFOLCSCOLOR = pTC_TMS_8TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_9TYPEINFOLCSCOLOR() {
		return PTC_TMS_9TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_9TYPEINFOLCSCOLOR(Date pTC_TMS_9TYPEINFOLCSCOLOR) {
		PTC_TMS_9TYPEINFOLCSCOLOR = pTC_TMS_9TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_10TYPEINFOLCSCOLOR() {
		return PTC_TMS_10TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_10TYPEINFOLCSCOLOR(Date pTC_TMS_10TYPEINFOLCSCOLOR) {
		PTC_TMS_10TYPEINFOLCSCOLOR = pTC_TMS_10TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_11TYPEINFOLCSCOLOR() {
		return PTC_TMS_11TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_11TYPEINFOLCSCOLOR(Date pTC_TMS_11TYPEINFOLCSCOLOR) {
		PTC_TMS_11TYPEINFOLCSCOLOR = pTC_TMS_11TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_12TYPEINFOLCSCOLOR() {
		return PTC_TMS_12TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_12TYPEINFOLCSCOLOR(Date pTC_TMS_12TYPEINFOLCSCOLOR) {
		PTC_TMS_12TYPEINFOLCSCOLOR = pTC_TMS_12TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_13TYPEINFOLCSCOLOR() {
		return PTC_TMS_13TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_13TYPEINFOLCSCOLOR(Date pTC_TMS_13TYPEINFOLCSCOLOR) {
		PTC_TMS_13TYPEINFOLCSCOLOR = pTC_TMS_13TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_14TYPEINFOLCSCOLOR() {
		return PTC_TMS_14TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_14TYPEINFOLCSCOLOR(Date pTC_TMS_14TYPEINFOLCSCOLOR) {
		PTC_TMS_14TYPEINFOLCSCOLOR = pTC_TMS_14TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_15TYPEINFOLCSCOLOR() {
		return PTC_TMS_15TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_15TYPEINFOLCSCOLOR(Date pTC_TMS_15TYPEINFOLCSCOLOR) {
		PTC_TMS_15TYPEINFOLCSCOLOR = pTC_TMS_15TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_16TYPEINFOLCSCOLOR() {
		return PTC_TMS_16TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_16TYPEINFOLCSCOLOR(Date pTC_TMS_16TYPEINFOLCSCOLOR) {
		PTC_TMS_16TYPEINFOLCSCOLOR = pTC_TMS_16TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_17TYPEINFOLCSCOLOR() {
		return PTC_TMS_17TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_17TYPEINFOLCSCOLOR(Date pTC_TMS_17TYPEINFOLCSCOLOR) {
		PTC_TMS_17TYPEINFOLCSCOLOR = pTC_TMS_17TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_18TYPEINFOLCSCOLOR() {
		return PTC_TMS_18TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_18TYPEINFOLCSCOLOR(Date pTC_TMS_18TYPEINFOLCSCOLOR) {
		PTC_TMS_18TYPEINFOLCSCOLOR = pTC_TMS_18TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_19TYPEINFOLCSCOLOR() {
		return PTC_TMS_19TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_19TYPEINFOLCSCOLOR(Date pTC_TMS_19TYPEINFOLCSCOLOR) {
		PTC_TMS_19TYPEINFOLCSCOLOR = pTC_TMS_19TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_20TYPEINFOLCSCOLOR() {
		return PTC_TMS_20TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_20TYPEINFOLCSCOLOR(Date pTC_TMS_20TYPEINFOLCSCOLOR) {
		PTC_TMS_20TYPEINFOLCSCOLOR = pTC_TMS_20TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_21TYPEINFOLCSCOLOR() {
		return PTC_TMS_21TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_21TYPEINFOLCSCOLOR(Date pTC_TMS_21TYPEINFOLCSCOLOR) {
		PTC_TMS_21TYPEINFOLCSCOLOR = pTC_TMS_21TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_22TYPEINFOLCSCOLOR() {
		return PTC_TMS_22TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_22TYPEINFOLCSCOLOR(Date pTC_TMS_22TYPEINFOLCSCOLOR) {
		PTC_TMS_22TYPEINFOLCSCOLOR = pTC_TMS_22TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_23TYPEINFOLCSCOLOR() {
		return PTC_TMS_23TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_23TYPEINFOLCSCOLOR(Date pTC_TMS_23TYPEINFOLCSCOLOR) {
		PTC_TMS_23TYPEINFOLCSCOLOR = pTC_TMS_23TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_24TYPEINFOLCSCOLOR() {
		return PTC_TMS_24TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_24TYPEINFOLCSCOLOR(Date pTC_TMS_24TYPEINFOLCSCOLOR) {
		PTC_TMS_24TYPEINFOLCSCOLOR = pTC_TMS_24TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_25TYPEINFOLCSCOLOR() {
		return PTC_TMS_25TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_25TYPEINFOLCSCOLOR(Date pTC_TMS_25TYPEINFOLCSCOLOR) {
		PTC_TMS_25TYPEINFOLCSCOLOR = pTC_TMS_25TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_26TYPEINFOLCSCOLOR() {
		return PTC_TMS_26TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_26TYPEINFOLCSCOLOR(Date pTC_TMS_26TYPEINFOLCSCOLOR) {
		PTC_TMS_26TYPEINFOLCSCOLOR = pTC_TMS_26TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_27TYPEINFOLCSCOLOR() {
		return PTC_TMS_27TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_27TYPEINFOLCSCOLOR(Date pTC_TMS_27TYPEINFOLCSCOLOR) {
		PTC_TMS_27TYPEINFOLCSCOLOR = pTC_TMS_27TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_28TYPEINFOLCSCOLOR() {
		return PTC_TMS_28TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_28TYPEINFOLCSCOLOR(Date pTC_TMS_28TYPEINFOLCSCOLOR) {
		PTC_TMS_28TYPEINFOLCSCOLOR = pTC_TMS_28TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_29TYPEINFOLCSCOLOR() {
		return PTC_TMS_29TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_29TYPEINFOLCSCOLOR(Date pTC_TMS_29TYPEINFOLCSCOLOR) {
		PTC_TMS_29TYPEINFOLCSCOLOR = pTC_TMS_29TYPEINFOLCSCOLOR;
	}
	public Date getPTC_TMS_30TYPEINFOLCSCOLOR() {
		return PTC_TMS_30TYPEINFOLCSCOLOR;
	}
	public void setPTC_TMS_30TYPEINFOLCSCOLOR(Date pTC_TMS_30TYPEINFOLCSCOLOR) {
		PTC_TMS_30TYPEINFOLCSCOLOR = pTC_TMS_30TYPEINFOLCSCOLOR;
	}
	public String getPTC_BLN_1TYPEINFOLCSCOLOR() {
		return PTC_BLN_1TYPEINFOLCSCOLOR;
	}
	public void setPTC_BLN_1TYPEINFOLCSCOLOR(String pTC_BLN_1TYPEINFOLCSCOLOR) {
		PTC_BLN_1TYPEINFOLCSCOLOR = pTC_BLN_1TYPEINFOLCSCOLOR;
	}
	public String getPTC_BLN_2TYPEINFOLCSCOLOR() {
		return PTC_BLN_2TYPEINFOLCSCOLOR;
	}
	public void setPTC_BLN_2TYPEINFOLCSCOLOR(String pTC_BLN_2TYPEINFOLCSCOLOR) {
		PTC_BLN_2TYPEINFOLCSCOLOR = pTC_BLN_2TYPEINFOLCSCOLOR;
	}
	public String getPTC_BLN_3TYPEINFOLCSCOLOR() {
		return PTC_BLN_3TYPEINFOLCSCOLOR;
	}
	public void setPTC_BLN_3TYPEINFOLCSCOLOR(String pTC_BLN_3TYPEINFOLCSCOLOR) {
		PTC_BLN_3TYPEINFOLCSCOLOR = pTC_BLN_3TYPEINFOLCSCOLOR;
	}
	public String getPTC_BLN_4TYPEINFOLCSCOLOR() {
		return PTC_BLN_4TYPEINFOLCSCOLOR;
	}
	public void setPTC_BLN_4TYPEINFOLCSCOLOR(String pTC_BLN_4TYPEINFOLCSCOLOR) {
		PTC_BLN_4TYPEINFOLCSCOLOR = pTC_BLN_4TYPEINFOLCSCOLOR;
	}
	public String getPTC_BLN_5TYPEINFOLCSCOLOR() {
		return PTC_BLN_5TYPEINFOLCSCOLOR;
	}
	public void setPTC_BLN_5TYPEINFOLCSCOLOR(String pTC_BLN_5TYPEINFOLCSCOLOR) {
		PTC_BLN_5TYPEINFOLCSCOLOR = pTC_BLN_5TYPEINFOLCSCOLOR;
	}
	public String getPTC_BLN_6TYPEINFOLCSCOLOR() {
		return PTC_BLN_6TYPEINFOLCSCOLOR;
	}
	public void setPTC_BLN_6TYPEINFOLCSCOLOR(String pTC_BLN_6TYPEINFOLCSCOLOR) {
		PTC_BLN_6TYPEINFOLCSCOLOR = pTC_BLN_6TYPEINFOLCSCOLOR;
	}
	public String getPTC_BLN_7TYPEINFOLCSCOLOR() {
		return PTC_BLN_7TYPEINFOLCSCOLOR;
	}
	public void setPTC_BLN_7TYPEINFOLCSCOLOR(String pTC_BLN_7TYPEINFOLCSCOLOR) {
		PTC_BLN_7TYPEINFOLCSCOLOR = pTC_BLN_7TYPEINFOLCSCOLOR;
	}
	public String getPTC_BLN_8TYPEINFOLCSCOLOR() {
		return PTC_BLN_8TYPEINFOLCSCOLOR;
	}
	public void setPTC_BLN_8TYPEINFOLCSCOLOR(String pTC_BLN_8TYPEINFOLCSCOLOR) {
		PTC_BLN_8TYPEINFOLCSCOLOR = pTC_BLN_8TYPEINFOLCSCOLOR;
	}
	public String getPTC_BLN_9TYPEINFOLCSCOLOR() {
		return PTC_BLN_9TYPEINFOLCSCOLOR;
	}
	public void setPTC_BLN_9TYPEINFOLCSCOLOR(String pTC_BLN_9TYPEINFOLCSCOLOR) {
		PTC_BLN_9TYPEINFOLCSCOLOR = pTC_BLN_9TYPEINFOLCSCOLOR;
	}
	public String getPTC_BLN_10TYPEINFOLCSCOLOR() {
		return PTC_BLN_10TYPEINFOLCSCOLOR;
	}
	public void setPTC_BLN_10TYPEINFOLCSCOLOR(String pTC_BLN_10TYPEINFOLCSCOLOR) {
		PTC_BLN_10TYPEINFOLCSCOLOR = pTC_BLN_10TYPEINFOLCSCOLOR;
	}
	@Override
	public String toString() {
		return "QiwkColor [primaryKey=" + primaryKey + ", BRANCHID=" + BRANCHID + ", CREATESTAMPA2=" + CREATESTAMPA2
				+ ", UPDATESTAMPA2=" + UPDATESTAMPA2 + ", FLEXTYPEIDPATH=" + FLEXTYPEIDPATH + ", FLEXTYPEID="
				+ FLEXTYPEID + ", COLORHEXIDECIMALVALUE=" + COLORHEXIDECIMALVALUE + ", THUMBNAIL=" + THUMBNAIL
				+ ", COLORNAME=" + COLORNAME + ", UPDATECOUNTA2=" + UPDATECOUNTA2 + ", MARKEDFORDELETEA2="
				+ MARKEDFORDELETEA2 + ", IDA2TYPEDEFINITIONREFERENCE=" + IDA2TYPEDEFINITIONREFERENCE
				+ ", LOADERCREATESTAMP=" + LOADERCREATESTAMP + ", LOADERUPDATESTAMP=" + LOADERUPDATESTAMP
				+ ", BRANCHIDA3E2TYPEINFOLCSCOLOR=" + BRANCHIDA3E2TYPEINFOLCSCOLOR + ", BRANCHIDA3D2TYPEINFOLCSCOLOR="
				+ BRANCHIDA3D2TYPEINFOLCSCOLOR + ", BRANCHIDA3C2TYPEINFOLCSCOLOR=" + BRANCHIDA3C2TYPEINFOLCSCOLOR
				+ ", BRANCHIDA3B2TYPEINFOLCSCOLOR=" + BRANCHIDA3B2TYPEINFOLCSCOLOR + ", BRANCHIDA3A2TYPEINFOLCSCOLOR="
				+ BRANCHIDA3A2TYPEINFOLCSCOLOR + ", PTC_DBL_1TYPEINFOLCSCOLOR=" + PTC_DBL_1TYPEINFOLCSCOLOR
				+ ", PTC_DBL_2TYPEINFOLCSCOLOR=" + PTC_DBL_2TYPEINFOLCSCOLOR + ", PTC_DBL_3TYPEINFOLCSCOLOR="
				+ PTC_DBL_3TYPEINFOLCSCOLOR + ", PTC_DBL_4TYPEINFOLCSCOLOR=" + PTC_DBL_4TYPEINFOLCSCOLOR
				+ ", PTC_DBL_5TYPEINFOLCSCOLOR=" + PTC_DBL_5TYPEINFOLCSCOLOR + ", PTC_DBL_6TYPEINFOLCSCOLOR="
				+ PTC_DBL_6TYPEINFOLCSCOLOR + ", PTC_DBL_7TYPEINFOLCSCOLOR=" + PTC_DBL_7TYPEINFOLCSCOLOR
				+ ", PTC_DBL_8TYPEINFOLCSCOLOR=" + PTC_DBL_8TYPEINFOLCSCOLOR + ", PTC_DBL_9TYPEINFOLCSCOLOR="
				+ PTC_DBL_9TYPEINFOLCSCOLOR + ", PTC_DBL_10TYPEINFOLCSCOLOR=" + PTC_DBL_10TYPEINFOLCSCOLOR
				+ ", PTC_DBL_11TYPEINFOLCSCOLOR=" + PTC_DBL_11TYPEINFOLCSCOLOR + ", PTC_DBL_12TYPEINFOLCSCOLOR="
				+ PTC_DBL_12TYPEINFOLCSCOLOR + ", PTC_DBL_13TYPEINFOLCSCOLOR=" + PTC_DBL_13TYPEINFOLCSCOLOR
				+ ", PTC_DBL_14TYPEINFOLCSCOLOR=" + PTC_DBL_14TYPEINFOLCSCOLOR + ", PTC_DBL_15TYPEINFOLCSCOLOR="
				+ PTC_DBL_15TYPEINFOLCSCOLOR + ", PTC_DBL_16TYPEINFOLCSCOLOR=" + PTC_DBL_16TYPEINFOLCSCOLOR
				+ ", PTC_DBL_17TYPEINFOLCSCOLOR=" + PTC_DBL_17TYPEINFOLCSCOLOR + ", PTC_DBL_18TYPEINFOLCSCOLOR="
				+ PTC_DBL_18TYPEINFOLCSCOLOR + ", PTC_DBL_19TYPEINFOLCSCOLOR=" + PTC_DBL_19TYPEINFOLCSCOLOR
				+ ", PTC_DBL_20TYPEINFOLCSCOLOR=" + PTC_DBL_20TYPEINFOLCSCOLOR + ", PTC_STR_1TYPEINFOLCSCOLOR="
				+ PTC_STR_1TYPEINFOLCSCOLOR + ", PTC_STR_2TYPEINFOLCSCOLOR=" + PTC_STR_2TYPEINFOLCSCOLOR
				+ ", PTC_STR_3TYPEINFOLCSCOLOR=" + PTC_STR_3TYPEINFOLCSCOLOR + ", PTC_STR_4TYPEINFOLCSCOLOR="
				+ PTC_STR_4TYPEINFOLCSCOLOR + ", PTC_STR_5TYPEINFOLCSCOLOR=" + PTC_STR_5TYPEINFOLCSCOLOR
				+ ", PTC_STR_6TYPEINFOLCSCOLOR=" + PTC_STR_6TYPEINFOLCSCOLOR + ", PTC_STR_7TYPEINFOLCSCOLOR="
				+ PTC_STR_7TYPEINFOLCSCOLOR + ", PTC_STR_8TYPEINFOLCSCOLOR=" + PTC_STR_8TYPEINFOLCSCOLOR
				+ ", PTC_STR_9TYPEINFOLCSCOLOR=" + PTC_STR_9TYPEINFOLCSCOLOR + ", PTC_STR_10TYPEINFOLCSCOLOR="
				+ PTC_STR_10TYPEINFOLCSCOLOR + ", PTC_STR_11TYPEINFOLCSCOLOR=" + PTC_STR_11TYPEINFOLCSCOLOR
				+ ", PTC_STR_12TYPEINFOLCSCOLOR=" + PTC_STR_12TYPEINFOLCSCOLOR + ", PTC_STR_13TYPEINFOLCSCOLOR="
				+ PTC_STR_13TYPEINFOLCSCOLOR + ", PTC_STR_14TYPEINFOLCSCOLOR=" + PTC_STR_14TYPEINFOLCSCOLOR
				+ ", PTC_STR_15TYPEINFOLCSCOLOR=" + PTC_STR_15TYPEINFOLCSCOLOR + ", PTC_STR_16TYPEINFOLCSCOLOR="
				+ PTC_STR_16TYPEINFOLCSCOLOR + ", PTC_STR_17TYPEINFOLCSCOLOR=" + PTC_STR_17TYPEINFOLCSCOLOR
				+ ", PTC_STR_18TYPEINFOLCSCOLOR=" + PTC_STR_18TYPEINFOLCSCOLOR + ", PTC_STR_19TYPEINFOLCSCOLOR="
				+ PTC_STR_19TYPEINFOLCSCOLOR + ", PTC_STR_20TYPEINFOLCSCOLOR=" + PTC_STR_20TYPEINFOLCSCOLOR
				+ ", PTC_STR_21TYPEINFOLCSCOLOR=" + PTC_STR_21TYPEINFOLCSCOLOR + ", PTC_STR_22TYPEINFOLCSCOLOR="
				+ PTC_STR_22TYPEINFOLCSCOLOR + ", PTC_STR_23TYPEINFOLCSCOLOR=" + PTC_STR_23TYPEINFOLCSCOLOR
				+ ", PTC_STR_24TYPEINFOLCSCOLOR=" + PTC_STR_24TYPEINFOLCSCOLOR + ", PTC_STR_25TYPEINFOLCSCOLOR="
				+ PTC_STR_25TYPEINFOLCSCOLOR + ", PTC_STR_26TYPEINFOLCSCOLOR=" + PTC_STR_26TYPEINFOLCSCOLOR
				+ ", PTC_STR_27TYPEINFOLCSCOLOR=" + PTC_STR_27TYPEINFOLCSCOLOR + ", PTC_STR_28TYPEINFOLCSCOLOR="
				+ PTC_STR_28TYPEINFOLCSCOLOR + ", PTC_STR_29TYPEINFOLCSCOLOR=" + PTC_STR_29TYPEINFOLCSCOLOR
				+ ", PTC_STR_30TYPEINFOLCSCOLOR=" + PTC_STR_30TYPEINFOLCSCOLOR + ", PTC_STR_31TYPEINFOLCSCOLOR="
				+ PTC_STR_31TYPEINFOLCSCOLOR + ", PTC_STR_32TYPEINFOLCSCOLOR=" + PTC_STR_32TYPEINFOLCSCOLOR
				+ ", PTC_STR_33TYPEINFOLCSCOLOR=" + PTC_STR_33TYPEINFOLCSCOLOR + ", PTC_STR_34TYPEINFOLCSCOLOR="
				+ PTC_STR_34TYPEINFOLCSCOLOR + ", PTC_STR_35TYPEINFOLCSCOLOR=" + PTC_STR_35TYPEINFOLCSCOLOR
				+ ", PTC_STR_36TYPEINFOLCSCOLOR=" + PTC_STR_36TYPEINFOLCSCOLOR + ", PTC_STR_37TYPEINFOLCSCOLOR="
				+ PTC_STR_37TYPEINFOLCSCOLOR + ", PTC_STR_38TYPEINFOLCSCOLOR=" + PTC_STR_38TYPEINFOLCSCOLOR
				+ ", PTC_STR_39TYPEINFOLCSCOLOR=" + PTC_STR_39TYPEINFOLCSCOLOR + ", PTC_STR_40TYPEINFOLCSCOLOR="
				+ PTC_STR_40TYPEINFOLCSCOLOR + ", PTC_STR_41TYPEINFOLCSCOLOR=" + PTC_STR_41TYPEINFOLCSCOLOR
				+ ", PTC_STR_42TYPEINFOLCSCOLOR=" + PTC_STR_42TYPEINFOLCSCOLOR + ", PTC_STR_43TYPEINFOLCSCOLOR="
				+ PTC_STR_43TYPEINFOLCSCOLOR + ", PTC_STR_44TYPEINFOLCSCOLOR=" + PTC_STR_44TYPEINFOLCSCOLOR
				+ ", PTC_STR_45TYPEINFOLCSCOLOR=" + PTC_STR_45TYPEINFOLCSCOLOR + ", PTC_STR_46TYPEINFOLCSCOLOR="
				+ PTC_STR_46TYPEINFOLCSCOLOR + ", PTC_STR_47TYPEINFOLCSCOLOR=" + PTC_STR_47TYPEINFOLCSCOLOR
				+ ", PTC_STR_48TYPEINFOLCSCOLOR=" + PTC_STR_48TYPEINFOLCSCOLOR + ", PTC_STR_49TYPEINFOLCSCOLOR="
				+ PTC_STR_49TYPEINFOLCSCOLOR + ", PTC_STR_50TYPEINFOLCSCOLOR=" + PTC_STR_50TYPEINFOLCSCOLOR
				+ ", PTC_STR_51TYPEINFOLCSCOLOR=" + PTC_STR_51TYPEINFOLCSCOLOR + ", PTC_STR_52TYPEINFOLCSCOLOR="
				+ PTC_STR_52TYPEINFOLCSCOLOR + ", PTC_STR_53TYPEINFOLCSCOLOR=" + PTC_STR_53TYPEINFOLCSCOLOR
				+ ", PTC_STR_54TYPEINFOLCSCOLOR=" + PTC_STR_54TYPEINFOLCSCOLOR + ", PTC_STR_55TYPEINFOLCSCOLOR="
				+ PTC_STR_55TYPEINFOLCSCOLOR + ", PTC_STR_56TYPEINFOLCSCOLOR=" + PTC_STR_56TYPEINFOLCSCOLOR
				+ ", PTC_STR_57TYPEINFOLCSCOLOR=" + PTC_STR_57TYPEINFOLCSCOLOR + ", PTC_STR_58TYPEINFOLCSCOLOR="
				+ PTC_STR_58TYPEINFOLCSCOLOR + ", PTC_STR_59TYPEINFOLCSCOLOR=" + PTC_STR_59TYPEINFOLCSCOLOR
				+ ", PTC_STR_60TYPEINFOLCSCOLOR=" + PTC_STR_60TYPEINFOLCSCOLOR + ", PTC_STR_61TYPEINFOLCSCOLOR="
				+ PTC_STR_61TYPEINFOLCSCOLOR + ", PTC_STR_62TYPEINFOLCSCOLOR=" + PTC_STR_62TYPEINFOLCSCOLOR
				+ ", PTC_STR_63TYPEINFOLCSCOLOR=" + PTC_STR_63TYPEINFOLCSCOLOR + ", PTC_STR_64TYPEINFOLCSCOLOR="
				+ PTC_STR_64TYPEINFOLCSCOLOR + ", PTC_STR_65TYPEINFOLCSCOLOR=" + PTC_STR_65TYPEINFOLCSCOLOR
				+ ", PTC_STR_66TYPEINFOLCSCOLOR=" + PTC_STR_66TYPEINFOLCSCOLOR + ", PTC_STR_67TYPEINFOLCSCOLOR="
				+ PTC_STR_67TYPEINFOLCSCOLOR + ", PTC_STR_68TYPEINFOLCSCOLOR=" + PTC_STR_68TYPEINFOLCSCOLOR
				+ ", PTC_STR_69TYPEINFOLCSCOLOR=" + PTC_STR_69TYPEINFOLCSCOLOR + ", PTC_STR_70TYPEINFOLCSCOLOR="
				+ PTC_STR_70TYPEINFOLCSCOLOR + ", PTC_STR_71TYPEINFOLCSCOLOR=" + PTC_STR_71TYPEINFOLCSCOLOR
				+ ", PTC_STR_72TYPEINFOLCSCOLOR=" + PTC_STR_72TYPEINFOLCSCOLOR + ", PTC_STR_73TYPEINFOLCSCOLOR="
				+ PTC_STR_73TYPEINFOLCSCOLOR + ", PTC_STR_74TYPEINFOLCSCOLOR=" + PTC_STR_74TYPEINFOLCSCOLOR
				+ ", PTC_STR_75TYPEINFOLCSCOLOR=" + PTC_STR_75TYPEINFOLCSCOLOR + ", PTC_STR_76TYPEINFOLCSCOLOR="
				+ PTC_STR_76TYPEINFOLCSCOLOR + ", PTC_STR_77TYPEINFOLCSCOLOR=" + PTC_STR_77TYPEINFOLCSCOLOR
				+ ", PTC_STR_78TYPEINFOLCSCOLOR=" + PTC_STR_78TYPEINFOLCSCOLOR + ", PTC_STR_79TYPEINFOLCSCOLOR="
				+ PTC_STR_79TYPEINFOLCSCOLOR + ", PTC_STR_80TYPEINFOLCSCOLOR=" + PTC_STR_80TYPEINFOLCSCOLOR
				+ ", PTC_STR_81TYPEINFOLCSCOLOR=" + PTC_STR_81TYPEINFOLCSCOLOR + ", PTC_STR_82TYPEINFOLCSCOLOR="
				+ PTC_STR_82TYPEINFOLCSCOLOR + ", PTC_STR_83TYPEINFOLCSCOLOR=" + PTC_STR_83TYPEINFOLCSCOLOR
				+ ", PTC_STR_84TYPEINFOLCSCOLOR=" + PTC_STR_84TYPEINFOLCSCOLOR + ", PTC_STR_85TYPEINFOLCSCOLOR="
				+ PTC_STR_85TYPEINFOLCSCOLOR + ", PTC_STR_86TYPEINFOLCSCOLOR=" + PTC_STR_86TYPEINFOLCSCOLOR
				+ ", PTC_STR_87TYPEINFOLCSCOLOR=" + PTC_STR_87TYPEINFOLCSCOLOR + ", PTC_STR_88TYPEINFOLCSCOLOR="
				+ PTC_STR_88TYPEINFOLCSCOLOR + ", PTC_STR_89TYPEINFOLCSCOLOR=" + PTC_STR_89TYPEINFOLCSCOLOR
				+ ", PTC_STR_90TYPEINFOLCSCOLOR=" + PTC_STR_90TYPEINFOLCSCOLOR + ", PTC_STR_91TYPEINFOLCSCOLOR="
				+ PTC_STR_91TYPEINFOLCSCOLOR + ", PTC_STR_92TYPEINFOLCSCOLOR=" + PTC_STR_92TYPEINFOLCSCOLOR
				+ ", PTC_STR_93TYPEINFOLCSCOLOR=" + PTC_STR_93TYPEINFOLCSCOLOR + ", PTC_STR_94TYPEINFOLCSCOLOR="
				+ PTC_STR_94TYPEINFOLCSCOLOR + ", PTC_STR_95TYPEINFOLCSCOLOR=" + PTC_STR_95TYPEINFOLCSCOLOR
				+ ", PTC_STR_96TYPEINFOLCSCOLOR=" + PTC_STR_96TYPEINFOLCSCOLOR + ", PTC_STR_97TYPEINFOLCSCOLOR="
				+ PTC_STR_97TYPEINFOLCSCOLOR + ", PTC_STR_98TYPEINFOLCSCOLOR=" + PTC_STR_98TYPEINFOLCSCOLOR
				+ ", PTC_STR_99TYPEINFOLCSCOLOR=" + PTC_STR_99TYPEINFOLCSCOLOR + ", PTC_STR_100TYPEINFOLCSCOLOR="
				+ PTC_STR_100TYPEINFOLCSCOLOR + ", PTC_LNG_1TYPEINFOLCSCOLOR=" + PTC_LNG_1TYPEINFOLCSCOLOR
				+ ", PTC_LNG_2TYPEINFOLCSCOLOR=" + PTC_LNG_2TYPEINFOLCSCOLOR + ", PTC_LNG_3TYPEINFOLCSCOLOR="
				+ PTC_LNG_3TYPEINFOLCSCOLOR + ", PTC_LNG_4TYPEINFOLCSCOLOR=" + PTC_LNG_4TYPEINFOLCSCOLOR
				+ ", PTC_LNG_5TYPEINFOLCSCOLOR=" + PTC_LNG_5TYPEINFOLCSCOLOR + ", PTC_LNG_6TYPEINFOLCSCOLOR="
				+ PTC_LNG_6TYPEINFOLCSCOLOR + ", PTC_LNG_7TYPEINFOLCSCOLOR=" + PTC_LNG_7TYPEINFOLCSCOLOR
				+ ", PTC_LNG_8TYPEINFOLCSCOLOR=" + PTC_LNG_8TYPEINFOLCSCOLOR + ", PTC_LNG_9TYPEINFOLCSCOLOR="
				+ PTC_LNG_9TYPEINFOLCSCOLOR + ", PTC_LNG_10TYPEINFOLCSCOLOR=" + PTC_LNG_10TYPEINFOLCSCOLOR
				+ ", PTC_TMS_1TYPEINFOLCSCOLOR=" + PTC_TMS_1TYPEINFOLCSCOLOR + ", PTC_TMS_2TYPEINFOLCSCOLOR="
				+ PTC_TMS_2TYPEINFOLCSCOLOR + ", PTC_TMS_3TYPEINFOLCSCOLOR=" + PTC_TMS_3TYPEINFOLCSCOLOR
				+ ", PTC_TMS_4TYPEINFOLCSCOLOR=" + PTC_TMS_4TYPEINFOLCSCOLOR + ", PTC_TMS_5TYPEINFOLCSCOLOR="
				+ PTC_TMS_5TYPEINFOLCSCOLOR + ", PTC_TMS_6TYPEINFOLCSCOLOR=" + PTC_TMS_6TYPEINFOLCSCOLOR
				+ ", PTC_TMS_7TYPEINFOLCSCOLOR=" + PTC_TMS_7TYPEINFOLCSCOLOR + ", PTC_TMS_8TYPEINFOLCSCOLOR="
				+ PTC_TMS_8TYPEINFOLCSCOLOR + ", PTC_TMS_9TYPEINFOLCSCOLOR=" + PTC_TMS_9TYPEINFOLCSCOLOR
				+ ", PTC_TMS_10TYPEINFOLCSCOLOR=" + PTC_TMS_10TYPEINFOLCSCOLOR + ", PTC_TMS_11TYPEINFOLCSCOLOR="
				+ PTC_TMS_11TYPEINFOLCSCOLOR + ", PTC_TMS_12TYPEINFOLCSCOLOR=" + PTC_TMS_12TYPEINFOLCSCOLOR
				+ ", PTC_TMS_13TYPEINFOLCSCOLOR=" + PTC_TMS_13TYPEINFOLCSCOLOR + ", PTC_TMS_14TYPEINFOLCSCOLOR="
				+ PTC_TMS_14TYPEINFOLCSCOLOR + ", PTC_TMS_15TYPEINFOLCSCOLOR=" + PTC_TMS_15TYPEINFOLCSCOLOR
				+ ", PTC_TMS_16TYPEINFOLCSCOLOR=" + PTC_TMS_16TYPEINFOLCSCOLOR + ", PTC_TMS_17TYPEINFOLCSCOLOR="
				+ PTC_TMS_17TYPEINFOLCSCOLOR + ", PTC_TMS_18TYPEINFOLCSCOLOR=" + PTC_TMS_18TYPEINFOLCSCOLOR
				+ ", PTC_TMS_19TYPEINFOLCSCOLOR=" + PTC_TMS_19TYPEINFOLCSCOLOR + ", PTC_TMS_20TYPEINFOLCSCOLOR="
				+ PTC_TMS_20TYPEINFOLCSCOLOR + ", PTC_TMS_21TYPEINFOLCSCOLOR=" + PTC_TMS_21TYPEINFOLCSCOLOR
				+ ", PTC_TMS_22TYPEINFOLCSCOLOR=" + PTC_TMS_22TYPEINFOLCSCOLOR + ", PTC_TMS_23TYPEINFOLCSCOLOR="
				+ PTC_TMS_23TYPEINFOLCSCOLOR + ", PTC_TMS_24TYPEINFOLCSCOLOR=" + PTC_TMS_24TYPEINFOLCSCOLOR
				+ ", PTC_TMS_25TYPEINFOLCSCOLOR=" + PTC_TMS_25TYPEINFOLCSCOLOR + ", PTC_TMS_26TYPEINFOLCSCOLOR="
				+ PTC_TMS_26TYPEINFOLCSCOLOR + ", PTC_TMS_27TYPEINFOLCSCOLOR=" + PTC_TMS_27TYPEINFOLCSCOLOR
				+ ", PTC_TMS_28TYPEINFOLCSCOLOR=" + PTC_TMS_28TYPEINFOLCSCOLOR + ", PTC_TMS_29TYPEINFOLCSCOLOR="
				+ PTC_TMS_29TYPEINFOLCSCOLOR + ", PTC_TMS_30TYPEINFOLCSCOLOR=" + PTC_TMS_30TYPEINFOLCSCOLOR
				+ ", PTC_BLN_1TYPEINFOLCSCOLOR=" + PTC_BLN_1TYPEINFOLCSCOLOR + ", PTC_BLN_2TYPEINFOLCSCOLOR="
				+ PTC_BLN_2TYPEINFOLCSCOLOR + ", PTC_BLN_3TYPEINFOLCSCOLOR=" + PTC_BLN_3TYPEINFOLCSCOLOR
				+ ", PTC_BLN_4TYPEINFOLCSCOLOR=" + PTC_BLN_4TYPEINFOLCSCOLOR + ", PTC_BLN_5TYPEINFOLCSCOLOR="
				+ PTC_BLN_5TYPEINFOLCSCOLOR + ", PTC_BLN_6TYPEINFOLCSCOLOR=" + PTC_BLN_6TYPEINFOLCSCOLOR
				+ ", PTC_BLN_7TYPEINFOLCSCOLOR=" + PTC_BLN_7TYPEINFOLCSCOLOR + ", PTC_BLN_8TYPEINFOLCSCOLOR="
				+ PTC_BLN_8TYPEINFOLCSCOLOR + ", PTC_BLN_9TYPEINFOLCSCOLOR=" + PTC_BLN_9TYPEINFOLCSCOLOR
				+ ", PTC_BLN_10TYPEINFOLCSCOLOR=" + PTC_BLN_10TYPEINFOLCSCOLOR + "]";
	}

	
*/}
