package com.qiwkreport.qiwk.etl.domain;

import java.security.Timestamp;
import java.util.Date;

public class QiwkMaterial implements java.io.Serializable {
	

		private int primaryKey;
		private int BRANCHID;
		private int IDA3MASTERREFERENCE;
		private int IDA2A2;
		private Date CREATESTAMPA2;
		private Date UPDATESTAMPA2;
		private Date DATELOCK;
		private String FLEXTYPEIDPATH;
		private String LIFECYCLE;
		private int FLEXTYPEID;
		private int UPDATECOUNTA2;
		private int MARKEDFORDELETEA2;
		private Timestamp LOADERCREATESTAMP;
		private Timestamp LOADERUPDATESTAMP;

		private String PTC_STR_1TYPEINFOLCSMATERIAL;
		private String PTC_STR_2TYPEINFOLCSMATERIAL;
		private String PTC_STR_3TYPEINFOLCSMATERIAL;
		private String PTC_STR_4TYPEINFOLCSMATERIAL;
		private String PTC_STR_5TYPEINFOLCSMATERIAL;
		private String PTC_STR_6TYPEINFOLCSMATERIAL;
		private String PTC_STR_7TYPEINFOLCSMATERIAL;
		private String PTC_STR_8TYPEINFOLCSMATERIAL;
		private String PTC_STR_9TYPEINFOLCSMATERIAL;
		private String PTC_STR_10TYPEINFOLCSMATERIA;
		private String PTC_STR_11TYPEINFOLCSMATERIA;
		private String PTC_STR_12TYPEINFOLCSMATERIA;
		private String PTC_STR_13TYPEINFOLCSMATERIA;
		private String PTC_STR_14TYPEINFOLCSMATERIA;
		private String PTC_STR_15TYPEINFOLCSMATERIA;
		private String PTC_STR_16TYPEINFOLCSMATERIA;
		private String PTC_STR_17TYPEINFOLCSMATERIA;
		private String PTC_STR_18TYPEINFOLCSMATERIA;
		private String PTC_STR_19TYPEINFOLCSMATERIA;
		private String PTC_STR_20TYPEINFOLCSMATERIA;
		private String PTC_STR_21TYPEINFOLCSMATERIA;
		private String PTC_STR_22TYPEINFOLCSMATERIA;
		private String PTC_STR_23TYPEINFOLCSMATERIA;
		private String PTC_STR_24TYPEINFOLCSMATERIA;
		private String PTC_STR_25TYPEINFOLCSMATERIA;
		private String PTC_STR_26TYPEINFOLCSMATERIA;
		private String PTC_STR_27TYPEINFOLCSMATERIA;
		private String PTC_STR_28TYPEINFOLCSMATERIA;
		private String PTC_STR_29TYPEINFOLCSMATERIA;
		private String PTC_STR_30TYPEINFOLCSMATERIA;
		private String PTC_STR_31TYPEINFOLCSMATERIA;
		private String PTC_STR_32TYPEINFOLCSMATERIA;
		private String PTC_STR_33TYPEINFOLCSMATERIA;
		private String PTC_STR_34TYPEINFOLCSMATERIA;
		private String PTC_STR_35TYPEINFOLCSMATERIA;
		private String PTC_STR_36TYPEINFOLCSMATERIA;
		private String PTC_STR_37TYPEINFOLCSMATERIA;
		private String PTC_STR_38TYPEINFOLCSMATERIA;
		private String PTC_STR_39TYPEINFOLCSMATERIA;
		private String PTC_STR_40TYPEINFOLCSMATERIA;
		private String PTC_STR_41TYPEINFOLCSMATERIA;
		private String PTC_STR_42TYPEINFOLCSMATERIA;
		private String PTC_STR_43TYPEINFOLCSMATERIA;
		private String PTC_STR_44TYPEINFOLCSMATERIA;
		private String PTC_STR_45TYPEINFOLCSMATERIA;
		private String PTC_STR_46TYPEINFOLCSMATERIA;
		private String PTC_STR_47TYPEINFOLCSMATERIA;
		private String PTC_STR_48TYPEINFOLCSMATERIA;
		private String PTC_STR_49TYPEINFOLCSMATERIA;
		private String PTC_STR_50TYPEINFOLCSMATERIA;
		private String PTC_STR_51TYPEINFOLCSMATERIA;
		private String PTC_STR_52TYPEINFOLCSMATERIA;
		private String PTC_STR_53TYPEINFOLCSMATERIA;
		private String PTC_STR_54TYPEINFOLCSMATERIA;
		private String PTC_STR_55TYPEINFOLCSMATERIA;
		private String PTC_STR_56TYPEINFOLCSMATERIA;
		private String PTC_STR_57TYPEINFOLCSMATERIA;
		private String PTC_STR_58TYPEINFOLCSMATERIA;
		private String PTC_STR_59TYPEINFOLCSMATERIA;
		private String PTC_STR_60TYPEINFOLCSMATERIA;
		private String PTC_STR_61TYPEINFOLCSMATERIA;
		private String PTC_STR_62TYPEINFOLCSMATERIA;
		private String PTC_STR_63TYPEINFOLCSMATERIA;
		private String PTC_STR_64TYPEINFOLCSMATERIA;
		private String PTC_STR_65TYPEINFOLCSMATERIA;
		private String PTC_STR_66TYPEINFOLCSMATERIA;
		private String PTC_STR_67TYPEINFOLCSMATERIA;
		private String PTC_STR_68TYPEINFOLCSMATERIA;
		private String PTC_STR_69TYPEINFOLCSMATERIA;
		private String PTC_STR_70TYPEINFOLCSMATERIA;
		private String PTC_STR_71TYPEINFOLCSMATERIA;
		private String PTC_STR_72TYPEINFOLCSMATERIA;
		private String PTC_STR_73TYPEINFOLCSMATERIA;
		private String PTC_STR_74TYPEINFOLCSMATERIA;
		private String PTC_STR_75TYPEINFOLCSMATERIA;
		private String PTC_STR_76TYPEINFOLCSMATERIA;
		private String PTC_STR_77TYPEINFOLCSMATERIA;
		private String PTC_STR_78TYPEINFOLCSMATERIA;
		private String PTC_STR_79TYPEINFOLCSMATERIA;
		private String PTC_STR_80TYPEINFOLCSMATERIA;
		private String PTC_STR_81TYPEINFOLCSMATERIA;
		private String PTC_STR_82TYPEINFOLCSMATERIA;
		private String PTC_STR_83TYPEINFOLCSMATERIA;
		private String PTC_STR_84TYPEINFOLCSMATERIA;
		private String PTC_STR_85TYPEINFOLCSMATERIA;
		private String PTC_STR_86TYPEINFOLCSMATERIA;
		private String PTC_STR_87TYPEINFOLCSMATERIA;
		private String PTC_STR_88TYPEINFOLCSMATERIA;
		private String PTC_STR_89TYPEINFOLCSMATERIA;
		private String PTC_STR_90TYPEINFOLCSMATERIA;

		// double
		private double PTC_DBL_1TYPEINFOLCSMATERIAL;
		private double PTC_DBL_2TYPEINFOLCSMATERIAL;
		private double PTC_DBL_3TYPEINFOLCSMATERIAL;
		private double PTC_DBL_4TYPEINFOLCSMATERIAL;
		private double PTC_DBL_5TYPEINFOLCSMATERIAL;
		private double PTC_DBL_6TYPEINFOLCSMATERIAL;
		private double PTC_DBL_7TYPEINFOLCSMATERIAL;
		private double PTC_DBL_8TYPEINFOLCSMATERIAL;
		private double PTC_DBL_9TYPEINFOLCSMATERIAL;
		private double PTC_DBL_10TYPEINFOLCSMATERIA;
		private double PTC_DBL_11TYPEINFOLCSMATERIA;
		private double PTC_DBL_12TYPEINFOLCSMATERIA;
		private double PTC_DBL_13TYPEINFOLCSMATERIA;
		private double PTC_DBL_14TYPEINFOLCSMATERIA;
		private double PTC_DBL_15TYPEINFOLCSMATERIA;
		private double PTC_DBL_16TYPEINFOLCSMATERIA;
		private double PTC_DBL_17TYPEINFOLCSMATERIA;
		private double PTC_DBL_18TYPEINFOLCSMATERIA;
		private double PTC_DBL_19TYPEINFOLCSMATERIA;
		private double PTC_DBL_20TYPEINFOLCSMATERIA;
		private double PTC_DBL_21TYPEINFOLCSMATERIA;
		private double PTC_DBL_22TYPEINFOLCSMATERIA;
		private double PTC_DBL_23TYPEINFOLCSMATERIA;
		private double PTC_DBL_24TYPEINFOLCSMATERIA;
		private double PTC_DBL_25TYPEINFOLCSMATERIA;
		private double PTC_DBL_26TYPEINFOLCSMATERIA;
		private double PTC_DBL_27TYPEINFOLCSMATERIA;
		private double PTC_DBL_28TYPEINFOLCSMATERIA;
		private double PTC_DBL_29TYPEINFOLCSMATERIA;
		private double PTC_DBL_30TYPEINFOLCSMATERIA;
		private double PTC_DBL_31TYPEINFOLCSMATERIA;
		private double PTC_DBL_32TYPEINFOLCSMATERIA;
		private double PTC_DBL_33TYPEINFOLCSMATERIA;
		private double PTC_DBL_34TYPEINFOLCSMATERIA;
		private double PTC_DBL_35TYPEINFOLCSMATERIA;
		private double PTC_DBL_36TYPEINFOLCSMATERIA;
		private double PTC_DBL_37TYPEINFOLCSMATERIA;
		private double PTC_DBL_38TYPEINFOLCSMATERIA;
		private double PTC_DBL_39TYPEINFOLCSMATERIA;
		private double PTC_DBL_40TYPEINFOLCSMATERIA;
		private double PTC_DBL_41TYPEINFOLCSMATERIA;
		private double PTC_DBL_42TYPEINFOLCSMATERIA;
		private double PTC_DBL_43TYPEINFOLCSMATERIA;
		private double PTC_DBL_44TYPEINFOLCSMATERIA;
		private double PTC_DBL_45TYPEINFOLCSMATERIA;
		private double PTC_DBL_46TYPEINFOLCSMATERIA;
		private double PTC_DBL_47TYPEINFOLCSMATERIA;
		private double PTC_DBL_48TYPEINFOLCSMATERIA;
		private double PTC_DBL_49TYPEINFOLCSMATERIA;
		private double PTC_DBL_50TYPEINFOLCSMATERIA;
		private double PTC_DBL_51TYPEINFOLCSMATERIA;
		private double PTC_DBL_52TYPEINFOLCSMATERIA;
		private double PTC_DBL_53TYPEINFOLCSMATERIA;
		private double PTC_DBL_54TYPEINFOLCSMATERIA;
		private double PTC_DBL_55TYPEINFOLCSMATERIA;

		// long 
		private long PTC_LNG_1TYPEINFOLCSMATERIAL;
		private long PTC_LNG_2TYPEINFOLCSMATERIAL;
		private long PTC_LNG_3TYPEINFOLCSMATERIAL;
		private long PTC_LNG_4TYPEINFOLCSMATERIAL;
		private long PTC_LNG_5TYPEINFOLCSMATERIAL;
		private long PTC_LNG_6TYPEINFOLCSMATERIAL;

		// boolean
		private String PTC_BLN_1TYPEINFOLCSMATERIAL;
		private String PTC_BLN_2TYPEINFOLCSMATERIAL;
		private String PTC_BLN_3TYPEINFOLCSMATERIAL;
		private String PTC_BLN_4TYPEINFOLCSMATERIAL;
		private String PTC_BLN_5TYPEINFOLCSMATERIAL;

		// tms
			private Date  PTC_TMS_1TYPEINFOLCSMATERIAL;
			private Date  PTC_TMS_2TYPEINFOLCSMATERIAL;
			private Date  PTC_TMS_3TYPEINFOLCSMATERIAL;
			private Date  PTC_TMS_4TYPEINFOLCSMATERIAL;
			private Date  PTC_TMS_5TYPEINFOLCSMATERIAL;
			private Date  PTC_TMS_6TYPEINFOLCSMATERIAL;
			private Date  PTC_TMS_7TYPEINFOLCSMATERIAL;
			private Date  PTC_TMS_8TYPEINFOLCSMATERIAL;
			private Date  PTC_TMS_9TYPEINFOLCSMATERIAL;
			private Date  PTC_TMS_10TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_11TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_12TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_13TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_14TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_15TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_16TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_17TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_18TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_19TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_20TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_21TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_22TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_23TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_24TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_25TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_26TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_27TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_28TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_29TYPEINFOLCSMATERIA;
			private Date  PTC_TMS_30TYPEINFOLCSMATERIA;
		


		public int getPrimaryKey() {
			return primaryKey;
		}
		public void setPrimaryKey(int primaryKey) {
			this.primaryKey = primaryKey;
		}
		public int getBRANCHID() {
			return BRANCHID;
		}
		public void setBRANCHID(int bRANCHID) {
			BRANCHID = bRANCHID;
		}	
		public int getIDA3MASTERREFERENCE() {
			return IDA3MASTERREFERENCE;
		}
		public void setIDA3MASTERREFERENCE(int iDA3MASTERREFERENCE) {
			IDA3MASTERREFERENCE = iDA3MASTERREFERENCE;
		}
		public int getIDA2A2() {
			return IDA2A2;
		}
		public void setIDA2A2(int iDA2A2) {
			IDA2A2 = iDA2A2;
		}
		public Date getCREATESTAMPA2() {
			return CREATESTAMPA2;
		}
		public void setCREATESTAMPA2(Date cREATESTAMPA2) {
			CREATESTAMPA2 = cREATESTAMPA2;
		}
		public Date getUPDATESTAMPA2() {
			return UPDATESTAMPA2;
		}
		public void setUPDATESTAMPA2(Date uPDATESTAMPA2) {
			UPDATESTAMPA2 = uPDATESTAMPA2;
		}
		public Date getDATELOCK() {
			return DATELOCK;
		}
		public void setDATELOCK(Date dATELOCK) {
			DATELOCK = dATELOCK;
		}
		public String getFLEXTYPEIDPATH() {
			return FLEXTYPEIDPATH;
		}
		public void setFLEXTYPEIDPATH(String fLEXTYPEIDPATH) {
			FLEXTYPEIDPATH = fLEXTYPEIDPATH;
		}
		public String getLIFECYCLE() {
			return LIFECYCLE;
		}
		public void setLIFECYCLE(String lIFECYCLE) {
			LIFECYCLE = lIFECYCLE;
		}
		public int getFLEXTYPEID() {
			return FLEXTYPEID;
		}
		public void setFLEXTYPEID(int fLEXTYPEID) {
			FLEXTYPEID = fLEXTYPEID;
		}
		public int getUPDATECOUNTA2() {
			return UPDATECOUNTA2;
		}
		public void setUPDATECOUNTA2(int uPDATECOUNTA2) {
			UPDATECOUNTA2 = uPDATECOUNTA2;
		}
		public int getMARKEDFORDELETEA2() {
			return MARKEDFORDELETEA2;
		}
		public void setMARKEDFORDELETEA2(int mARKEDFORDELETEA2) {
			MARKEDFORDELETEA2 = mARKEDFORDELETEA2;
		}
		public Timestamp getLOADERCREATESTAMP() {
			return LOADERCREATESTAMP;
		}
		public void setLOADERCREATESTAMP(Timestamp lOADERCREATESTAMP) {
			LOADERCREATESTAMP = lOADERCREATESTAMP;
		}
		public Timestamp getLOADERUPDATESTAMP() {
			return LOADERUPDATESTAMP;
		}
		public void setLOADERUPDATESTAMP(Timestamp lOADERUPDATESTAMP) {
			LOADERUPDATESTAMP = lOADERUPDATESTAMP;
		}
		public String getPTC_STR_1TYPEINFOLCSMATERIAL() {
			return PTC_STR_1TYPEINFOLCSMATERIAL;
		}
		public void setPTC_STR_1TYPEINFOLCSMATERIAL(String pTC_STR_1TYPEINFOLCSMATERIAL) {
			PTC_STR_1TYPEINFOLCSMATERIAL = pTC_STR_1TYPEINFOLCSMATERIAL;
		}
		public String getPTC_STR_2TYPEINFOLCSMATERIAL() {
			return PTC_STR_2TYPEINFOLCSMATERIAL;
		}
		public void setPTC_STR_2TYPEINFOLCSMATERIAL(String pTC_STR_2TYPEINFOLCSMATERIAL) {
			PTC_STR_2TYPEINFOLCSMATERIAL = pTC_STR_2TYPEINFOLCSMATERIAL;
		}
		public String getPTC_STR_3TYPEINFOLCSMATERIAL() {
			return PTC_STR_3TYPEINFOLCSMATERIAL;
		}
		public void setPTC_STR_3TYPEINFOLCSMATERIAL(String pTC_STR_3TYPEINFOLCSMATERIAL) {
			PTC_STR_3TYPEINFOLCSMATERIAL = pTC_STR_3TYPEINFOLCSMATERIAL;
		}
		public String getPTC_STR_4TYPEINFOLCSMATERIAL() {
			return PTC_STR_4TYPEINFOLCSMATERIAL;
		}
		public void setPTC_STR_4TYPEINFOLCSMATERIAL(String pTC_STR_4TYPEINFOLCSMATERIAL) {
			PTC_STR_4TYPEINFOLCSMATERIAL = pTC_STR_4TYPEINFOLCSMATERIAL;
		}

		public String getPTC_STR_5TYPEINFOLCSMATERIAL() {
			return PTC_STR_5TYPEINFOLCSMATERIAL;
		}
		public void setPTC_STR_5TYPEINFOLCSMATERIAL(String pTC_STR_5TYPEINFOLCSMATERIAL) {
			PTC_STR_5TYPEINFOLCSMATERIAL = pTC_STR_5TYPEINFOLCSMATERIAL;
		}
		public String getPTC_STR_6TYPEINFOLCSMATERIAL() {
			return PTC_STR_6TYPEINFOLCSMATERIAL;
		}
		public void setPTC_STR_6TYPEINFOLCSMATERIAL(String pTC_STR_6TYPEINFOLCSMATERIAL) {
			PTC_STR_6TYPEINFOLCSMATERIAL = pTC_STR_6TYPEINFOLCSMATERIAL;
		}
		public String getPTC_STR_7TYPEINFOLCSMATERIAL() {
			return PTC_STR_7TYPEINFOLCSMATERIAL;
		}
		public void setPTC_STR_7TYPEINFOLCSMATERIAL(String pTC_STR_7TYPEINFOLCSMATERIAL) {
			PTC_STR_7TYPEINFOLCSMATERIAL = pTC_STR_7TYPEINFOLCSMATERIAL;
		}
		public String getPTC_STR_8TYPEINFOLCSMATERIAL() {
			return PTC_STR_8TYPEINFOLCSMATERIAL;
		}
		public void setPTC_STR_8TYPEINFOLCSMATERIAL(String pTC_STR_8TYPEINFOLCSMATERIAL) {
			PTC_STR_8TYPEINFOLCSMATERIAL = pTC_STR_8TYPEINFOLCSMATERIAL;
		}
		public String getPTC_STR_9TYPEINFOLCSMATERIAL() {
			return PTC_STR_9TYPEINFOLCSMATERIAL;
		}
		public void setPTC_STR_9TYPEINFOLCSMATERIAL(String pTC_STR_9TYPEINFOLCSMATERIAL) {
			PTC_STR_9TYPEINFOLCSMATERIAL = pTC_STR_9TYPEINFOLCSMATERIAL;
		}
		public String getPTC_STR_10TYPEINFOLCSMATERIA() {
			return PTC_STR_10TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_10TYPEINFOLCSMATERIA(String pTC_STR_10TYPEINFOLCSMATERIA) {
			PTC_STR_10TYPEINFOLCSMATERIA = pTC_STR_10TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_11TYPEINFOLCSMATERIA() {
			return PTC_STR_11TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_11TYPEINFOLCSMATERIA(String pTC_STR_11TYPEINFOLCSMATERIA) {
			PTC_STR_11TYPEINFOLCSMATERIA = pTC_STR_11TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_12TYPEINFOLCSMATERIA() {
			return PTC_STR_12TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_12TYPEINFOLCSMATERIA(String pTC_STR_12TYPEINFOLCSMATERIA) {
			PTC_STR_12TYPEINFOLCSMATERIA = pTC_STR_12TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_13TYPEINFOLCSMATERIA() {
			return PTC_STR_13TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_13TYPEINFOLCSMATERIA(String pTC_STR_13TYPEINFOLCSMATERIA) {
			PTC_STR_13TYPEINFOLCSMATERIA = pTC_STR_13TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_14TYPEINFOLCSMATERIA() {
			return PTC_STR_14TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_14TYPEINFOLCSMATERIA(String pTC_STR_14TYPEINFOLCSMATERIA) {
			PTC_STR_14TYPEINFOLCSMATERIA = pTC_STR_14TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_15TYPEINFOLCSMATERIA() {
			return PTC_STR_15TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_15TYPEINFOLCSMATERIA(String pTC_STR_15TYPEINFOLCSMATERIA) {
			PTC_STR_15TYPEINFOLCSMATERIA = pTC_STR_15TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_16TYPEINFOLCSMATERIA() {
			return PTC_STR_16TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_16TYPEINFOLCSMATERIA(String pTC_STR_16TYPEINFOLCSMATERIA) {
			PTC_STR_16TYPEINFOLCSMATERIA = pTC_STR_16TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_17TYPEINFOLCSMATERIA() {
			return PTC_STR_17TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_17TYPEINFOLCSMATERIA(String pTC_STR_17TYPEINFOLCSMATERIA) {
			PTC_STR_17TYPEINFOLCSMATERIA = pTC_STR_17TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_18TYPEINFOLCSMATERIA() {
			return PTC_STR_18TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_18TYPEINFOLCSMATERIA(String pTC_STR_18TYPEINFOLCSMATERIA) {
			PTC_STR_18TYPEINFOLCSMATERIA = pTC_STR_18TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_19TYPEINFOLCSMATERIA() {
			return PTC_STR_19TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_19TYPEINFOLCSMATERIA(String pTC_STR_19TYPEINFOLCSMATERIA) {
			PTC_STR_19TYPEINFOLCSMATERIA = pTC_STR_19TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_20TYPEINFOLCSMATERIA() {
			return PTC_STR_20TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_20TYPEINFOLCSMATERIA(String pTC_STR_20TYPEINFOLCSMATERIA) {
			PTC_STR_20TYPEINFOLCSMATERIA = pTC_STR_20TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_21TYPEINFOLCSMATERIA() {
			return PTC_STR_21TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_21TYPEINFOLCSMATERIA(String pTC_STR_21TYPEINFOLCSMATERIA) {
			PTC_STR_21TYPEINFOLCSMATERIA = pTC_STR_21TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_22TYPEINFOLCSMATERIA() {
			return PTC_STR_22TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_22TYPEINFOLCSMATERIA(String pTC_STR_22TYPEINFOLCSMATERIA) {
			PTC_STR_22TYPEINFOLCSMATERIA = pTC_STR_22TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_23TYPEINFOLCSMATERIA() {
			return PTC_STR_23TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_23TYPEINFOLCSMATERIA(String pTC_STR_23TYPEINFOLCSMATERIA) {
			PTC_STR_23TYPEINFOLCSMATERIA = pTC_STR_23TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_24TYPEINFOLCSMATERIA() {
			return PTC_STR_24TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_24TYPEINFOLCSMATERIA(String pTC_STR_24TYPEINFOLCSMATERIA) {
			PTC_STR_24TYPEINFOLCSMATERIA = pTC_STR_24TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_25TYPEINFOLCSMATERIA() {
			return PTC_STR_25TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_25TYPEINFOLCSMATERIA(String pTC_STR_25TYPEINFOLCSMATERIA) {
			PTC_STR_25TYPEINFOLCSMATERIA = pTC_STR_25TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_26TYPEINFOLCSMATERIA() {
			return PTC_STR_26TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_26TYPEINFOLCSMATERIA(String pTC_STR_26TYPEINFOLCSMATERIA) {
			PTC_STR_26TYPEINFOLCSMATERIA = pTC_STR_26TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_27TYPEINFOLCSMATERIA() {
			return PTC_STR_27TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_27TYPEINFOLCSMATERIA(String pTC_STR_27TYPEINFOLCSMATERIA) {
			PTC_STR_27TYPEINFOLCSMATERIA = pTC_STR_27TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_28TYPEINFOLCSMATERIA() {
			return PTC_STR_28TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_28TYPEINFOLCSMATERIA(String pTC_STR_28TYPEINFOLCSMATERIA) {
			PTC_STR_28TYPEINFOLCSMATERIA = pTC_STR_28TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_29TYPEINFOLCSMATERIA() {
			return PTC_STR_29TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_29TYPEINFOLCSMATERIA(String pTC_STR_29TYPEINFOLCSMATERIA) {
			PTC_STR_29TYPEINFOLCSMATERIA = pTC_STR_29TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_30TYPEINFOLCSMATERIA() {
			return PTC_STR_30TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_30TYPEINFOLCSMATERIA(String pTC_STR_30TYPEINFOLCSMATERIA) {
			PTC_STR_30TYPEINFOLCSMATERIA = pTC_STR_30TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_31TYPEINFOLCSMATERIA() {
			return PTC_STR_31TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_31TYPEINFOLCSMATERIA(String pTC_STR_31TYPEINFOLCSMATERIA) {
			PTC_STR_31TYPEINFOLCSMATERIA = pTC_STR_31TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_32TYPEINFOLCSMATERIA() {
			return PTC_STR_32TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_32TYPEINFOLCSMATERIA(String pTC_STR_32TYPEINFOLCSMATERIA) {
			PTC_STR_32TYPEINFOLCSMATERIA = pTC_STR_32TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_33TYPEINFOLCSMATERIA() {
			return PTC_STR_33TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_33TYPEINFOLCSMATERIA(String pTC_STR_33TYPEINFOLCSMATERIA) {
			PTC_STR_33TYPEINFOLCSMATERIA = pTC_STR_33TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_34TYPEINFOLCSMATERIA() {
			return PTC_STR_34TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_34TYPEINFOLCSMATERIA(String pTC_STR_34TYPEINFOLCSMATERIA) {
			PTC_STR_34TYPEINFOLCSMATERIA = pTC_STR_34TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_35TYPEINFOLCSMATERIA() {
			return PTC_STR_35TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_35TYPEINFOLCSMATERIA(String pTC_STR_35TYPEINFOLCSMATERIA) {
			PTC_STR_35TYPEINFOLCSMATERIA = pTC_STR_35TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_36TYPEINFOLCSMATERIA() {
			return PTC_STR_36TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_36TYPEINFOLCSMATERIA(String pTC_STR_36TYPEINFOLCSMATERIA) {
			PTC_STR_36TYPEINFOLCSMATERIA = pTC_STR_36TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_37TYPEINFOLCSMATERIA() {
			return PTC_STR_37TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_37TYPEINFOLCSMATERIA(String pTC_STR_37TYPEINFOLCSMATERIA) {
			PTC_STR_37TYPEINFOLCSMATERIA = pTC_STR_37TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_38TYPEINFOLCSMATERIA() {
			return PTC_STR_38TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_38TYPEINFOLCSMATERIA(String pTC_STR_38TYPEINFOLCSMATERIA) {
			PTC_STR_38TYPEINFOLCSMATERIA = pTC_STR_38TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_39TYPEINFOLCSMATERIA() {
			return PTC_STR_39TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_39TYPEINFOLCSMATERIA(String pTC_STR_39TYPEINFOLCSMATERIA) {
			PTC_STR_39TYPEINFOLCSMATERIA = pTC_STR_39TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_40TYPEINFOLCSMATERIA() {
			return PTC_STR_40TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_40TYPEINFOLCSMATERIA(String pTC_STR_40TYPEINFOLCSMATERIA) {
			PTC_STR_40TYPEINFOLCSMATERIA = pTC_STR_40TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_41TYPEINFOLCSMATERIA() {
			return PTC_STR_41TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_41TYPEINFOLCSMATERIA(String pTC_STR_41TYPEINFOLCSMATERIA) {
			PTC_STR_41TYPEINFOLCSMATERIA = pTC_STR_41TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_42TYPEINFOLCSMATERIA() {
			return PTC_STR_42TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_42TYPEINFOLCSMATERIA(String pTC_STR_42TYPEINFOLCSMATERIA) {
			PTC_STR_42TYPEINFOLCSMATERIA = pTC_STR_42TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_43TYPEINFOLCSMATERIA() {
			return PTC_STR_43TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_43TYPEINFOLCSMATERIA(String pTC_STR_43TYPEINFOLCSMATERIA) {
			PTC_STR_43TYPEINFOLCSMATERIA = pTC_STR_43TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_44TYPEINFOLCSMATERIA() {
			return PTC_STR_44TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_44TYPEINFOLCSMATERIA(String pTC_STR_44TYPEINFOLCSMATERIA) {
			PTC_STR_44TYPEINFOLCSMATERIA = pTC_STR_44TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_45TYPEINFOLCSMATERIA() {
			return PTC_STR_45TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_45TYPEINFOLCSMATERIA(String pTC_STR_45TYPEINFOLCSMATERIA) {
			PTC_STR_45TYPEINFOLCSMATERIA = pTC_STR_45TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_46TYPEINFOLCSMATERIA() {
			return PTC_STR_46TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_46TYPEINFOLCSMATERIA(String pTC_STR_46TYPEINFOLCSMATERIA) {
			PTC_STR_46TYPEINFOLCSMATERIA = pTC_STR_46TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_47TYPEINFOLCSMATERIA() {
			return PTC_STR_47TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_47TYPEINFOLCSMATERIA(String pTC_STR_47TYPEINFOLCSMATERIA) {
			PTC_STR_47TYPEINFOLCSMATERIA = pTC_STR_47TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_48TYPEINFOLCSMATERIA() {
			return PTC_STR_48TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_48TYPEINFOLCSMATERIA(String pTC_STR_48TYPEINFOLCSMATERIA) {
			PTC_STR_48TYPEINFOLCSMATERIA = pTC_STR_48TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_49TYPEINFOLCSMATERIA() {
			return PTC_STR_49TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_49TYPEINFOLCSMATERIA(String pTC_STR_49TYPEINFOLCSMATERIA) {
			PTC_STR_49TYPEINFOLCSMATERIA = pTC_STR_49TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_50TYPEINFOLCSMATERIA() {
			return PTC_STR_50TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_50TYPEINFOLCSMATERIA(String pTC_STR_50TYPEINFOLCSMATERIA) {
			PTC_STR_50TYPEINFOLCSMATERIA = pTC_STR_50TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_51TYPEINFOLCSMATERIA() {
			return PTC_STR_51TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_51TYPEINFOLCSMATERIA(String pTC_STR_51TYPEINFOLCSMATERIA) {
			PTC_STR_51TYPEINFOLCSMATERIA = pTC_STR_51TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_52TYPEINFOLCSMATERIA() {
			return PTC_STR_52TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_52TYPEINFOLCSMATERIA(String pTC_STR_52TYPEINFOLCSMATERIA) {
			PTC_STR_52TYPEINFOLCSMATERIA = pTC_STR_52TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_53TYPEINFOLCSMATERIA() {
			return PTC_STR_53TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_53TYPEINFOLCSMATERIA(String pTC_STR_53TYPEINFOLCSMATERIA) {
			PTC_STR_53TYPEINFOLCSMATERIA = pTC_STR_53TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_54TYPEINFOLCSMATERIA() {
			return PTC_STR_54TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_54TYPEINFOLCSMATERIA(String pTC_STR_54TYPEINFOLCSMATERIA) {
			PTC_STR_54TYPEINFOLCSMATERIA = pTC_STR_54TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_55TYPEINFOLCSMATERIA() {
			return PTC_STR_55TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_55TYPEINFOLCSMATERIA(String pTC_STR_55TYPEINFOLCSMATERIA) {
			PTC_STR_55TYPEINFOLCSMATERIA = pTC_STR_55TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_56TYPEINFOLCSMATERIA() {
			return PTC_STR_56TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_56TYPEINFOLCSMATERIA(String pTC_STR_56TYPEINFOLCSMATERIA) {
			PTC_STR_56TYPEINFOLCSMATERIA = pTC_STR_56TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_57TYPEINFOLCSMATERIA() {
			return PTC_STR_57TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_57TYPEINFOLCSMATERIA(String pTC_STR_57TYPEINFOLCSMATERIA) {
			PTC_STR_57TYPEINFOLCSMATERIA = pTC_STR_57TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_58TYPEINFOLCSMATERIA() {
			return PTC_STR_58TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_58TYPEINFOLCSMATERIA(String pTC_STR_58TYPEINFOLCSMATERIA) {
			PTC_STR_58TYPEINFOLCSMATERIA = pTC_STR_58TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_59TYPEINFOLCSMATERIA() {
			return PTC_STR_59TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_59TYPEINFOLCSMATERIA(String pTC_STR_59TYPEINFOLCSMATERIA) {
			PTC_STR_59TYPEINFOLCSMATERIA = pTC_STR_59TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_60TYPEINFOLCSMATERIA() {
			return PTC_STR_60TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_60TYPEINFOLCSMATERIA(String pTC_STR_60TYPEINFOLCSMATERIA) {
			PTC_STR_60TYPEINFOLCSMATERIA = pTC_STR_60TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_61TYPEINFOLCSMATERIA() {
			return PTC_STR_61TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_61TYPEINFOLCSMATERIA(String pTC_STR_61TYPEINFOLCSMATERIA) {
			PTC_STR_61TYPEINFOLCSMATERIA = pTC_STR_61TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_62TYPEINFOLCSMATERIA() {
			return PTC_STR_62TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_62TYPEINFOLCSMATERIA(String pTC_STR_62TYPEINFOLCSMATERIA) {
			PTC_STR_62TYPEINFOLCSMATERIA = pTC_STR_62TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_63TYPEINFOLCSMATERIA() {
			return PTC_STR_63TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_63TYPEINFOLCSMATERIA(String pTC_STR_63TYPEINFOLCSMATERIA) {
			PTC_STR_63TYPEINFOLCSMATERIA = pTC_STR_63TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_64TYPEINFOLCSMATERIA() {
			return PTC_STR_64TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_64TYPEINFOLCSMATERIA(String pTC_STR_64TYPEINFOLCSMATERIA) {
			PTC_STR_64TYPEINFOLCSMATERIA = pTC_STR_64TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_65TYPEINFOLCSMATERIA() {
			return PTC_STR_65TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_65TYPEINFOLCSMATERIA(String pTC_STR_65TYPEINFOLCSMATERIA) {
			PTC_STR_65TYPEINFOLCSMATERIA = pTC_STR_65TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_66TYPEINFOLCSMATERIA() {
			return PTC_STR_66TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_66TYPEINFOLCSMATERIA(String pTC_STR_66TYPEINFOLCSMATERIA) {
			PTC_STR_66TYPEINFOLCSMATERIA = pTC_STR_66TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_67TYPEINFOLCSMATERIA() {
			return PTC_STR_67TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_67TYPEINFOLCSMATERIA(String pTC_STR_67TYPEINFOLCSMATERIA) {
			PTC_STR_67TYPEINFOLCSMATERIA = pTC_STR_67TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_68TYPEINFOLCSMATERIA() {
			return PTC_STR_68TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_68TYPEINFOLCSMATERIA(String pTC_STR_68TYPEINFOLCSMATERIA) {
			PTC_STR_68TYPEINFOLCSMATERIA = pTC_STR_68TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_69TYPEINFOLCSMATERIA() {
			return PTC_STR_69TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_69TYPEINFOLCSMATERIA(String pTC_STR_69TYPEINFOLCSMATERIA) {
			PTC_STR_69TYPEINFOLCSMATERIA = pTC_STR_69TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_70TYPEINFOLCSMATERIA() {
			return PTC_STR_70TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_70TYPEINFOLCSMATERIA(String pTC_STR_70TYPEINFOLCSMATERIA) {
			PTC_STR_70TYPEINFOLCSMATERIA = pTC_STR_70TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_71TYPEINFOLCSMATERIA() {
			return PTC_STR_71TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_71TYPEINFOLCSMATERIA(String pTC_STR_71TYPEINFOLCSMATERIA) {
			PTC_STR_71TYPEINFOLCSMATERIA = pTC_STR_71TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_72TYPEINFOLCSMATERIA() {
			return PTC_STR_72TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_72TYPEINFOLCSMATERIA(String pTC_STR_72TYPEINFOLCSMATERIA) {
			PTC_STR_72TYPEINFOLCSMATERIA = pTC_STR_72TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_73TYPEINFOLCSMATERIA() {
			return PTC_STR_73TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_73TYPEINFOLCSMATERIA(String pTC_STR_73TYPEINFOLCSMATERIA) {
			PTC_STR_73TYPEINFOLCSMATERIA = pTC_STR_73TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_74TYPEINFOLCSMATERIA() {
			return PTC_STR_74TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_74TYPEINFOLCSMATERIA(String pTC_STR_74TYPEINFOLCSMATERIA) {
			PTC_STR_74TYPEINFOLCSMATERIA = pTC_STR_74TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_75TYPEINFOLCSMATERIA() {
			return PTC_STR_75TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_75TYPEINFOLCSMATERIA(String pTC_STR_75TYPEINFOLCSMATERIA) {
			PTC_STR_75TYPEINFOLCSMATERIA = pTC_STR_75TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_76TYPEINFOLCSMATERIA() {
			return PTC_STR_76TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_76TYPEINFOLCSMATERIA(String pTC_STR_76TYPEINFOLCSMATERIA) {
			PTC_STR_76TYPEINFOLCSMATERIA = pTC_STR_76TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_77TYPEINFOLCSMATERIA() {
			return PTC_STR_77TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_77TYPEINFOLCSMATERIA(String pTC_STR_77TYPEINFOLCSMATERIA) {
			PTC_STR_77TYPEINFOLCSMATERIA = pTC_STR_77TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_78TYPEINFOLCSMATERIA() {
			return PTC_STR_78TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_78TYPEINFOLCSMATERIA(String pTC_STR_78TYPEINFOLCSMATERIA) {
			PTC_STR_78TYPEINFOLCSMATERIA = pTC_STR_78TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_79TYPEINFOLCSMATERIA() {
			return PTC_STR_79TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_79TYPEINFOLCSMATERIA(String pTC_STR_79TYPEINFOLCSMATERIA) {
			PTC_STR_79TYPEINFOLCSMATERIA = pTC_STR_79TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_80TYPEINFOLCSMATERIA() {
			return PTC_STR_80TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_80TYPEINFOLCSMATERIA(String pTC_STR_80TYPEINFOLCSMATERIA) {
			PTC_STR_80TYPEINFOLCSMATERIA = pTC_STR_80TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_81TYPEINFOLCSMATERIA() {
			return PTC_STR_81TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_81TYPEINFOLCSMATERIA(String pTC_STR_81TYPEINFOLCSMATERIA) {
			PTC_STR_81TYPEINFOLCSMATERIA = pTC_STR_81TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_82TYPEINFOLCSMATERIA() {
			return PTC_STR_82TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_82TYPEINFOLCSMATERIA(String pTC_STR_82TYPEINFOLCSMATERIA) {
			PTC_STR_82TYPEINFOLCSMATERIA = pTC_STR_82TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_83TYPEINFOLCSMATERIA() {
			return PTC_STR_83TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_83TYPEINFOLCSMATERIA(String pTC_STR_83TYPEINFOLCSMATERIA) {
			PTC_STR_83TYPEINFOLCSMATERIA = pTC_STR_83TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_84TYPEINFOLCSMATERIA() {
			return PTC_STR_84TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_84TYPEINFOLCSMATERIA(String pTC_STR_84TYPEINFOLCSMATERIA) {
			PTC_STR_84TYPEINFOLCSMATERIA = pTC_STR_84TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_85TYPEINFOLCSMATERIA() {
			return PTC_STR_85TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_85TYPEINFOLCSMATERIA(String pTC_STR_85TYPEINFOLCSMATERIA) {
			PTC_STR_85TYPEINFOLCSMATERIA = pTC_STR_85TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_86TYPEINFOLCSMATERIA() {
			return PTC_STR_86TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_86TYPEINFOLCSMATERIA(String pTC_STR_86TYPEINFOLCSMATERIA) {
			PTC_STR_86TYPEINFOLCSMATERIA = pTC_STR_86TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_87TYPEINFOLCSMATERIA() {
			return PTC_STR_87TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_87TYPEINFOLCSMATERIA(String pTC_STR_87TYPEINFOLCSMATERIA) {
			PTC_STR_87TYPEINFOLCSMATERIA = pTC_STR_87TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_88TYPEINFOLCSMATERIA() {
			return PTC_STR_88TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_88TYPEINFOLCSMATERIA(String pTC_STR_88TYPEINFOLCSMATERIA) {
			PTC_STR_88TYPEINFOLCSMATERIA = pTC_STR_88TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_89TYPEINFOLCSMATERIA() {
			return PTC_STR_89TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_89TYPEINFOLCSMATERIA(String pTC_STR_89TYPEINFOLCSMATERIA) {
			PTC_STR_89TYPEINFOLCSMATERIA = pTC_STR_89TYPEINFOLCSMATERIA;
		}
		public String getPTC_STR_90TYPEINFOLCSMATERIA() {
			return PTC_STR_90TYPEINFOLCSMATERIA;
		}
		public void setPTC_STR_90TYPEINFOLCSMATERIA(String pTC_STR_90TYPEINFOLCSMATERIA) {
			PTC_STR_90TYPEINFOLCSMATERIA = pTC_STR_90TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_1TYPEINFOLCSMATERIAL() {
			return PTC_DBL_1TYPEINFOLCSMATERIAL;
		}
		public void setPTC_DBL_1TYPEINFOLCSMATERIAL(double pTC_DBL_1TYPEINFOLCSMATERIAL) {
			PTC_DBL_1TYPEINFOLCSMATERIAL = pTC_DBL_1TYPEINFOLCSMATERIAL;
		}
		public double getPTC_DBL_2TYPEINFOLCSMATERIAL() {
			return PTC_DBL_2TYPEINFOLCSMATERIAL;
		}
		public void setPTC_DBL_2TYPEINFOLCSMATERIAL(double pTC_DBL_2TYPEINFOLCSMATERIAL) {
			PTC_DBL_2TYPEINFOLCSMATERIAL = pTC_DBL_2TYPEINFOLCSMATERIAL;
		}
		public double getPTC_DBL_3TYPEINFOLCSMATERIAL() {
			return PTC_DBL_3TYPEINFOLCSMATERIAL;
		}
		public void setPTC_DBL_3TYPEINFOLCSMATERIAL(double pTC_DBL_3TYPEINFOLCSMATERIAL) {
			PTC_DBL_3TYPEINFOLCSMATERIAL = pTC_DBL_3TYPEINFOLCSMATERIAL;
		}
		public double getPTC_DBL_4TYPEINFOLCSMATERIAL() {
			return PTC_DBL_4TYPEINFOLCSMATERIAL;
		}
		public void setPTC_DBL_4TYPEINFOLCSMATERIAL(double pTC_DBL_4TYPEINFOLCSMATERIAL) {
			PTC_DBL_4TYPEINFOLCSMATERIAL = pTC_DBL_4TYPEINFOLCSMATERIAL;
		}
		public double getPTC_DBL_5TYPEINFOLCSMATERIAL() {
			return PTC_DBL_5TYPEINFOLCSMATERIAL;
		}
		public void setPTC_DBL_5TYPEINFOLCSMATERIAL(double pTC_DBL_5TYPEINFOLCSMATERIAL) {
			PTC_DBL_5TYPEINFOLCSMATERIAL = pTC_DBL_5TYPEINFOLCSMATERIAL;
		}
		public double getPTC_DBL_6TYPEINFOLCSMATERIAL() {
			return PTC_DBL_6TYPEINFOLCSMATERIAL;
		}
		public void setPTC_DBL_6TYPEINFOLCSMATERIAL(double pTC_DBL_6TYPEINFOLCSMATERIAL) {
			PTC_DBL_6TYPEINFOLCSMATERIAL = pTC_DBL_6TYPEINFOLCSMATERIAL;
		}
		public double getPTC_DBL_7TYPEINFOLCSMATERIAL() {
			return PTC_DBL_7TYPEINFOLCSMATERIAL;
		}
		public void setPTC_DBL_7TYPEINFOLCSMATERIAL(double pTC_DBL_7TYPEINFOLCSMATERIAL) {
			PTC_DBL_7TYPEINFOLCSMATERIAL = pTC_DBL_7TYPEINFOLCSMATERIAL;
		}
		public double getPTC_DBL_8TYPEINFOLCSMATERIAL() {
			return PTC_DBL_8TYPEINFOLCSMATERIAL;
		}
		public void setPTC_DBL_8TYPEINFOLCSMATERIAL(double pTC_DBL_8TYPEINFOLCSMATERIAL) {
			PTC_DBL_8TYPEINFOLCSMATERIAL = pTC_DBL_8TYPEINFOLCSMATERIAL;
		}
		public double getPTC_DBL_9TYPEINFOLCSMATERIAL() {
			return PTC_DBL_9TYPEINFOLCSMATERIAL;
		}
		public void setPTC_DBL_9TYPEINFOLCSMATERIAL(double pTC_DBL_9TYPEINFOLCSMATERIAL) {
			PTC_DBL_9TYPEINFOLCSMATERIAL = pTC_DBL_9TYPEINFOLCSMATERIAL;
		}
		public double getPTC_DBL_10TYPEINFOLCSMATERIA() {
			return PTC_DBL_10TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_10TYPEINFOLCSMATERIA(double pTC_DBL_10TYPEINFOLCSMATERIA) {
			PTC_DBL_10TYPEINFOLCSMATERIA = pTC_DBL_10TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_11TYPEINFOLCSMATERIA() {
			return PTC_DBL_11TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_11TYPEINFOLCSMATERIA(double pTC_DBL_11TYPEINFOLCSMATERIA) {
			PTC_DBL_11TYPEINFOLCSMATERIA = pTC_DBL_11TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_12TYPEINFOLCSMATERIA() {
			return PTC_DBL_12TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_12TYPEINFOLCSMATERIA(double pTC_DBL_12TYPEINFOLCSMATERIA) {
			PTC_DBL_12TYPEINFOLCSMATERIA = pTC_DBL_12TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_13TYPEINFOLCSMATERIA() {
			return PTC_DBL_13TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_13TYPEINFOLCSMATERIA(double pTC_DBL_13TYPEINFOLCSMATERIA) {
			PTC_DBL_13TYPEINFOLCSMATERIA = pTC_DBL_13TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_14TYPEINFOLCSMATERIA() {
			return PTC_DBL_14TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_14TYPEINFOLCSMATERIA(double pTC_DBL_14TYPEINFOLCSMATERIA) {
			PTC_DBL_14TYPEINFOLCSMATERIA = pTC_DBL_14TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_15TYPEINFOLCSMATERIA() {
			return PTC_DBL_15TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_15TYPEINFOLCSMATERIA(double pTC_DBL_15TYPEINFOLCSMATERIA) {
			PTC_DBL_15TYPEINFOLCSMATERIA = pTC_DBL_15TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_16TYPEINFOLCSMATERIA() {
			return PTC_DBL_16TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_16TYPEINFOLCSMATERIA(double pTC_DBL_16TYPEINFOLCSMATERIA) {
			PTC_DBL_16TYPEINFOLCSMATERIA = pTC_DBL_16TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_17TYPEINFOLCSMATERIA() {
			return PTC_DBL_17TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_17TYPEINFOLCSMATERIA(double pTC_DBL_17TYPEINFOLCSMATERIA) {
			PTC_DBL_17TYPEINFOLCSMATERIA = pTC_DBL_17TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_18TYPEINFOLCSMATERIA() {
			return PTC_DBL_18TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_18TYPEINFOLCSMATERIA(double pTC_DBL_18TYPEINFOLCSMATERIA) {
			PTC_DBL_18TYPEINFOLCSMATERIA = pTC_DBL_18TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_19TYPEINFOLCSMATERIA() {
			return PTC_DBL_19TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_19TYPEINFOLCSMATERIA(double pTC_DBL_19TYPEINFOLCSMATERIA) {
			PTC_DBL_19TYPEINFOLCSMATERIA = pTC_DBL_19TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_20TYPEINFOLCSMATERIA() {
			return PTC_DBL_20TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_20TYPEINFOLCSMATERIA(double pTC_DBL_20TYPEINFOLCSMATERIA) {
			PTC_DBL_20TYPEINFOLCSMATERIA = pTC_DBL_20TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_21TYPEINFOLCSMATERIA() {
			return PTC_DBL_21TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_21TYPEINFOLCSMATERIA(double pTC_DBL_21TYPEINFOLCSMATERIA) {
			PTC_DBL_21TYPEINFOLCSMATERIA = pTC_DBL_21TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_22TYPEINFOLCSMATERIA() {
			return PTC_DBL_22TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_22TYPEINFOLCSMATERIA(double pTC_DBL_22TYPEINFOLCSMATERIA) {
			PTC_DBL_22TYPEINFOLCSMATERIA = pTC_DBL_22TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_23TYPEINFOLCSMATERIA() {
			return PTC_DBL_23TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_23TYPEINFOLCSMATERIA(double pTC_DBL_23TYPEINFOLCSMATERIA) {
			PTC_DBL_23TYPEINFOLCSMATERIA = pTC_DBL_23TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_24TYPEINFOLCSMATERIA() {
			return PTC_DBL_24TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_24TYPEINFOLCSMATERIA(double pTC_DBL_24TYPEINFOLCSMATERIA) {
			PTC_DBL_24TYPEINFOLCSMATERIA = pTC_DBL_24TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_25TYPEINFOLCSMATERIA() {
			return PTC_DBL_25TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_25TYPEINFOLCSMATERIA(double pTC_DBL_25TYPEINFOLCSMATERIA) {
			PTC_DBL_25TYPEINFOLCSMATERIA = pTC_DBL_25TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_26TYPEINFOLCSMATERIA() {
			return PTC_DBL_26TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_26TYPEINFOLCSMATERIA(double pTC_DBL_26TYPEINFOLCSMATERIA) {
			PTC_DBL_26TYPEINFOLCSMATERIA = pTC_DBL_26TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_27TYPEINFOLCSMATERIA() {
			return PTC_DBL_27TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_27TYPEINFOLCSMATERIA(double pTC_DBL_27TYPEINFOLCSMATERIA) {
			PTC_DBL_27TYPEINFOLCSMATERIA = pTC_DBL_27TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_28TYPEINFOLCSMATERIA() {
			return PTC_DBL_28TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_28TYPEINFOLCSMATERIA(double pTC_DBL_28TYPEINFOLCSMATERIA) {
			PTC_DBL_28TYPEINFOLCSMATERIA = pTC_DBL_28TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_29TYPEINFOLCSMATERIA() {
			return PTC_DBL_29TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_29TYPEINFOLCSMATERIA(double pTC_DBL_29TYPEINFOLCSMATERIA) {
			PTC_DBL_29TYPEINFOLCSMATERIA = pTC_DBL_29TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_30TYPEINFOLCSMATERIA() {
			return PTC_DBL_30TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_30TYPEINFOLCSMATERIA(double pTC_DBL_30TYPEINFOLCSMATERIA) {
			PTC_DBL_30TYPEINFOLCSMATERIA = pTC_DBL_30TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_31TYPEINFOLCSMATERIA() {
			return PTC_DBL_31TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_31TYPEINFOLCSMATERIA(double pTC_DBL_31TYPEINFOLCSMATERIA) {
			PTC_DBL_31TYPEINFOLCSMATERIA = pTC_DBL_31TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_32TYPEINFOLCSMATERIA() {
			return PTC_DBL_32TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_32TYPEINFOLCSMATERIA(double pTC_DBL_32TYPEINFOLCSMATERIA) {
			PTC_DBL_32TYPEINFOLCSMATERIA = pTC_DBL_32TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_33TYPEINFOLCSMATERIA() {
			return PTC_DBL_33TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_33TYPEINFOLCSMATERIA(double pTC_DBL_33TYPEINFOLCSMATERIA) {
			PTC_DBL_33TYPEINFOLCSMATERIA = pTC_DBL_33TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_34TYPEINFOLCSMATERIA() {
			return PTC_DBL_34TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_34TYPEINFOLCSMATERIA(double pTC_DBL_34TYPEINFOLCSMATERIA) {
			PTC_DBL_34TYPEINFOLCSMATERIA = pTC_DBL_34TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_35TYPEINFOLCSMATERIA() {
			return PTC_DBL_35TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_35TYPEINFOLCSMATERIA(double pTC_DBL_35TYPEINFOLCSMATERIA) {
			PTC_DBL_35TYPEINFOLCSMATERIA = pTC_DBL_35TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_36TYPEINFOLCSMATERIA() {
			return PTC_DBL_36TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_36TYPEINFOLCSMATERIA(double pTC_DBL_36TYPEINFOLCSMATERIA) {
			PTC_DBL_36TYPEINFOLCSMATERIA = pTC_DBL_36TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_37TYPEINFOLCSMATERIA() {
			return PTC_DBL_37TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_37TYPEINFOLCSMATERIA(double pTC_DBL_37TYPEINFOLCSMATERIA) {
			PTC_DBL_37TYPEINFOLCSMATERIA = pTC_DBL_37TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_38TYPEINFOLCSMATERIA() {
			return PTC_DBL_38TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_38TYPEINFOLCSMATERIA(double pTC_DBL_38TYPEINFOLCSMATERIA) {
			PTC_DBL_38TYPEINFOLCSMATERIA = pTC_DBL_38TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_39TYPEINFOLCSMATERIA() {
			return PTC_DBL_39TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_39TYPEINFOLCSMATERIA(double pTC_DBL_39TYPEINFOLCSMATERIA) {
			PTC_DBL_39TYPEINFOLCSMATERIA = pTC_DBL_39TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_40TYPEINFOLCSMATERIA() {
			return PTC_DBL_40TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_40TYPEINFOLCSMATERIA(double pTC_DBL_40TYPEINFOLCSMATERIA) {
			PTC_DBL_40TYPEINFOLCSMATERIA = pTC_DBL_40TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_41TYPEINFOLCSMATERIA() {
			return PTC_DBL_41TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_41TYPEINFOLCSMATERIA(double pTC_DBL_41TYPEINFOLCSMATERIA) {
			PTC_DBL_41TYPEINFOLCSMATERIA = pTC_DBL_41TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_42TYPEINFOLCSMATERIA() {
			return PTC_DBL_42TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_42TYPEINFOLCSMATERIA(double pTC_DBL_42TYPEINFOLCSMATERIA) {
			PTC_DBL_42TYPEINFOLCSMATERIA = pTC_DBL_42TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_43TYPEINFOLCSMATERIA() {
			return PTC_DBL_43TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_43TYPEINFOLCSMATERIA(double pTC_DBL_43TYPEINFOLCSMATERIA) {
			PTC_DBL_43TYPEINFOLCSMATERIA = pTC_DBL_43TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_44TYPEINFOLCSMATERIA() {
			return PTC_DBL_44TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_44TYPEINFOLCSMATERIA(double pTC_DBL_44TYPEINFOLCSMATERIA) {
			PTC_DBL_44TYPEINFOLCSMATERIA = pTC_DBL_44TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_45TYPEINFOLCSMATERIA() {
			return PTC_DBL_45TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_45TYPEINFOLCSMATERIA(double pTC_DBL_45TYPEINFOLCSMATERIA) {
			PTC_DBL_45TYPEINFOLCSMATERIA = pTC_DBL_45TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_46TYPEINFOLCSMATERIA() {
			return PTC_DBL_46TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_46TYPEINFOLCSMATERIA(double pTC_DBL_46TYPEINFOLCSMATERIA) {
			PTC_DBL_46TYPEINFOLCSMATERIA = pTC_DBL_46TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_47TYPEINFOLCSMATERIA() {
			return PTC_DBL_47TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_47TYPEINFOLCSMATERIA(double pTC_DBL_47TYPEINFOLCSMATERIA) {
			PTC_DBL_47TYPEINFOLCSMATERIA = pTC_DBL_47TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_48TYPEINFOLCSMATERIA() {
			return PTC_DBL_48TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_48TYPEINFOLCSMATERIA(double pTC_DBL_48TYPEINFOLCSMATERIA) {
			PTC_DBL_48TYPEINFOLCSMATERIA = pTC_DBL_48TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_49TYPEINFOLCSMATERIA() {
			return PTC_DBL_49TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_49TYPEINFOLCSMATERIA(double pTC_DBL_49TYPEINFOLCSMATERIA) {
			PTC_DBL_49TYPEINFOLCSMATERIA = pTC_DBL_49TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_50TYPEINFOLCSMATERIA() {
			return PTC_DBL_50TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_50TYPEINFOLCSMATERIA(double pTC_DBL_50TYPEINFOLCSMATERIA) {
			PTC_DBL_50TYPEINFOLCSMATERIA = pTC_DBL_50TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_51TYPEINFOLCSMATERIA() {
			return PTC_DBL_51TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_51TYPEINFOLCSMATERIA(double pTC_DBL_51TYPEINFOLCSMATERIA) {
			PTC_DBL_51TYPEINFOLCSMATERIA = pTC_DBL_51TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_52TYPEINFOLCSMATERIA() {
			return PTC_DBL_52TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_52TYPEINFOLCSMATERIA(double pTC_DBL_52TYPEINFOLCSMATERIA) {
			PTC_DBL_52TYPEINFOLCSMATERIA = pTC_DBL_52TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_53TYPEINFOLCSMATERIA() {
			return PTC_DBL_53TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_53TYPEINFOLCSMATERIA(double pTC_DBL_53TYPEINFOLCSMATERIA) {
			PTC_DBL_53TYPEINFOLCSMATERIA = pTC_DBL_53TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_54TYPEINFOLCSMATERIA() {
			return PTC_DBL_54TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_54TYPEINFOLCSMATERIA(double pTC_DBL_54TYPEINFOLCSMATERIA) {
			PTC_DBL_54TYPEINFOLCSMATERIA = pTC_DBL_54TYPEINFOLCSMATERIA;
		}
		public double getPTC_DBL_55TYPEINFOLCSMATERIA() {
			return PTC_DBL_55TYPEINFOLCSMATERIA;
		}
		public void setPTC_DBL_55TYPEINFOLCSMATERIA(double pTC_DBL_55TYPEINFOLCSMATERIA) {
			PTC_DBL_55TYPEINFOLCSMATERIA = pTC_DBL_55TYPEINFOLCSMATERIA;
		}
		public long getPTC_LNG_1TYPEINFOLCSMATERIAL() {
			return PTC_LNG_1TYPEINFOLCSMATERIAL;
		}
		public void setPTC_LNG_1TYPEINFOLCSMATERIAL(long pTC_LNG_1TYPEINFOLCSMATERIAL) {
			PTC_LNG_1TYPEINFOLCSMATERIAL = pTC_LNG_1TYPEINFOLCSMATERIAL;
		}
		public long getPTC_LNG_2TYPEINFOLCSMATERIAL() {
			return PTC_LNG_2TYPEINFOLCSMATERIAL;
		}
		public void setPTC_LNG_2TYPEINFOLCSMATERIAL(long pTC_LNG_2TYPEINFOLCSMATERIAL) {
			PTC_LNG_2TYPEINFOLCSMATERIAL = pTC_LNG_2TYPEINFOLCSMATERIAL;
		}
		public long getPTC_LNG_3TYPEINFOLCSMATERIAL() {
			return PTC_LNG_3TYPEINFOLCSMATERIAL;
		}
		public void setPTC_LNG_3TYPEINFOLCSMATERIAL(long pTC_LNG_3TYPEINFOLCSMATERIAL) {
			PTC_LNG_3TYPEINFOLCSMATERIAL = pTC_LNG_3TYPEINFOLCSMATERIAL;
		}
		public long getPTC_LNG_4TYPEINFOLCSMATERIAL() {
			return PTC_LNG_4TYPEINFOLCSMATERIAL;
		}
		public void setPTC_LNG_4TYPEINFOLCSMATERIAL(long pTC_LNG_4TYPEINFOLCSMATERIAL) {
			PTC_LNG_4TYPEINFOLCSMATERIAL = pTC_LNG_4TYPEINFOLCSMATERIAL;
		}
		public long getPTC_LNG_5TYPEINFOLCSMATERIAL() {
			return PTC_LNG_5TYPEINFOLCSMATERIAL;
		}
		public void setPTC_LNG_5TYPEINFOLCSMATERIAL(long pTC_LNG_5TYPEINFOLCSMATERIAL) {
			PTC_LNG_5TYPEINFOLCSMATERIAL = pTC_LNG_5TYPEINFOLCSMATERIAL;
		}
		public long getPTC_LNG_6TYPEINFOLCSMATERIAL() {
			return PTC_LNG_6TYPEINFOLCSMATERIAL;
		}
		public void setPTC_LNG_6TYPEINFOLCSMATERIAL(long pTC_LNG_6TYPEINFOLCSMATERIAL) {
			PTC_LNG_6TYPEINFOLCSMATERIAL = pTC_LNG_6TYPEINFOLCSMATERIAL;
		}
		public String getPTC_BLN_1TYPEINFOLCSMATERIAL() {
			return PTC_BLN_1TYPEINFOLCSMATERIAL;
		}
		public void setPTC_BLN_1TYPEINFOLCSMATERIAL(String pTC_BLN_1TYPEINFOLCSMATERIAL) {
			PTC_BLN_1TYPEINFOLCSMATERIAL = pTC_BLN_1TYPEINFOLCSMATERIAL;
		}
		public String getPTC_BLN_2TYPEINFOLCSMATERIAL() {
			return PTC_BLN_2TYPEINFOLCSMATERIAL;
		}
		public void setPTC_BLN_2TYPEINFOLCSMATERIAL(String pTC_BLN_2TYPEINFOLCSMATERIAL) {
			PTC_BLN_2TYPEINFOLCSMATERIAL = pTC_BLN_2TYPEINFOLCSMATERIAL;
		}
		public String getPTC_BLN_3TYPEINFOLCSMATERIAL() {
			return PTC_BLN_3TYPEINFOLCSMATERIAL;
		}
		public void setPTC_BLN_3TYPEINFOLCSMATERIAL(String pTC_BLN_3TYPEINFOLCSMATERIAL) {
			PTC_BLN_3TYPEINFOLCSMATERIAL = pTC_BLN_3TYPEINFOLCSMATERIAL;
		}
		public String getPTC_BLN_4TYPEINFOLCSMATERIAL() {
			return PTC_BLN_4TYPEINFOLCSMATERIAL;
		}
		public void setPTC_BLN_4TYPEINFOLCSMATERIAL(String pTC_BLN_4TYPEINFOLCSMATERIAL) {
			PTC_BLN_4TYPEINFOLCSMATERIAL = pTC_BLN_4TYPEINFOLCSMATERIAL;
		}
		public String getPTC_BLN_5TYPEINFOLCSMATERIAL() {
			return PTC_BLN_5TYPEINFOLCSMATERIAL;
		}
		public void setPTC_BLN_5TYPEINFOLCSMATERIAL(String pTC_BLN_5TYPEINFOLCSMATERIAL) {
			PTC_BLN_5TYPEINFOLCSMATERIAL = pTC_BLN_5TYPEINFOLCSMATERIAL;
		}

		public Date getPTC_TMS_1TYPEINFOLCSMATERIAL() {
			return PTC_TMS_1TYPEINFOLCSMATERIAL;
		}
		public void setPTC_TMS_1TYPEINFOLCSMATERIAL(Date pTC_TMS_1TYPEINFOLCSMATERIAL) {
			PTC_TMS_1TYPEINFOLCSMATERIAL = pTC_TMS_1TYPEINFOLCSMATERIAL;
		}
		public Date getPTC_TMS_2TYPEINFOLCSMATERIAL() {
			return PTC_TMS_2TYPEINFOLCSMATERIAL;
		}
		public void setPTC_TMS_2TYPEINFOLCSMATERIAL(Date pTC_TMS_2TYPEINFOLCSMATERIAL) {
			PTC_TMS_2TYPEINFOLCSMATERIAL = pTC_TMS_2TYPEINFOLCSMATERIAL;
		}
		public Date getPTC_TMS_3TYPEINFOLCSMATERIAL() {
			return PTC_TMS_3TYPEINFOLCSMATERIAL;
		}
		public void setPTC_TMS_3TYPEINFOLCSMATERIAL(Date pTC_TMS_3TYPEINFOLCSMATERIAL) {
			PTC_TMS_3TYPEINFOLCSMATERIAL = pTC_TMS_3TYPEINFOLCSMATERIAL;
		}
		public Date getPTC_TMS_4TYPEINFOLCSMATERIAL() {
			return PTC_TMS_4TYPEINFOLCSMATERIAL;
		}
		public void setPTC_TMS_4TYPEINFOLCSMATERIAL(Date pTC_TMS_4TYPEINFOLCSMATERIAL) {
			PTC_TMS_4TYPEINFOLCSMATERIAL = pTC_TMS_4TYPEINFOLCSMATERIAL;
		}
		public Date getPTC_TMS_5TYPEINFOLCSMATERIAL() {
			return PTC_TMS_5TYPEINFOLCSMATERIAL;
		}
		public void setPTC_TMS_5TYPEINFOLCSMATERIAL(Date pTC_TMS_5TYPEINFOLCSMATERIAL) {
			PTC_TMS_5TYPEINFOLCSMATERIAL = pTC_TMS_5TYPEINFOLCSMATERIAL;
		}
		public Date getPTC_TMS_6TYPEINFOLCSMATERIAL() {
			return PTC_TMS_6TYPEINFOLCSMATERIAL;
		}
		public void setPTC_TMS_6TYPEINFOLCSMATERIAL(Date pTC_TMS_6TYPEINFOLCSMATERIAL) {
			PTC_TMS_6TYPEINFOLCSMATERIAL = pTC_TMS_6TYPEINFOLCSMATERIAL;
		}
		public Date getPTC_TMS_7TYPEINFOLCSMATERIAL() {
			return PTC_TMS_7TYPEINFOLCSMATERIAL;
		}
		public void setPTC_TMS_7TYPEINFOLCSMATERIAL(Date pTC_TMS_7TYPEINFOLCSMATERIAL) {
			PTC_TMS_7TYPEINFOLCSMATERIAL = pTC_TMS_7TYPEINFOLCSMATERIAL;
		}
		public Date getPTC_TMS_8TYPEINFOLCSMATERIAL() {
			return PTC_TMS_8TYPEINFOLCSMATERIAL;
		}
		public void setPTC_TMS_8TYPEINFOLCSMATERIAL(Date pTC_TMS_8TYPEINFOLCSMATERIAL) {
			PTC_TMS_8TYPEINFOLCSMATERIAL = pTC_TMS_8TYPEINFOLCSMATERIAL;
		}
		public Date getPTC_TMS_9TYPEINFOLCSMATERIAL() {
			return PTC_TMS_9TYPEINFOLCSMATERIAL;
		}
		public void setPTC_TMS_9TYPEINFOLCSMATERIAL(Date pTC_TMS_9TYPEINFOLCSMATERIAL) {
			PTC_TMS_9TYPEINFOLCSMATERIAL = pTC_TMS_9TYPEINFOLCSMATERIAL;
		}
		public Date getPTC_TMS_10TYPEINFOLCSMATERIA() {
			return PTC_TMS_10TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_10TYPEINFOLCSMATERIA(Date pTC_TMS_10TYPEINFOLCSMATERIA) {
			PTC_TMS_10TYPEINFOLCSMATERIA = pTC_TMS_10TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_11TYPEINFOLCSMATERIA() {
			return PTC_TMS_11TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_11TYPEINFOLCSMATERIA(Date pTC_TMS_11TYPEINFOLCSMATERIA) {
			PTC_TMS_11TYPEINFOLCSMATERIA = pTC_TMS_11TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_12TYPEINFOLCSMATERIA() {
			return PTC_TMS_12TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_12TYPEINFOLCSMATERIA(Date pTC_TMS_12TYPEINFOLCSMATERIA) {
			PTC_TMS_12TYPEINFOLCSMATERIA = pTC_TMS_12TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_13TYPEINFOLCSMATERIA() {
			return PTC_TMS_13TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_13TYPEINFOLCSMATERIA(Date pTC_TMS_13TYPEINFOLCSMATERIA) {
			PTC_TMS_13TYPEINFOLCSMATERIA = pTC_TMS_13TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_14TYPEINFOLCSMATERIA() {
			return PTC_TMS_14TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_14TYPEINFOLCSMATERIA(Date pTC_TMS_14TYPEINFOLCSMATERIA) {
			PTC_TMS_14TYPEINFOLCSMATERIA = pTC_TMS_14TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_15TYPEINFOLCSMATERIA() {
			return PTC_TMS_15TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_15TYPEINFOLCSMATERIA(Date pTC_TMS_15TYPEINFOLCSMATERIA) {
			PTC_TMS_15TYPEINFOLCSMATERIA = pTC_TMS_15TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_16TYPEINFOLCSMATERIA() {
			return PTC_TMS_16TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_16TYPEINFOLCSMATERIA(Date pTC_TMS_16TYPEINFOLCSMATERIA) {
			PTC_TMS_16TYPEINFOLCSMATERIA = pTC_TMS_16TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_17TYPEINFOLCSMATERIA() {
			return PTC_TMS_17TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_17TYPEINFOLCSMATERIA(Date pTC_TMS_17TYPEINFOLCSMATERIA) {
			PTC_TMS_17TYPEINFOLCSMATERIA = pTC_TMS_17TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_18TYPEINFOLCSMATERIA() {
			return PTC_TMS_18TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_18TYPEINFOLCSMATERIA(Date pTC_TMS_18TYPEINFOLCSMATERIA) {
			PTC_TMS_18TYPEINFOLCSMATERIA = pTC_TMS_18TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_19TYPEINFOLCSMATERIA() {
			return PTC_TMS_19TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_19TYPEINFOLCSMATERIA(Date pTC_TMS_19TYPEINFOLCSMATERIA) {
			PTC_TMS_19TYPEINFOLCSMATERIA = pTC_TMS_19TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_20TYPEINFOLCSMATERIA() {
			return PTC_TMS_20TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_20TYPEINFOLCSMATERIA(Date pTC_TMS_20TYPEINFOLCSMATERIA) {
			PTC_TMS_20TYPEINFOLCSMATERIA = pTC_TMS_20TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_21TYPEINFOLCSMATERIA() {
			return PTC_TMS_21TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_21TYPEINFOLCSMATERIA(Date pTC_TMS_21TYPEINFOLCSMATERIA) {
			PTC_TMS_21TYPEINFOLCSMATERIA = pTC_TMS_21TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_22TYPEINFOLCSMATERIA() {
			return PTC_TMS_22TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_22TYPEINFOLCSMATERIA(Date pTC_TMS_22TYPEINFOLCSMATERIA) {
			PTC_TMS_22TYPEINFOLCSMATERIA = pTC_TMS_22TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_23TYPEINFOLCSMATERIA() {
			return PTC_TMS_23TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_23TYPEINFOLCSMATERIA(Date pTC_TMS_23TYPEINFOLCSMATERIA) {
			PTC_TMS_23TYPEINFOLCSMATERIA = pTC_TMS_23TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_24TYPEINFOLCSMATERIA() {
			return PTC_TMS_24TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_24TYPEINFOLCSMATERIA(Date pTC_TMS_24TYPEINFOLCSMATERIA) {
			PTC_TMS_24TYPEINFOLCSMATERIA = pTC_TMS_24TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_25TYPEINFOLCSMATERIA() {
			return PTC_TMS_25TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_25TYPEINFOLCSMATERIA(Date pTC_TMS_25TYPEINFOLCSMATERIA) {
			PTC_TMS_25TYPEINFOLCSMATERIA = pTC_TMS_25TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_26TYPEINFOLCSMATERIA() {
			return PTC_TMS_26TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_26TYPEINFOLCSMATERIA(Date pTC_TMS_26TYPEINFOLCSMATERIA) {
			PTC_TMS_26TYPEINFOLCSMATERIA = pTC_TMS_26TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_27TYPEINFOLCSMATERIA() {
			return PTC_TMS_27TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_27TYPEINFOLCSMATERIA(Date pTC_TMS_27TYPEINFOLCSMATERIA) {
			PTC_TMS_27TYPEINFOLCSMATERIA = pTC_TMS_27TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_28TYPEINFOLCSMATERIA() {
			return PTC_TMS_28TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_28TYPEINFOLCSMATERIA(Date pTC_TMS_28TYPEINFOLCSMATERIA) {
			PTC_TMS_28TYPEINFOLCSMATERIA = pTC_TMS_28TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_29TYPEINFOLCSMATERIA() {
			return PTC_TMS_29TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_29TYPEINFOLCSMATERIA(Date pTC_TMS_29TYPEINFOLCSMATERIA) {
			PTC_TMS_29TYPEINFOLCSMATERIA = pTC_TMS_29TYPEINFOLCSMATERIA;
		}
		public Date getPTC_TMS_30TYPEINFOLCSMATERIA() {
			return PTC_TMS_30TYPEINFOLCSMATERIA;
		}
		public void setPTC_TMS_30TYPEINFOLCSMATERIA(Date pTC_TMS_30TYPEINFOLCSMATERIA) {
			PTC_TMS_30TYPEINFOLCSMATERIA = pTC_TMS_30TYPEINFOLCSMATERIA;
		}





}
