/**
 * 
 */
package com.qiwkreport.qiwk.etl.domain;

import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * @author abhilash This is Qiwk Color object
 *
 */

@Entity
@Table(name = "QIWKCOLOR")
public class QiwkColor {

	/**
	 * Don't include any id genrator type here when developing actual FR/NC job
	 * use database sequence generator or any other genrator based on business
	 * decision.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "PRIMARYKEY")
	private int PRIMARYKEY;
	@Column(name = "BRANCHID")
	private int BRANCHID;
	@Column(name = "LOADERCREATESTAMP")
	private Timestamp LOADERCREATESTAMP;
	@Column(name = "LOADERUPDATESTAMP")
	private Timestamp LOADERUPDATESTAMP;
	@Column(name = "PTC_STR_11TYPEINFOLCSCOLOR")
	private String PTC_STR_11TYPEINFOLCSCOLOR;
	@Column(name = "CREATESTAMPA2")
	private Date CREATESTAMPA2;
	@Column(name = "UPDATESTAMPA2")
	private Date UPDATESTAMPA2;
	@Column(name = "UPDATECOUNTA2")
	private int UPDATECOUNTA2;
	@Column(name = "MARKEDFORDELETEA2")
	private int MARKEDFORDELETEA2;
	@Column(name = "FLEXTYPEID")
	private int FLEXTYPEID;
	@Column(name = "IDA2TYPEDEFINITIONREFERENCE")
	private int IDA2TYPEDEFINITIONREFERENCE;
	@Column(name = "FLEXTYPEIDPATH")
	private String FLEXTYPEIDPATH;
	@Column(name = "COLORHEXIDECIMALVALUE")
	private String COLORHEXIDECIMALVALUE;
	@Column(name = "THUMBNAIL")
	private String THUMBNAIL;
	@Column(name = "COLORNAME")
	private String COLORNAME;

	/*@Column(name = "BRANCHIDA3E2TYPEINFOLCSCOLOR")
	private int BRANCHIDA3E2TYPEINFOLCSCOLOR;
	@Column(name = "BRANCHIDA3D2TYPEINFOLCSCOLOR")
	private int BRANCHIDA3D2TYPEINFOLCSCOLOR;
	@Column(name = "BRANCHIDA3C2TYPEINFOLCSCOLOR")
	private int BRANCHIDA3C2TYPEINFOLCSCOLOR;
	@Column(name = "BRANCHIDA3B2TYPEINFOLCSCOLOR")
	private int BRANCHIDA3B2TYPEINFOLCSCOLOR;
	@Column(name = "BRANCHIDA3A2TYPEINFOLCSCOLOR")
	private int BRANCHIDA3A2TYPEINFOLCSCOLOR;

	@Column(name = "PTC_DBL_1TYPEINFOLCSCOLOR")
	private double PTC_DBL_1TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_2TYPEINFOLCSCOLOR")
	private double PTC_DBL_2TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_3TYPEINFOLCSCOLOR")
	private double PTC_DBL_3TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_4TYPEINFOLCSCOLOR")
	private double PTC_DBL_4TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_5TYPEINFOLCSCOLOR")
	private double PTC_DBL_5TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_6TYPEINFOLCSCOLOR")
	private double PTC_DBL_6TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_7TYPEINFOLCSCOLOR")
	private double PTC_DBL_7TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_8TYPEINFOLCSCOLOR")
	private double PTC_DBL_8TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_9TYPEINFOLCSCOLOR")
	private double PTC_DBL_9TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_10TYPEINFOLCSCOLOR")
	private double PTC_DBL_10TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_11TYPEINFOLCSCOLOR")
	private double PTC_DBL_11TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_12TYPEINFOLCSCOLOR")
	private double PTC_DBL_12TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_13TYPEINFOLCSCOLOR")
	private double PTC_DBL_13TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_14TYPEINFOLCSCOLOR")
	private double PTC_DBL_14TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_15TYPEINFOLCSCOLOR")
	private double PTC_DBL_15TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_16TYPEINFOLCSCOLOR")
	private double PTC_DBL_16TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_17TYPEINFOLCSCOLOR")
	private double PTC_DBL_17TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_18TYPEINFOLCSCOLOR")
	private double PTC_DBL_18TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_19TYPEINFOLCSCOLOR")
	private double PTC_DBL_19TYPEINFOLCSCOLOR;
	@Column(name = "PTC_DBL_20TYPEINFOLCSCOLOR")
	private double PTC_DBL_20TYPEINFOLCSCOLOR;

	@Column(name = "PTC_STR_1TYPEINFOLCSCOLOR")
	private String PTC_STR_1TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_2TYPEINFOLCSCOLOR")
	private String PTC_STR_2TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_3TYPEINFOLCSCOLOR")
	private String PTC_STR_3TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_4TYPEINFOLCSCOLOR")
	private String PTC_STR_4TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_5TYPEINFOLCSCOLOR")
	private String PTC_STR_5TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_6TYPEINFOLCSCOLOR")
	private String PTC_STR_6TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_7TYPEINFOLCSCOLOR")
	private String PTC_STR_7TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_8TYPEINFOLCSCOLOR")
	private String PTC_STR_8TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_9TYPEINFOLCSCOLOR")
	private String PTC_STR_9TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_10TYPEINFOLCSCOLOR")
	private String PTC_STR_10TYPEINFOLCSCOLOR;

	@Column(name = "PTC_STR_12TYPEINFOLCSCOLOR")
	private String PTC_STR_12TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_13TYPEINFOLCSCOLOR")
	private String PTC_STR_13TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_14TYPEINFOLCSCOLOR")
	private String PTC_STR_14TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_15TYPEINFOLCSCOLOR")
	private String PTC_STR_15TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_16TYPEINFOLCSCOLOR")
	private String PTC_STR_16TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_17TYPEINFOLCSCOLOR")
	private String PTC_STR_17TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_18TYPEINFOLCSCOLOR")
	private String PTC_STR_18TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_19TYPEINFOLCSCOLOR")
	private String PTC_STR_19TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_20TYPEINFOLCSCOLOR")
	private String PTC_STR_20TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_21TYPEINFOLCSCOLOR")
	private String PTC_STR_21TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_22TYPEINFOLCSCOLOR")
	private String PTC_STR_22TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_23TYPEINFOLCSCOLOR")
	private String PTC_STR_23TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_24TYPEINFOLCSCOLOR")
	private String PTC_STR_24TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_25TYPEINFOLCSCOLOR")
	private String PTC_STR_25TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_26TYPEINFOLCSCOLOR")
	private String PTC_STR_26TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_27TYPEINFOLCSCOLOR")
	private String PTC_STR_27TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_28TYPEINFOLCSCOLOR")
	private String PTC_STR_28TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_29TYPEINFOLCSCOLOR")
	private String PTC_STR_29TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_30TYPEINFOLCSCOLOR")
	private String PTC_STR_30TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_31TYPEINFOLCSCOLOR")
	private String PTC_STR_31TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_32TYPEINFOLCSCOLOR")
	private String PTC_STR_32TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_33TYPEINFOLCSCOLOR")
	private String PTC_STR_33TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_34TYPEINFOLCSCOLOR")
	private String PTC_STR_34TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_35TYPEINFOLCSCOLOR")
	private String PTC_STR_35TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_36TYPEINFOLCSCOLOR")
	private String PTC_STR_36TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_37TYPEINFOLCSCOLOR")
	private String PTC_STR_37TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_38TYPEINFOLCSCOLOR")
	private String PTC_STR_38TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_39TYPEINFOLCSCOLOR")
	private String PTC_STR_39TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_40TYPEINFOLCSCOLOR")
	private String PTC_STR_40TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_41TYPEINFOLCSCOLOR")
	private String PTC_STR_41TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_42TYPEINFOLCSCOLOR")
	private String PTC_STR_42TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_43TYPEINFOLCSCOLOR")
	private String PTC_STR_43TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_44TYPEINFOLCSCOLOR")
	private String PTC_STR_44TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_45TYPEINFOLCSCOLOR")
	private String PTC_STR_45TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_46TYPEINFOLCSCOLOR")
	private String PTC_STR_46TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_47TYPEINFOLCSCOLOR")
	private String PTC_STR_47TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_48TYPEINFOLCSCOLOR")
	private String PTC_STR_48TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_49TYPEINFOLCSCOLOR")
	private String PTC_STR_49TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_50TYPEINFOLCSCOLOR")
	private String PTC_STR_50TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_51TYPEINFOLCSCOLOR")
	private String PTC_STR_51TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_52TYPEINFOLCSCOLOR")
	private String PTC_STR_52TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_53TYPEINFOLCSCOLOR")
	private String PTC_STR_53TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_54TYPEINFOLCSCOLOR")
	private String PTC_STR_54TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_55TYPEINFOLCSCOLOR")
	private String PTC_STR_55TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_56TYPEINFOLCSCOLOR")
	private String PTC_STR_56TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_57TYPEINFOLCSCOLOR")
	private String PTC_STR_57TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_58TYPEINFOLCSCOLOR")
	private String PTC_STR_58TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_59TYPEINFOLCSCOLOR")
	private String PTC_STR_59TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_60TYPEINFOLCSCOLOR")
	private String PTC_STR_60TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_61TYPEINFOLCSCOLOR")
	private String PTC_STR_61TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_62TYPEINFOLCSCOLOR")
	private String PTC_STR_62TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_63TYPEINFOLCSCOLOR")
	private String PTC_STR_63TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_64TYPEINFOLCSCOLOR")
	private String PTC_STR_64TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_65TYPEINFOLCSCOLOR")
	private String PTC_STR_65TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_66TYPEINFOLCSCOLOR")
	private String PTC_STR_66TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_67TYPEINFOLCSCOLOR")
	private String PTC_STR_67TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_68TYPEINFOLCSCOLOR")
	private String PTC_STR_68TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_69TYPEINFOLCSCOLOR")
	private String PTC_STR_69TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_70TYPEINFOLCSCOLOR")
	private String PTC_STR_70TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_71TYPEINFOLCSCOLOR")
	private String PTC_STR_71TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_72TYPEINFOLCSCOLOR")
	private String PTC_STR_72TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_73TYPEINFOLCSCOLOR")
	private String PTC_STR_73TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_74TYPEINFOLCSCOLOR")
	private String PTC_STR_74TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_75TYPEINFOLCSCOLOR")
	private String PTC_STR_75TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_76TYPEINFOLCSCOLOR")
	private String PTC_STR_76TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_77TYPEINFOLCSCOLOR")
	private String PTC_STR_77TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_78TYPEINFOLCSCOLOR")
	private String PTC_STR_78TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_79TYPEINFOLCSCOLOR")
	private String PTC_STR_79TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_80TYPEINFOLCSCOLOR")
	private String PTC_STR_80TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_81TYPEINFOLCSCOLOR")
	private String PTC_STR_81TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_82TYPEINFOLCSCOLOR")
	private String PTC_STR_82TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_83TYPEINFOLCSCOLOR")
	private String PTC_STR_83TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_84TYPEINFOLCSCOLOR")
	private String PTC_STR_84TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_85TYPEINFOLCSCOLOR")
	private String PTC_STR_85TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_86TYPEINFOLCSCOLOR")
	private String PTC_STR_86TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_87TYPEINFOLCSCOLOR")
	private String PTC_STR_87TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_88TYPEINFOLCSCOLOR")
	private String PTC_STR_88TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_89TYPEINFOLCSCOLOR")
	private String PTC_STR_89TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_90TYPEINFOLCSCOLOR")
	private String PTC_STR_90TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_91TYPEINFOLCSCOLOR")
	private String PTC_STR_91TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_92TYPEINFOLCSCOLOR")
	private String PTC_STR_92TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_93TYPEINFOLCSCOLOR")
	private String PTC_STR_93TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_94TYPEINFOLCSCOLOR")
	private String PTC_STR_94TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_95TYPEINFOLCSCOLOR")
	private String PTC_STR_95TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_96TYPEINFOLCSCOLOR")
	private String PTC_STR_96TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_97TYPEINFOLCSCOLOR")
	private String PTC_STR_97TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_98TYPEINFOLCSCOLOR")
	private String PTC_STR_98TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_99TYPEINFOLCSCOLOR")
	private String PTC_STR_99TYPEINFOLCSCOLOR;
	@Column(name = "PTC_STR_100TYPEINFOLCSCOLOR")
	private String PTC_STR_100TYPEINFOLCSCOLOR;

	@Column(name = "PTC_LNG_1TYPEINFOLCSCOLOR")
	private long PTC_LNG_1TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_2TYPEINFOLCSCOLOR")
	private long PTC_LNG_2TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_3TYPEINFOLCSCOLOR")
	private long PTC_LNG_3TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_4TYPEINFOLCSCOLOR")
	private long PTC_LNG_4TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_5TYPEINFOLCSCOLOR")
	private long PTC_LNG_5TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_6TYPEINFOLCSCOLOR")
	private long PTC_LNG_6TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_7TYPEINFOLCSCOLOR")
	private long PTC_LNG_7TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_8TYPEINFOLCSCOLOR")
	private long PTC_LNG_8TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_9TYPEINFOLCSCOLOR")
	private long PTC_LNG_9TYPEINFOLCSCOLOR;
	@Column(name = "PTC_LNG_10TYPEINFOLCSCOLOR")
	private long PTC_LNG_10TYPEINFOLCSCOLOR;

	@Column(name = "PTC_TMS_1TYPEINFOLCSCOLOR")
	private Date PTC_TMS_1TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_2TYPEINFOLCSCOLOR")
	private Date PTC_TMS_2TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_3TYPEINFOLCSCOLOR")
	private Date PTC_TMS_3TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_4TYPEINFOLCSCOLOR")
	private Date PTC_TMS_4TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_5TYPEINFOLCSCOLOR")
	private Date PTC_TMS_5TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_6TYPEINFOLCSCOLOR")
	private Date PTC_TMS_6TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_7TYPEINFOLCSCOLOR")
	private Date PTC_TMS_7TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_8TYPEINFOLCSCOLOR")
	private Date PTC_TMS_8TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_9TYPEINFOLCSCOLOR")
	private Date PTC_TMS_9TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_10TYPEINFOLCSCOLOR")
	private Date PTC_TMS_10TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_11TYPEINFOLCSCOLOR")
	private Date PTC_TMS_11TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_12TYPEINFOLCSCOLOR")
	private Date PTC_TMS_12TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_13TYPEINFOLCSCOLOR")
	private Date PTC_TMS_13TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_14TYPEINFOLCSCOLOR")
	private Date PTC_TMS_14TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_15TYPEINFOLCSCOLOR")
	private Date PTC_TMS_15TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_16TYPEINFOLCSCOLOR")
	private Date PTC_TMS_16TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_17TYPEINFOLCSCOLOR")
	private Date PTC_TMS_17TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_18TYPEINFOLCSCOLOR")
	private Date PTC_TMS_18TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_19TYPEINFOLCSCOLOR")
	private Date PTC_TMS_19TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_20TYPEINFOLCSCOLOR")
	private Date PTC_TMS_20TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_21TYPEINFOLCSCOLOR")
	private Date PTC_TMS_21TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_22TYPEINFOLCSCOLOR")
	private Date PTC_TMS_22TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_23TYPEINFOLCSCOLOR")
	private Date PTC_TMS_23TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_24TYPEINFOLCSCOLOR")
	private Date PTC_TMS_24TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_25TYPEINFOLCSCOLOR")
	private Date PTC_TMS_25TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_26TYPEINFOLCSCOLOR")
	private Date PTC_TMS_26TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_27TYPEINFOLCSCOLOR")
	private Date PTC_TMS_27TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_28TYPEINFOLCSCOLOR")
	private Date PTC_TMS_28TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_29TYPEINFOLCSCOLOR")
	private Date PTC_TMS_29TYPEINFOLCSCOLOR;
	@Column(name = "PTC_TMS_30TYPEINFOLCSCOLOR")
	private Date PTC_TMS_30TYPEINFOLCSCOLOR;

	@Column(name = "PTC_BLN_1TYPEINFOLCSCOLOR")
	private String PTC_BLN_1TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_2TYPEINFOLCSCOLOR")
	private String PTC_BLN_2TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_3TYPEINFOLCSCOLOR")
	private String PTC_BLN_3TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_4TYPEINFOLCSCOLOR")
	private String PTC_BLN_4TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_5TYPEINFOLCSCOLOR")
	private String PTC_BLN_5TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_6TYPEINFOLCSCOLOR")
	private String PTC_BLN_6TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_7TYPEINFOLCSCOLOR")
	private String PTC_BLN_7TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_8TYPEINFOLCSCOLOR")
	private String PTC_BLN_8TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_9TYPEINFOLCSCOLOR")
	private String PTC_BLN_9TYPEINFOLCSCOLOR;
	@Column(name = "PTC_BLN_10TYPEINFOLCSCOLOR")
	private String PTC_BLN_10TYPEINFOLCSCOLOR;
*/	
	public QiwkColor() {
		super();
	}

	public QiwkColor(int PRIMARYKEY, int bRANCHID, Timestamp lOADERCREATESTAMP, Timestamp lOADERUPDATESTAMP,
			String pTC_STR_11TYPEINFOLCSCOLOR, Date cREATESTAMPA2, Date uPDATESTAMPA2, int uPDATECOUNTA2,
			int mARKEDFORDELETEA2, int fLEXTYPEID, int iDA2TYPEDEFINITIONREFERENCE, String fLEXTYPEIDPATH,
			String cOLORHEXIDECIMALVALUE, String tHUMBNAIL, String cOLORNAME) {
		super();
		this.PRIMARYKEY = PRIMARYKEY;
		BRANCHID = bRANCHID;
		LOADERCREATESTAMP = lOADERCREATESTAMP;
		LOADERUPDATESTAMP = lOADERUPDATESTAMP;
		PTC_STR_11TYPEINFOLCSCOLOR = pTC_STR_11TYPEINFOLCSCOLOR;
		CREATESTAMPA2 = cREATESTAMPA2;
		UPDATESTAMPA2 = uPDATESTAMPA2;
		UPDATECOUNTA2 = uPDATECOUNTA2;
		MARKEDFORDELETEA2 = mARKEDFORDELETEA2;
		FLEXTYPEID = fLEXTYPEID;
		IDA2TYPEDEFINITIONREFERENCE = iDA2TYPEDEFINITIONREFERENCE;
		FLEXTYPEIDPATH = fLEXTYPEIDPATH;
		COLORHEXIDECIMALVALUE = cOLORHEXIDECIMALVALUE;
		THUMBNAIL = tHUMBNAIL;
		COLORNAME = cOLORNAME;
	}

	public int getPRIMARYKEY() {
		return PRIMARYKEY;
	}

	public void setPRIMARYKEY(int PRIMARYKEY) {
		this.PRIMARYKEY = PRIMARYKEY;
	}

	public int getBRANCHID() {
		return BRANCHID;
	}

	public void setBRANCHID(int bRANCHID) {
		BRANCHID = bRANCHID;
	}

	public Timestamp getLOADERCREATESTAMP() {
		return LOADERCREATESTAMP;
	}

	public void setLOADERCREATESTAMP(Timestamp lOADERCREATESTAMP) {
		LOADERCREATESTAMP = lOADERCREATESTAMP;
	}

	public Timestamp getLOADERUPDATESTAMP() {
		return LOADERUPDATESTAMP;
	}

	public void setLOADERUPDATESTAMP(Timestamp lOADERUPDATESTAMP) {
		LOADERUPDATESTAMP = lOADERUPDATESTAMP;
	}

	public String getPTC_STR_11TYPEINFOLCSCOLOR() {
		return PTC_STR_11TYPEINFOLCSCOLOR;
	}

	public void setPTC_STR_11TYPEINFOLCSCOLOR(String pTC_STR_11TYPEINFOLCSCOLOR) {
		PTC_STR_11TYPEINFOLCSCOLOR = pTC_STR_11TYPEINFOLCSCOLOR;
	}

	public Date getCREATESTAMPA2() {
		return CREATESTAMPA2;
	}

	public void setCREATESTAMPA2(Date cREATESTAMPA2) {
		CREATESTAMPA2 = cREATESTAMPA2;
	}

	public Date getUPDATESTAMPA2() {
		return UPDATESTAMPA2;
	}

	public void setUPDATESTAMPA2(Date uPDATESTAMPA2) {
		UPDATESTAMPA2 = uPDATESTAMPA2;
	}

	public int getUPDATECOUNTA2() {
		return UPDATECOUNTA2;
	}

	public void setUPDATECOUNTA2(int uPDATECOUNTA2) {
		UPDATECOUNTA2 = uPDATECOUNTA2;
	}

	public int getMARKEDFORDELETEA2() {
		return MARKEDFORDELETEA2;
	}

	public void setMARKEDFORDELETEA2(int mARKEDFORDELETEA2) {
		MARKEDFORDELETEA2 = mARKEDFORDELETEA2;
	}

	public int getFLEXTYPEID() {
		return FLEXTYPEID;
	}

	public void setFLEXTYPEID(int fLEXTYPEID) {
		FLEXTYPEID = fLEXTYPEID;
	}

	public int getIDA2TYPEDEFINITIONREFERENCE() {
		return IDA2TYPEDEFINITIONREFERENCE;
	}

	public void setIDA2TYPEDEFINITIONREFERENCE(int iDA2TYPEDEFINITIONREFERENCE) {
		IDA2TYPEDEFINITIONREFERENCE = iDA2TYPEDEFINITIONREFERENCE;
	}

	public String getFLEXTYPEIDPATH() {
		return FLEXTYPEIDPATH;
	}

	public void setFLEXTYPEIDPATH(String fLEXTYPEIDPATH) {
		FLEXTYPEIDPATH = fLEXTYPEIDPATH;
	}

	public String getCOLORHEXIDECIMALVALUE() {
		return COLORHEXIDECIMALVALUE;
	}

	public void setCOLORHEXIDECIMALVALUE(String cOLORHEXIDECIMALVALUE) {
		COLORHEXIDECIMALVALUE = cOLORHEXIDECIMALVALUE;
	}

	public String getTHUMBNAIL() {
		return THUMBNAIL;
	}

	public void setTHUMBNAIL(String tHUMBNAIL) {
		THUMBNAIL = tHUMBNAIL;
	}

	public String getCOLORNAME() {
		return COLORNAME;
	}

	public void setCOLORNAME(String cOLORNAME) {
		COLORNAME = cOLORNAME;
	}

	@Override
	public String toString() {
		return "QiwkColor2 [PRIMARYKEY=" + PRIMARYKEY + ", BRANCHID=" + BRANCHID + ", LOADERCREATESTAMP="
				+ LOADERCREATESTAMP + ", LOADERUPDATESTAMP=" + LOADERUPDATESTAMP + ", PTC_STR_11TYPEINFOLCSCOLOR="
				+ PTC_STR_11TYPEINFOLCSCOLOR + ", CREATESTAMPA2=" + CREATESTAMPA2 + ", UPDATESTAMPA2=" + UPDATESTAMPA2
				+ ", UPDATECOUNTA2=" + UPDATECOUNTA2 + ", MARKEDFORDELETEA2=" + MARKEDFORDELETEA2 + ", FLEXTYPEID="
				+ FLEXTYPEID + ", IDA2TYPEDEFINITIONREFERENCE=" + IDA2TYPEDEFINITIONREFERENCE + ", FLEXTYPEIDPATH="
				+ FLEXTYPEIDPATH + ", COLORHEXIDECIMALVALUE=" + COLORHEXIDECIMALVALUE + ", THUMBNAIL=" + THUMBNAIL
				+ ", COLORNAME=" + COLORNAME + "]";
	}

}
